WITH _temp_view_1 AS (
SELECT /*+ materialize */ F0."tid" AS "tid", F0."c_custkey" AS "c_custkey", F0."c_name" AS "c_name", F0."c_address" AS "c_address", F0."c_nationkey" AS "c_nationkey", F0."c_phone" AS "c_phone", F0."c_acctbal" AS "c_acctbal", F0."c_mktsegment" AS "c_mktsegment", F0."c_comment" AS "c_comment", F0."ub_tid" AS "ub_tid", F0."lb_tid" AS "lb_tid", F0."ub_c_custkey" AS "ub_c_custkey", F0."lb_c_custkey" AS "lb_c_custkey", F0."ub_c_name" AS "ub_c_name", F0."lb_c_name" AS "lb_c_name", F0."ub_c_address" AS "ub_c_address", F0."lb_c_address" AS "lb_c_address", F0."ub_c_nationkey" AS "ub_c_nationkey", F0."lb_c_nationkey" AS "lb_c_nationkey", F0."ub_c_phone" AS "ub_c_phone", F0."lb_c_phone" AS "lb_c_phone", F0."ub_c_acctbal" AS "ub_c_acctbal", F0."lb_c_acctbal" AS "lb_c_acctbal", F0."ub_c_mktsegment" AS "ub_c_mktsegment", F0."lb_c_mktsegment" AS "lb_c_mktsegment", F0."ub_c_comment" AS "ub_c_comment", F0."lb_c_comment" AS "lb_c_comment", F0."cet_r" AS "cet_r", F0."bst_r" AS "bst_r", F0."pos_r" AS "pos_r"
FROM "customer_radb" AS F0),
_temp_view_0 AS (
SELECT /*+ materialize */ F0."tid" AS "tid", F0."c_custkey" AS "c_custkey", F0."c_name" AS "c_name", F0."c_address" AS "c_address", F0."c_nationkey" AS "c_nationkey", F0."c_phone" AS "c_phone", F0."c_acctbal" AS "c_acctbal", F0."c_mktsegment" AS "c_mktsegment", F0."c_comment" AS "c_comment", F0."ub_tid" AS "ub_tid", F0."lb_tid" AS "lb_tid", F0."ub_c_custkey" AS "ub_c_custkey", F0."lb_c_custkey" AS "lb_c_custkey", F0."ub_c_name" AS "ub_c_name", F0."lb_c_name" AS "lb_c_name", F0."ub_c_address" AS "ub_c_address", F0."lb_c_address" AS "lb_c_address", F0."ub_c_nationkey" AS "ub_c_nationkey", F0."lb_c_nationkey" AS "lb_c_nationkey", F0."ub_c_phone" AS "ub_c_phone", F0."lb_c_phone" AS "lb_c_phone", F0."ub_c_acctbal" AS "ub_c_acctbal", F0."lb_c_acctbal" AS "lb_c_acctbal", F0."ub_c_mktsegment" AS "ub_c_mktsegment", F0."lb_c_mktsegment" AS "lb_c_mktsegment", F0."ub_c_comment" AS "ub_c_comment", F0."lb_c_comment" AS "lb_c_comment", (CASE  WHEN ((F0."c_mktsegment" = 'BUILDING') AND ((F0."ub_c_mktsegment" = F0."lb_c_mktsegment") AND ('BUILDING' = 'BUILDING'))) THEN 1 ELSE 0 END) AS "cet_r", (CASE  WHEN (F0."c_mktsegment" = 'BUILDING') THEN 1 ELSE 0 END) AS "bst_r", F0."pos_r" AS "pos_r"
FROM (
SELECT F0."tid" AS "tid", F0."c_custkey" AS "c_custkey", F0."c_name" AS "c_name", F0."c_address" AS "c_address", F0."c_nationkey" AS "c_nationkey", F0."c_phone" AS "c_phone", F0."c_acctbal" AS "c_acctbal", F0."c_mktsegment" AS "c_mktsegment", F0."c_comment" AS "c_comment", F0."ub_tid" AS "ub_tid", F0."lb_tid" AS "lb_tid", F0."ub_c_custkey" AS "ub_c_custkey", F0."lb_c_custkey" AS "lb_c_custkey", F0."ub_c_name" AS "ub_c_name", F0."lb_c_name" AS "lb_c_name", F0."ub_c_address" AS "ub_c_address", F0."lb_c_address" AS "lb_c_address", F0."ub_c_nationkey" AS "ub_c_nationkey", F0."lb_c_nationkey" AS "lb_c_nationkey", F0."ub_c_phone" AS "ub_c_phone", F0."lb_c_phone" AS "lb_c_phone", F0."ub_c_acctbal" AS "ub_c_acctbal", F0."lb_c_acctbal" AS "lb_c_acctbal", F0."ub_c_mktsegment" AS "ub_c_mktsegment", F0."lb_c_mktsegment" AS "lb_c_mktsegment", F0."ub_c_comment" AS "ub_c_comment", F0."lb_c_comment" AS "lb_c_comment", F0."cet_r" AS "cet_r", F0."bst_r" AS "bst_r", F0."pos_r" AS "pos_r"
FROM (SELECT * FROM _temp_view_1) F0) F0
WHERE ((F0."lb_c_mktsegment" <= 'BUILDING') AND (F0."ub_c_mktsegment" >= 'BUILDING'))),
_temp_view_3 AS (
SELECT /*+ materialize */ F0."tid" AS "tid", F0."o_orderkey" AS "o_orderkey", F0."o_custkey" AS "o_custkey", F0."o_orderstatus" AS "o_orderstatus", F0."o_totalprice" AS "o_totalprice", F0."o_orderdate" AS "o_orderdate", F0."o_orderpriority" AS "o_orderpriority", F0."o_clerk" AS "o_clerk", F0."o_shippriority" AS "o_shippriority", F0."o_comment" AS "o_comment", F0."ub_tid" AS "ub_tid", F0."lb_tid" AS "lb_tid", F0."ub_o_orderkey" AS "ub_o_orderkey", F0."lb_o_orderkey" AS "lb_o_orderkey", F0."ub_o_custkey" AS "ub_o_custkey", F0."lb_o_custkey" AS "lb_o_custkey", F0."ub_o_orderstatus" AS "ub_o_orderstatus", F0."lb_o_orderstatus" AS "lb_o_orderstatus", F0."ub_o_totalprice" AS "ub_o_totalprice", F0."lb_o_totalprice" AS "lb_o_totalprice", F0."ub_o_orderdate" AS "ub_o_orderdate", F0."lb_o_orderdate" AS "lb_o_orderdate", F0."ub_o_orderpriority" AS "ub_o_orderpriority", F0."lb_o_orderpriority" AS "lb_o_orderpriority", F0."ub_o_clerk" AS "ub_o_clerk", F0."lb_o_clerk" AS "lb_o_clerk", F0."ub_o_shippriority" AS "ub_o_shippriority", F0."lb_o_shippriority" AS "lb_o_shippriority", F0."ub_o_comment" AS "ub_o_comment", F0."lb_o_comment" AS "lb_o_comment", F0."cet_r" AS "cet_r", F0."bst_r" AS "bst_r", F0."pos_r" AS "pos_r"
FROM "orders_radb" AS F0),
_temp_view_2 AS (
SELECT /*+ materialize */ F0."tid" AS "tid", F0."o_orderkey" AS "o_orderkey", F0."o_custkey" AS "o_custkey", F0."o_orderstatus" AS "o_orderstatus", F0."o_totalprice" AS "o_totalprice", F0."o_orderdate" AS "o_orderdate", F0."o_orderpriority" AS "o_orderpriority", F0."o_clerk" AS "o_clerk", F0."o_shippriority" AS "o_shippriority", F0."o_comment" AS "o_comment", F0."ub_tid" AS "ub_tid", F0."lb_tid" AS "lb_tid", F0."ub_o_orderkey" AS "ub_o_orderkey", F0."lb_o_orderkey" AS "lb_o_orderkey", F0."ub_o_custkey" AS "ub_o_custkey", F0."lb_o_custkey" AS "lb_o_custkey", F0."ub_o_orderstatus" AS "ub_o_orderstatus", F0."lb_o_orderstatus" AS "lb_o_orderstatus", F0."ub_o_totalprice" AS "ub_o_totalprice", F0."lb_o_totalprice" AS "lb_o_totalprice", F0."ub_o_orderdate" AS "ub_o_orderdate", F0."lb_o_orderdate" AS "lb_o_orderdate", F0."ub_o_orderpriority" AS "ub_o_orderpriority", F0."lb_o_orderpriority" AS "lb_o_orderpriority", F0."ub_o_clerk" AS "ub_o_clerk", F0."lb_o_clerk" AS "lb_o_clerk", F0."ub_o_shippriority" AS "ub_o_shippriority", F0."lb_o_shippriority" AS "lb_o_shippriority", F0."ub_o_comment" AS "ub_o_comment", F0."lb_o_comment" AS "lb_o_comment", (CASE  WHEN (F0."lb_o_orderdate" > '1995-03-15') THEN 1 ELSE 0 END) AS "cet_r", (CASE  WHEN (F0."o_orderdate" > '1995-03-15') THEN 1 ELSE 0 END) AS "bst_r", F0."pos_r" AS "pos_r"
FROM (
SELECT F0."tid" AS "tid", F0."o_orderkey" AS "o_orderkey", F0."o_custkey" AS "o_custkey", F0."o_orderstatus" AS "o_orderstatus", F0."o_totalprice" AS "o_totalprice", F0."o_orderdate" AS "o_orderdate", F0."o_orderpriority" AS "o_orderpriority", F0."o_clerk" AS "o_clerk", F0."o_shippriority" AS "o_shippriority", F0."o_comment" AS "o_comment", F0."ub_tid" AS "ub_tid", F0."lb_tid" AS "lb_tid", F0."ub_o_orderkey" AS "ub_o_orderkey", F0."lb_o_orderkey" AS "lb_o_orderkey", F0."ub_o_custkey" AS "ub_o_custkey", F0."lb_o_custkey" AS "lb_o_custkey", F0."ub_o_orderstatus" AS "ub_o_orderstatus", F0."lb_o_orderstatus" AS "lb_o_orderstatus", F0."ub_o_totalprice" AS "ub_o_totalprice", F0."lb_o_totalprice" AS "lb_o_totalprice", F0."ub_o_orderdate" AS "ub_o_orderdate", F0."lb_o_orderdate" AS "lb_o_orderdate", F0."ub_o_orderpriority" AS "ub_o_orderpriority", F0."lb_o_orderpriority" AS "lb_o_orderpriority", F0."ub_o_clerk" AS "ub_o_clerk", F0."lb_o_clerk" AS "lb_o_clerk", F0."ub_o_shippriority" AS "ub_o_shippriority", F0."lb_o_shippriority" AS "lb_o_shippriority", F0."ub_o_comment" AS "ub_o_comment", F0."lb_o_comment" AS "lb_o_comment", F0."cet_r" AS "cet_r", F0."bst_r" AS "bst_r", F0."pos_r" AS "pos_r"
FROM (SELECT * FROM _temp_view_3) F0) F0
WHERE (F0."ub_o_orderdate" > '1995-03-15')),
_temp_view_7 AS (
SELECT /*+ materialize */ F0."tid" AS "tid", F0."c_custkey" AS "c_custkey", F0."c_name" AS "c_name", F0."c_address" AS "c_address", F0."c_nationkey" AS "c_nationkey", F0."c_phone" AS "c_phone", F0."c_acctbal" AS "c_acctbal", F0."c_mktsegment" AS "c_mktsegment", F0."c_comment" AS "c_comment", F0."ub_tid" AS "ub_tid", F0."lb_tid" AS "lb_tid", F0."ub_c_custkey" AS "ub_c_custkey", F0."lb_c_custkey" AS "lb_c_custkey", F0."ub_c_name" AS "ub_c_name", F0."lb_c_name" AS "lb_c_name", F0."ub_c_address" AS "ub_c_address", F0."lb_c_address" AS "lb_c_address", F0."ub_c_nationkey" AS "ub_c_nationkey", F0."lb_c_nationkey" AS "lb_c_nationkey", F0."ub_c_phone" AS "ub_c_phone", F0."lb_c_phone" AS "lb_c_phone", F0."ub_c_acctbal" AS "ub_c_acctbal", F0."lb_c_acctbal" AS "lb_c_acctbal", F0."ub_c_mktsegment" AS "ub_c_mktsegment", F0."lb_c_mktsegment" AS "lb_c_mktsegment", F0."ub_c_comment" AS "ub_c_comment", F0."lb_c_comment" AS "lb_c_comment", F0."cet_r" AS "cet_r", F0."bst_r" AS "bst_r", F0."pos_r" AS "pos_r"
FROM "customer_radb" AS F0),
_temp_view_6 AS (
SELECT /*+ materialize */ F0."tid" AS "tid", F0."c_custkey" AS "c_custkey", F0."c_name" AS "c_name", F0."c_address" AS "c_address", F0."c_nationkey" AS "c_nationkey", F0."c_phone" AS "c_phone", F0."c_acctbal" AS "c_acctbal", F0."c_mktsegment" AS "c_mktsegment", F0."c_comment" AS "c_comment", F0."ub_tid" AS "ub_tid", F0."lb_tid" AS "lb_tid", F0."ub_c_custkey" AS "ub_c_custkey", F0."lb_c_custkey" AS "lb_c_custkey", F0."ub_c_name" AS "ub_c_name", F0."lb_c_name" AS "lb_c_name", F0."ub_c_address" AS "ub_c_address", F0."lb_c_address" AS "lb_c_address", F0."ub_c_nationkey" AS "ub_c_nationkey", F0."lb_c_nationkey" AS "lb_c_nationkey", F0."ub_c_phone" AS "ub_c_phone", F0."lb_c_phone" AS "lb_c_phone", F0."ub_c_acctbal" AS "ub_c_acctbal", F0."lb_c_acctbal" AS "lb_c_acctbal", F0."ub_c_mktsegment" AS "ub_c_mktsegment", F0."lb_c_mktsegment" AS "lb_c_mktsegment", F0."ub_c_comment" AS "ub_c_comment", F0."lb_c_comment" AS "lb_c_comment", (CASE  WHEN ((F0."c_mktsegment" = 'BUILDING') AND ((F0."ub_c_mktsegment" = F0."lb_c_mktsegment") AND ('BUILDING' = 'BUILDING'))) THEN 1 ELSE 0 END) AS "cet_r", (CASE  WHEN (F0."c_mktsegment" = 'BUILDING') THEN 1 ELSE 0 END) AS "bst_r", F0."pos_r" AS "pos_r"
FROM (
SELECT F0."tid" AS "tid", F0."c_custkey" AS "c_custkey", F0."c_name" AS "c_name", F0."c_address" AS "c_address", F0."c_nationkey" AS "c_nationkey", F0."c_phone" AS "c_phone", F0."c_acctbal" AS "c_acctbal", F0."c_mktsegment" AS "c_mktsegment", F0."c_comment" AS "c_comment", F0."ub_tid" AS "ub_tid", F0."lb_tid" AS "lb_tid", F0."ub_c_custkey" AS "ub_c_custkey", F0."lb_c_custkey" AS "lb_c_custkey", F0."ub_c_name" AS "ub_c_name", F0."lb_c_name" AS "lb_c_name", F0."ub_c_address" AS "ub_c_address", F0."lb_c_address" AS "lb_c_address", F0."ub_c_nationkey" AS "ub_c_nationkey", F0."lb_c_nationkey" AS "lb_c_nationkey", F0."ub_c_phone" AS "ub_c_phone", F0."lb_c_phone" AS "lb_c_phone", F0."ub_c_acctbal" AS "ub_c_acctbal", F0."lb_c_acctbal" AS "lb_c_acctbal", F0."ub_c_mktsegment" AS "ub_c_mktsegment", F0."lb_c_mktsegment" AS "lb_c_mktsegment", F0."ub_c_comment" AS "ub_c_comment", F0."lb_c_comment" AS "lb_c_comment", F0."cet_r" AS "cet_r", F0."bst_r" AS "bst_r", F0."pos_r" AS "pos_r"
FROM (SELECT * FROM _temp_view_7) F0) F0
WHERE ((F0."lb_c_mktsegment" <= 'BUILDING') AND (F0."ub_c_mktsegment" >= 'BUILDING'))),
_temp_view_5 AS (
SELECT /*+ materialize */ F0."c_custkey" AS "c_custkey", F0."ub_c_custkey" AS "ub_c_custkey", F0."lb_c_custkey" AS "lb_c_custkey", F0."cet_r" AS "cet_r", F0."bst_r" AS "bst_r", F0."pos_r" AS "pos_r"
FROM (SELECT * FROM _temp_view_6) F0),
_temp_view_4 AS (
SELECT /*+ materialize */ F0."c_custkey" AS "c_custkey", F0."ub_c_custkey" AS "ub_c_custkey", F0."lb_c_custkey" AS "lb_c_custkey", 0 AS "cet_r", 0 AS "bst_r", F0."bst_r" AS "pos_r"
FROM (SELECT * FROM _temp_view_5) F0),
_temp_view_11 AS (
SELECT /*+ materialize */ F0."tid" AS "tid", F0."o_orderkey" AS "o_orderkey", F0."o_custkey" AS "o_custkey", F0."o_orderstatus" AS "o_orderstatus", F0."o_totalprice" AS "o_totalprice", F0."o_orderdate" AS "o_orderdate", F0."o_orderpriority" AS "o_orderpriority", F0."o_clerk" AS "o_clerk", F0."o_shippriority" AS "o_shippriority", F0."o_comment" AS "o_comment", F0."ub_tid" AS "ub_tid", F0."lb_tid" AS "lb_tid", F0."ub_o_orderkey" AS "ub_o_orderkey", F0."lb_o_orderkey" AS "lb_o_orderkey", F0."ub_o_custkey" AS "ub_o_custkey", F0."lb_o_custkey" AS "lb_o_custkey", F0."ub_o_orderstatus" AS "ub_o_orderstatus", F0."lb_o_orderstatus" AS "lb_o_orderstatus", F0."ub_o_totalprice" AS "ub_o_totalprice", F0."lb_o_totalprice" AS "lb_o_totalprice", F0."ub_o_orderdate" AS "ub_o_orderdate", F0."lb_o_orderdate" AS "lb_o_orderdate", F0."ub_o_orderpriority" AS "ub_o_orderpriority", F0."lb_o_orderpriority" AS "lb_o_orderpriority", F0."ub_o_clerk" AS "ub_o_clerk", F0."lb_o_clerk" AS "lb_o_clerk", F0."ub_o_shippriority" AS "ub_o_shippriority", F0."lb_o_shippriority" AS "lb_o_shippriority", F0."ub_o_comment" AS "ub_o_comment", F0."lb_o_comment" AS "lb_o_comment", F0."cet_r" AS "cet_r", F0."bst_r" AS "bst_r", F0."pos_r" AS "pos_r"
FROM "orders_radb" AS F0),
_temp_view_10 AS (
SELECT /*+ materialize */ F0."tid" AS "tid", F0."o_orderkey" AS "o_orderkey", F0."o_custkey" AS "o_custkey", F0."o_orderstatus" AS "o_orderstatus", F0."o_totalprice" AS "o_totalprice", F0."o_orderdate" AS "o_orderdate", F0."o_orderpriority" AS "o_orderpriority", F0."o_clerk" AS "o_clerk", F0."o_shippriority" AS "o_shippriority", F0."o_comment" AS "o_comment", F0."ub_tid" AS "ub_tid", F0."lb_tid" AS "lb_tid", F0."ub_o_orderkey" AS "ub_o_orderkey", F0."lb_o_orderkey" AS "lb_o_orderkey", F0."ub_o_custkey" AS "ub_o_custkey", F0."lb_o_custkey" AS "lb_o_custkey", F0."ub_o_orderstatus" AS "ub_o_orderstatus", F0."lb_o_orderstatus" AS "lb_o_orderstatus", F0."ub_o_totalprice" AS "ub_o_totalprice", F0."lb_o_totalprice" AS "lb_o_totalprice", F0."ub_o_orderdate" AS "ub_o_orderdate", F0."lb_o_orderdate" AS "lb_o_orderdate", F0."ub_o_orderpriority" AS "ub_o_orderpriority", F0."lb_o_orderpriority" AS "lb_o_orderpriority", F0."ub_o_clerk" AS "ub_o_clerk", F0."lb_o_clerk" AS "lb_o_clerk", F0."ub_o_shippriority" AS "ub_o_shippriority", F0."lb_o_shippriority" AS "lb_o_shippriority", F0."ub_o_comment" AS "ub_o_comment", F0."lb_o_comment" AS "lb_o_comment", (CASE  WHEN (F0."lb_o_orderdate" > '1995-03-15') THEN 1 ELSE 0 END) AS "cet_r", (CASE  WHEN (F0."o_orderdate" > '1995-03-15') THEN 1 ELSE 0 END) AS "bst_r", F0."pos_r" AS "pos_r"
FROM (
SELECT F0."tid" AS "tid", F0."o_orderkey" AS "o_orderkey", F0."o_custkey" AS "o_custkey", F0."o_orderstatus" AS "o_orderstatus", F0."o_totalprice" AS "o_totalprice", F0."o_orderdate" AS "o_orderdate", F0."o_orderpriority" AS "o_orderpriority", F0."o_clerk" AS "o_clerk", F0."o_shippriority" AS "o_shippriority", F0."o_comment" AS "o_comment", F0."ub_tid" AS "ub_tid", F0."lb_tid" AS "lb_tid", F0."ub_o_orderkey" AS "ub_o_orderkey", F0."lb_o_orderkey" AS "lb_o_orderkey", F0."ub_o_custkey" AS "ub_o_custkey", F0."lb_o_custkey" AS "lb_o_custkey", F0."ub_o_orderstatus" AS "ub_o_orderstatus", F0."lb_o_orderstatus" AS "lb_o_orderstatus", F0."ub_o_totalprice" AS "ub_o_totalprice", F0."lb_o_totalprice" AS "lb_o_totalprice", F0."ub_o_orderdate" AS "ub_o_orderdate", F0."lb_o_orderdate" AS "lb_o_orderdate", F0."ub_o_orderpriority" AS "ub_o_orderpriority", F0."lb_o_orderpriority" AS "lb_o_orderpriority", F0."ub_o_clerk" AS "ub_o_clerk", F0."lb_o_clerk" AS "lb_o_clerk", F0."ub_o_shippriority" AS "ub_o_shippriority", F0."lb_o_shippriority" AS "lb_o_shippriority", F0."ub_o_comment" AS "ub_o_comment", F0."lb_o_comment" AS "lb_o_comment", F0."cet_r" AS "cet_r", F0."bst_r" AS "bst_r", F0."pos_r" AS "pos_r"
FROM (SELECT * FROM _temp_view_11) F0) F0
WHERE (F0."ub_o_orderdate" > '1995-03-15')),
_temp_view_9 AS (
SELECT /*+ materialize */ F0."o_custkey" AS "o_custkey", F0."o_orderkey" AS "o_orderkey", F0."o_orderdate" AS "o_orderdate", F0."o_shippriority" AS "o_shippriority", F0."ub_o_custkey" AS "ub_o_custkey", F0."lb_o_custkey" AS "lb_o_custkey", F0."ub_o_orderkey" AS "ub_o_orderkey", F0."lb_o_orderkey" AS "lb_o_orderkey", F0."ub_o_orderdate" AS "ub_o_orderdate", F0."lb_o_orderdate" AS "lb_o_orderdate", F0."ub_o_shippriority" AS "ub_o_shippriority", F0."lb_o_shippriority" AS "lb_o_shippriority", F0."cet_r" AS "cet_r", F0."bst_r" AS "bst_r", F0."pos_r" AS "pos_r"
FROM (SELECT * FROM _temp_view_10) F0),
_temp_view_8 AS (
SELECT /*+ materialize */ F0."o_custkey" AS "o_custkey", F0."o_orderkey" AS "o_orderkey", F0."o_orderdate" AS "o_orderdate", F0."o_shippriority" AS "o_shippriority", F0."ub_o_custkey" AS "ub_o_custkey", F0."lb_o_custkey" AS "lb_o_custkey", F0."ub_o_orderkey" AS "ub_o_orderkey", F0."lb_o_orderkey" AS "lb_o_orderkey", F0."ub_o_orderdate" AS "ub_o_orderdate", F0."lb_o_orderdate" AS "lb_o_orderdate", F0."ub_o_shippriority" AS "ub_o_shippriority", F0."lb_o_shippriority" AS "lb_o_shippriority", 0 AS "cet_r", 0 AS "bst_r", F0."bst_r" AS "pos_r"
FROM (SELECT * FROM _temp_view_9) F0),
_temp_view_13 AS (
SELECT /*+ materialize */ F0."tid" AS "tid", F0."l_orderkey" AS "l_orderkey", F0."l_partkey" AS "l_partkey", F0."l_suppkey" AS "l_suppkey", F0."l_linenumber" AS "l_linenumber", F0."l_quantity" AS "l_quantity", F0."l_extendedprice" AS "l_extendedprice", F0."l_discount" AS "l_discount", F0."l_tax" AS "l_tax", F0."l_returnflag" AS "l_returnflag", F0."l_linestatus" AS "l_linestatus", F0."l_shipdate" AS "l_shipdate", F0."l_commitdate" AS "l_commitdate", F0."l_receiptdate" AS "l_receiptdate", F0."l_shipinstruct" AS "l_shipinstruct", F0."l_shipmode" AS "l_shipmode", F0."l_comment" AS "l_comment", F0."ub_tid" AS "ub_tid", F0."lb_tid" AS "lb_tid", F0."ub_l_orderkey" AS "ub_l_orderkey", F0."lb_l_orderkey" AS "lb_l_orderkey", F0."ub_l_partkey" AS "ub_l_partkey", F0."lb_l_partkey" AS "lb_l_partkey", F0."ub_l_suppkey" AS "ub_l_suppkey", F0."lb_l_suppkey" AS "lb_l_suppkey", F0."ub_l_linenumber" AS "ub_l_linenumber", F0."lb_l_linenumber" AS "lb_l_linenumber", F0."ub_l_quantity" AS "ub_l_quantity", F0."lb_l_quantity" AS "lb_l_quantity", F0."ub_l_extendedprice" AS "ub_l_extendedprice", F0."lb_l_extendedprice" AS "lb_l_extendedprice", F0."ub_l_discount" AS "ub_l_discount", F0."lb_l_discount" AS "lb_l_discount", F0."ub_l_tax" AS "ub_l_tax", F0."lb_l_tax" AS "lb_l_tax", F0."ub_l_returnflag" AS "ub_l_returnflag", F0."lb_l_returnflag" AS "lb_l_returnflag", F0."ub_l_linestatus" AS "ub_l_linestatus", F0."lb_l_linestatus" AS "lb_l_linestatus", F0."ub_l_shipdate" AS "ub_l_shipdate", F0."lb_l_shipdate" AS "lb_l_shipdate", F0."ub_l_commitdate" AS "ub_l_commitdate", F0."lb_l_commitdate" AS "lb_l_commitdate", F0."ub_l_receiptdate" AS "ub_l_receiptdate", F0."lb_l_receiptdate" AS "lb_l_receiptdate", F0."ub_l_shipinstruct" AS "ub_l_shipinstruct", F0."lb_l_shipinstruct" AS "lb_l_shipinstruct", F0."ub_l_shipmode" AS "ub_l_shipmode", F0."lb_l_shipmode" AS "lb_l_shipmode", F0."ub_l_comment" AS "ub_l_comment", F0."lb_l_comment" AS "lb_l_comment", F0."cet_r" AS "cet_r", F0."bst_r" AS "bst_r", F0."pos_r" AS "pos_r"
FROM "lineitem_radb" AS F0),
_temp_view_12 AS (
SELECT /*+ materialize */ F0."tid" AS "tid", F0."l_orderkey" AS "l_orderkey", F0."l_partkey" AS "l_partkey", F0."l_suppkey" AS "l_suppkey", F0."l_linenumber" AS "l_linenumber", F0."l_quantity" AS "l_quantity", F0."l_extendedprice" AS "l_extendedprice", F0."l_discount" AS "l_discount", F0."l_tax" AS "l_tax", F0."l_returnflag" AS "l_returnflag", F0."l_linestatus" AS "l_linestatus", F0."l_shipdate" AS "l_shipdate", F0."l_commitdate" AS "l_commitdate", F0."l_receiptdate" AS "l_receiptdate", F0."l_shipinstruct" AS "l_shipinstruct", F0."l_shipmode" AS "l_shipmode", F0."l_comment" AS "l_comment", F0."ub_tid" AS "ub_tid", F0."lb_tid" AS "lb_tid", F0."ub_l_orderkey" AS "ub_l_orderkey", F0."lb_l_orderkey" AS "lb_l_orderkey", F0."ub_l_partkey" AS "ub_l_partkey", F0."lb_l_partkey" AS "lb_l_partkey", F0."ub_l_suppkey" AS "ub_l_suppkey", F0."lb_l_suppkey" AS "lb_l_suppkey", F0."ub_l_linenumber" AS "ub_l_linenumber", F0."lb_l_linenumber" AS "lb_l_linenumber", F0."ub_l_quantity" AS "ub_l_quantity", F0."lb_l_quantity" AS "lb_l_quantity", F0."ub_l_extendedprice" AS "ub_l_extendedprice", F0."lb_l_extendedprice" AS "lb_l_extendedprice", F0."ub_l_discount" AS "ub_l_discount", F0."lb_l_discount" AS "lb_l_discount", F0."ub_l_tax" AS "ub_l_tax", F0."lb_l_tax" AS "lb_l_tax", F0."ub_l_returnflag" AS "ub_l_returnflag", F0."lb_l_returnflag" AS "lb_l_returnflag", F0."ub_l_linestatus" AS "ub_l_linestatus", F0."lb_l_linestatus" AS "lb_l_linestatus", F0."ub_l_shipdate" AS "ub_l_shipdate", F0."lb_l_shipdate" AS "lb_l_shipdate", F0."ub_l_commitdate" AS "ub_l_commitdate", F0."lb_l_commitdate" AS "lb_l_commitdate", F0."ub_l_receiptdate" AS "ub_l_receiptdate", F0."lb_l_receiptdate" AS "lb_l_receiptdate", F0."ub_l_shipinstruct" AS "ub_l_shipinstruct", F0."lb_l_shipinstruct" AS "lb_l_shipinstruct", F0."ub_l_shipmode" AS "ub_l_shipmode", F0."lb_l_shipmode" AS "lb_l_shipmode", F0."ub_l_comment" AS "ub_l_comment", F0."lb_l_comment" AS "lb_l_comment", (CASE  WHEN (F0."ub_l_shipdate" < '1995-03-17') THEN 1 ELSE 0 END) AS "cet_r", (CASE  WHEN (F0."l_shipdate" < '1995-03-17') THEN 1 ELSE 0 END) AS "bst_r", F0."pos_r" AS "pos_r"
FROM (
SELECT F0."tid" AS "tid", F0."l_orderkey" AS "l_orderkey", F0."l_partkey" AS "l_partkey", F0."l_suppkey" AS "l_suppkey", F0."l_linenumber" AS "l_linenumber", F0."l_quantity" AS "l_quantity", F0."l_extendedprice" AS "l_extendedprice", F0."l_discount" AS "l_discount", F0."l_tax" AS "l_tax", F0."l_returnflag" AS "l_returnflag", F0."l_linestatus" AS "l_linestatus", F0."l_shipdate" AS "l_shipdate", F0."l_commitdate" AS "l_commitdate", F0."l_receiptdate" AS "l_receiptdate", F0."l_shipinstruct" AS "l_shipinstruct", F0."l_shipmode" AS "l_shipmode", F0."l_comment" AS "l_comment", F0."ub_tid" AS "ub_tid", F0."lb_tid" AS "lb_tid", F0."ub_l_orderkey" AS "ub_l_orderkey", F0."lb_l_orderkey" AS "lb_l_orderkey", F0."ub_l_partkey" AS "ub_l_partkey", F0."lb_l_partkey" AS "lb_l_partkey", F0."ub_l_suppkey" AS "ub_l_suppkey", F0."lb_l_suppkey" AS "lb_l_suppkey", F0."ub_l_linenumber" AS "ub_l_linenumber", F0."lb_l_linenumber" AS "lb_l_linenumber", F0."ub_l_quantity" AS "ub_l_quantity", F0."lb_l_quantity" AS "lb_l_quantity", F0."ub_l_extendedprice" AS "ub_l_extendedprice", F0."lb_l_extendedprice" AS "lb_l_extendedprice", F0."ub_l_discount" AS "ub_l_discount", F0."lb_l_discount" AS "lb_l_discount", F0."ub_l_tax" AS "ub_l_tax", F0."lb_l_tax" AS "lb_l_tax", F0."ub_l_returnflag" AS "ub_l_returnflag", F0."lb_l_returnflag" AS "lb_l_returnflag", F0."ub_l_linestatus" AS "ub_l_linestatus", F0."lb_l_linestatus" AS "lb_l_linestatus", F0."ub_l_shipdate" AS "ub_l_shipdate", F0."lb_l_shipdate" AS "lb_l_shipdate", F0."ub_l_commitdate" AS "ub_l_commitdate", F0."lb_l_commitdate" AS "lb_l_commitdate", F0."ub_l_receiptdate" AS "ub_l_receiptdate", F0."lb_l_receiptdate" AS "lb_l_receiptdate", F0."ub_l_shipinstruct" AS "ub_l_shipinstruct", F0."lb_l_shipinstruct" AS "lb_l_shipinstruct", F0."ub_l_shipmode" AS "ub_l_shipmode", F0."lb_l_shipmode" AS "lb_l_shipmode", F0."ub_l_comment" AS "ub_l_comment", F0."lb_l_comment" AS "lb_l_comment", F0."cet_r" AS "cet_r", F0."bst_r" AS "bst_r", F0."pos_r" AS "pos_r"
FROM (SELECT * FROM _temp_view_13) F0) F0
WHERE (F0."lb_l_shipdate" < '1995-03-17')),
_temp_view_17 AS (
SELECT /*+ materialize */ F0."tid" AS "tid", F0."c_custkey" AS "c_custkey", F0."c_name" AS "c_name", F0."c_address" AS "c_address", F0."c_nationkey" AS "c_nationkey", F0."c_phone" AS "c_phone", F0."c_acctbal" AS "c_acctbal", F0."c_mktsegment" AS "c_mktsegment", F0."c_comment" AS "c_comment", F0."ub_tid" AS "ub_tid", F0."lb_tid" AS "lb_tid", F0."ub_c_custkey" AS "ub_c_custkey", F0."lb_c_custkey" AS "lb_c_custkey", F0."ub_c_name" AS "ub_c_name", F0."lb_c_name" AS "lb_c_name", F0."ub_c_address" AS "ub_c_address", F0."lb_c_address" AS "lb_c_address", F0."ub_c_nationkey" AS "ub_c_nationkey", F0."lb_c_nationkey" AS "lb_c_nationkey", F0."ub_c_phone" AS "ub_c_phone", F0."lb_c_phone" AS "lb_c_phone", F0."ub_c_acctbal" AS "ub_c_acctbal", F0."lb_c_acctbal" AS "lb_c_acctbal", F0."ub_c_mktsegment" AS "ub_c_mktsegment", F0."lb_c_mktsegment" AS "lb_c_mktsegment", F0."ub_c_comment" AS "ub_c_comment", F0."lb_c_comment" AS "lb_c_comment", F0."cet_r" AS "cet_r", F0."bst_r" AS "bst_r", F0."pos_r" AS "pos_r"
FROM "customer_radb" AS F0),
_temp_view_16 AS (
SELECT /*+ materialize */ F0."tid" AS "tid", F0."c_custkey" AS "c_custkey", F0."c_name" AS "c_name", F0."c_address" AS "c_address", F0."c_nationkey" AS "c_nationkey", F0."c_phone" AS "c_phone", F0."c_acctbal" AS "c_acctbal", F0."c_mktsegment" AS "c_mktsegment", F0."c_comment" AS "c_comment", F0."ub_tid" AS "ub_tid", F0."lb_tid" AS "lb_tid", F0."ub_c_custkey" AS "ub_c_custkey", F0."lb_c_custkey" AS "lb_c_custkey", F0."ub_c_name" AS "ub_c_name", F0."lb_c_name" AS "lb_c_name", F0."ub_c_address" AS "ub_c_address", F0."lb_c_address" AS "lb_c_address", F0."ub_c_nationkey" AS "ub_c_nationkey", F0."lb_c_nationkey" AS "lb_c_nationkey", F0."ub_c_phone" AS "ub_c_phone", F0."lb_c_phone" AS "lb_c_phone", F0."ub_c_acctbal" AS "ub_c_acctbal", F0."lb_c_acctbal" AS "lb_c_acctbal", F0."ub_c_mktsegment" AS "ub_c_mktsegment", F0."lb_c_mktsegment" AS "lb_c_mktsegment", F0."ub_c_comment" AS "ub_c_comment", F0."lb_c_comment" AS "lb_c_comment", (CASE  WHEN ((F0."c_mktsegment" = 'BUILDING') AND ((F0."ub_c_mktsegment" = F0."lb_c_mktsegment") AND ('BUILDING' = 'BUILDING'))) THEN 1 ELSE 0 END) AS "cet_r", (CASE  WHEN (F0."c_mktsegment" = 'BUILDING') THEN 1 ELSE 0 END) AS "bst_r", F0."pos_r" AS "pos_r"
FROM (
SELECT F0."tid" AS "tid", F0."c_custkey" AS "c_custkey", F0."c_name" AS "c_name", F0."c_address" AS "c_address", F0."c_nationkey" AS "c_nationkey", F0."c_phone" AS "c_phone", F0."c_acctbal" AS "c_acctbal", F0."c_mktsegment" AS "c_mktsegment", F0."c_comment" AS "c_comment", F0."ub_tid" AS "ub_tid", F0."lb_tid" AS "lb_tid", F0."ub_c_custkey" AS "ub_c_custkey", F0."lb_c_custkey" AS "lb_c_custkey", F0."ub_c_name" AS "ub_c_name", F0."lb_c_name" AS "lb_c_name", F0."ub_c_address" AS "ub_c_address", F0."lb_c_address" AS "lb_c_address", F0."ub_c_nationkey" AS "ub_c_nationkey", F0."lb_c_nationkey" AS "lb_c_nationkey", F0."ub_c_phone" AS "ub_c_phone", F0."lb_c_phone" AS "lb_c_phone", F0."ub_c_acctbal" AS "ub_c_acctbal", F0."lb_c_acctbal" AS "lb_c_acctbal", F0."ub_c_mktsegment" AS "ub_c_mktsegment", F0."lb_c_mktsegment" AS "lb_c_mktsegment", F0."ub_c_comment" AS "ub_c_comment", F0."lb_c_comment" AS "lb_c_comment", F0."cet_r" AS "cet_r", F0."bst_r" AS "bst_r", F0."pos_r" AS "pos_r"
FROM (SELECT * FROM _temp_view_17) F0) F0
WHERE ((F0."lb_c_mktsegment" <= 'BUILDING') AND (F0."ub_c_mktsegment" >= 'BUILDING'))),
_temp_view_19 AS (
SELECT /*+ materialize */ F0."tid" AS "tid", F0."o_orderkey" AS "o_orderkey", F0."o_custkey" AS "o_custkey", F0."o_orderstatus" AS "o_orderstatus", F0."o_totalprice" AS "o_totalprice", F0."o_orderdate" AS "o_orderdate", F0."o_orderpriority" AS "o_orderpriority", F0."o_clerk" AS "o_clerk", F0."o_shippriority" AS "o_shippriority", F0."o_comment" AS "o_comment", F0."ub_tid" AS "ub_tid", F0."lb_tid" AS "lb_tid", F0."ub_o_orderkey" AS "ub_o_orderkey", F0."lb_o_orderkey" AS "lb_o_orderkey", F0."ub_o_custkey" AS "ub_o_custkey", F0."lb_o_custkey" AS "lb_o_custkey", F0."ub_o_orderstatus" AS "ub_o_orderstatus", F0."lb_o_orderstatus" AS "lb_o_orderstatus", F0."ub_o_totalprice" AS "ub_o_totalprice", F0."lb_o_totalprice" AS "lb_o_totalprice", F0."ub_o_orderdate" AS "ub_o_orderdate", F0."lb_o_orderdate" AS "lb_o_orderdate", F0."ub_o_orderpriority" AS "ub_o_orderpriority", F0."lb_o_orderpriority" AS "lb_o_orderpriority", F0."ub_o_clerk" AS "ub_o_clerk", F0."lb_o_clerk" AS "lb_o_clerk", F0."ub_o_shippriority" AS "ub_o_shippriority", F0."lb_o_shippriority" AS "lb_o_shippriority", F0."ub_o_comment" AS "ub_o_comment", F0."lb_o_comment" AS "lb_o_comment", F0."cet_r" AS "cet_r", F0."bst_r" AS "bst_r", F0."pos_r" AS "pos_r"
FROM "orders_radb" AS F0),
_temp_view_18 AS (
SELECT /*+ materialize */ F0."tid" AS "tid", F0."o_orderkey" AS "o_orderkey", F0."o_custkey" AS "o_custkey", F0."o_orderstatus" AS "o_orderstatus", F0."o_totalprice" AS "o_totalprice", F0."o_orderdate" AS "o_orderdate", F0."o_orderpriority" AS "o_orderpriority", F0."o_clerk" AS "o_clerk", F0."o_shippriority" AS "o_shippriority", F0."o_comment" AS "o_comment", F0."ub_tid" AS "ub_tid", F0."lb_tid" AS "lb_tid", F0."ub_o_orderkey" AS "ub_o_orderkey", F0."lb_o_orderkey" AS "lb_o_orderkey", F0."ub_o_custkey" AS "ub_o_custkey", F0."lb_o_custkey" AS "lb_o_custkey", F0."ub_o_orderstatus" AS "ub_o_orderstatus", F0."lb_o_orderstatus" AS "lb_o_orderstatus", F0."ub_o_totalprice" AS "ub_o_totalprice", F0."lb_o_totalprice" AS "lb_o_totalprice", F0."ub_o_orderdate" AS "ub_o_orderdate", F0."lb_o_orderdate" AS "lb_o_orderdate", F0."ub_o_orderpriority" AS "ub_o_orderpriority", F0."lb_o_orderpriority" AS "lb_o_orderpriority", F0."ub_o_clerk" AS "ub_o_clerk", F0."lb_o_clerk" AS "lb_o_clerk", F0."ub_o_shippriority" AS "ub_o_shippriority", F0."lb_o_shippriority" AS "lb_o_shippriority", F0."ub_o_comment" AS "ub_o_comment", F0."lb_o_comment" AS "lb_o_comment", (CASE  WHEN (F0."lb_o_orderdate" > '1995-03-15') THEN 1 ELSE 0 END) AS "cet_r", (CASE  WHEN (F0."o_orderdate" > '1995-03-15') THEN 1 ELSE 0 END) AS "bst_r", F0."pos_r" AS "pos_r"
FROM (
SELECT F0."tid" AS "tid", F0."o_orderkey" AS "o_orderkey", F0."o_custkey" AS "o_custkey", F0."o_orderstatus" AS "o_orderstatus", F0."o_totalprice" AS "o_totalprice", F0."o_orderdate" AS "o_orderdate", F0."o_orderpriority" AS "o_orderpriority", F0."o_clerk" AS "o_clerk", F0."o_shippriority" AS "o_shippriority", F0."o_comment" AS "o_comment", F0."ub_tid" AS "ub_tid", F0."lb_tid" AS "lb_tid", F0."ub_o_orderkey" AS "ub_o_orderkey", F0."lb_o_orderkey" AS "lb_o_orderkey", F0."ub_o_custkey" AS "ub_o_custkey", F0."lb_o_custkey" AS "lb_o_custkey", F0."ub_o_orderstatus" AS "ub_o_orderstatus", F0."lb_o_orderstatus" AS "lb_o_orderstatus", F0."ub_o_totalprice" AS "ub_o_totalprice", F0."lb_o_totalprice" AS "lb_o_totalprice", F0."ub_o_orderdate" AS "ub_o_orderdate", F0."lb_o_orderdate" AS "lb_o_orderdate", F0."ub_o_orderpriority" AS "ub_o_orderpriority", F0."lb_o_orderpriority" AS "lb_o_orderpriority", F0."ub_o_clerk" AS "ub_o_clerk", F0."lb_o_clerk" AS "lb_o_clerk", F0."ub_o_shippriority" AS "ub_o_shippriority", F0."lb_o_shippriority" AS "lb_o_shippriority", F0."ub_o_comment" AS "ub_o_comment", F0."lb_o_comment" AS "lb_o_comment", F0."cet_r" AS "cet_r", F0."bst_r" AS "bst_r", F0."pos_r" AS "pos_r"
FROM (SELECT * FROM _temp_view_19) F0) F0
WHERE (F0."ub_o_orderdate" > '1995-03-15')),
_temp_view_23 AS (
SELECT /*+ materialize */ F0."tid" AS "tid", F0."c_custkey" AS "c_custkey", F0."c_name" AS "c_name", F0."c_address" AS "c_address", F0."c_nationkey" AS "c_nationkey", F0."c_phone" AS "c_phone", F0."c_acctbal" AS "c_acctbal", F0."c_mktsegment" AS "c_mktsegment", F0."c_comment" AS "c_comment", F0."ub_tid" AS "ub_tid", F0."lb_tid" AS "lb_tid", F0."ub_c_custkey" AS "ub_c_custkey", F0."lb_c_custkey" AS "lb_c_custkey", F0."ub_c_name" AS "ub_c_name", F0."lb_c_name" AS "lb_c_name", F0."ub_c_address" AS "ub_c_address", F0."lb_c_address" AS "lb_c_address", F0."ub_c_nationkey" AS "ub_c_nationkey", F0."lb_c_nationkey" AS "lb_c_nationkey", F0."ub_c_phone" AS "ub_c_phone", F0."lb_c_phone" AS "lb_c_phone", F0."ub_c_acctbal" AS "ub_c_acctbal", F0."lb_c_acctbal" AS "lb_c_acctbal", F0."ub_c_mktsegment" AS "ub_c_mktsegment", F0."lb_c_mktsegment" AS "lb_c_mktsegment", F0."ub_c_comment" AS "ub_c_comment", F0."lb_c_comment" AS "lb_c_comment", F0."cet_r" AS "cet_r", F0."bst_r" AS "bst_r", F0."pos_r" AS "pos_r"
FROM "customer_radb" AS F0),
_temp_view_22 AS (
SELECT /*+ materialize */ F0."tid" AS "tid", F0."c_custkey" AS "c_custkey", F0."c_name" AS "c_name", F0."c_address" AS "c_address", F0."c_nationkey" AS "c_nationkey", F0."c_phone" AS "c_phone", F0."c_acctbal" AS "c_acctbal", F0."c_mktsegment" AS "c_mktsegment", F0."c_comment" AS "c_comment", F0."ub_tid" AS "ub_tid", F0."lb_tid" AS "lb_tid", F0."ub_c_custkey" AS "ub_c_custkey", F0."lb_c_custkey" AS "lb_c_custkey", F0."ub_c_name" AS "ub_c_name", F0."lb_c_name" AS "lb_c_name", F0."ub_c_address" AS "ub_c_address", F0."lb_c_address" AS "lb_c_address", F0."ub_c_nationkey" AS "ub_c_nationkey", F0."lb_c_nationkey" AS "lb_c_nationkey", F0."ub_c_phone" AS "ub_c_phone", F0."lb_c_phone" AS "lb_c_phone", F0."ub_c_acctbal" AS "ub_c_acctbal", F0."lb_c_acctbal" AS "lb_c_acctbal", F0."ub_c_mktsegment" AS "ub_c_mktsegment", F0."lb_c_mktsegment" AS "lb_c_mktsegment", F0."ub_c_comment" AS "ub_c_comment", F0."lb_c_comment" AS "lb_c_comment", (CASE  WHEN ((F0."c_mktsegment" = 'BUILDING') AND ((F0."ub_c_mktsegment" = F0."lb_c_mktsegment") AND ('BUILDING' = 'BUILDING'))) THEN 1 ELSE 0 END) AS "cet_r", (CASE  WHEN (F0."c_mktsegment" = 'BUILDING') THEN 1 ELSE 0 END) AS "bst_r", F0."pos_r" AS "pos_r"
FROM (
SELECT F0."tid" AS "tid", F0."c_custkey" AS "c_custkey", F0."c_name" AS "c_name", F0."c_address" AS "c_address", F0."c_nationkey" AS "c_nationkey", F0."c_phone" AS "c_phone", F0."c_acctbal" AS "c_acctbal", F0."c_mktsegment" AS "c_mktsegment", F0."c_comment" AS "c_comment", F0."ub_tid" AS "ub_tid", F0."lb_tid" AS "lb_tid", F0."ub_c_custkey" AS "ub_c_custkey", F0."lb_c_custkey" AS "lb_c_custkey", F0."ub_c_name" AS "ub_c_name", F0."lb_c_name" AS "lb_c_name", F0."ub_c_address" AS "ub_c_address", F0."lb_c_address" AS "lb_c_address", F0."ub_c_nationkey" AS "ub_c_nationkey", F0."lb_c_nationkey" AS "lb_c_nationkey", F0."ub_c_phone" AS "ub_c_phone", F0."lb_c_phone" AS "lb_c_phone", F0."ub_c_acctbal" AS "ub_c_acctbal", F0."lb_c_acctbal" AS "lb_c_acctbal", F0."ub_c_mktsegment" AS "ub_c_mktsegment", F0."lb_c_mktsegment" AS "lb_c_mktsegment", F0."ub_c_comment" AS "ub_c_comment", F0."lb_c_comment" AS "lb_c_comment", F0."cet_r" AS "cet_r", F0."bst_r" AS "bst_r", F0."pos_r" AS "pos_r"
FROM (SELECT * FROM _temp_view_23) F0) F0
WHERE ((F0."lb_c_mktsegment" <= 'BUILDING') AND (F0."ub_c_mktsegment" >= 'BUILDING'))),
_temp_view_21 AS (
SELECT /*+ materialize */ F0."c_custkey" AS "c_custkey", F0."ub_c_custkey" AS "ub_c_custkey", F0."lb_c_custkey" AS "lb_c_custkey", F0."cet_r" AS "cet_r", F0."bst_r" AS "bst_r", F0."pos_r" AS "pos_r"
FROM (SELECT * FROM _temp_view_22) F0),
_temp_view_20 AS (
SELECT /*+ materialize */ F0."c_custkey" AS "c_custkey", F0."ub_c_custkey" AS "ub_c_custkey", F0."lb_c_custkey" AS "lb_c_custkey", 0 AS "cet_r", 0 AS "bst_r", F0."bst_r" AS "pos_r"
FROM (SELECT * FROM _temp_view_21) F0),
_temp_view_27 AS (
SELECT /*+ materialize */ F0."tid" AS "tid", F0."o_orderkey" AS "o_orderkey", F0."o_custkey" AS "o_custkey", F0."o_orderstatus" AS "o_orderstatus", F0."o_totalprice" AS "o_totalprice", F0."o_orderdate" AS "o_orderdate", F0."o_orderpriority" AS "o_orderpriority", F0."o_clerk" AS "o_clerk", F0."o_shippriority" AS "o_shippriority", F0."o_comment" AS "o_comment", F0."ub_tid" AS "ub_tid", F0."lb_tid" AS "lb_tid", F0."ub_o_orderkey" AS "ub_o_orderkey", F0."lb_o_orderkey" AS "lb_o_orderkey", F0."ub_o_custkey" AS "ub_o_custkey", F0."lb_o_custkey" AS "lb_o_custkey", F0."ub_o_orderstatus" AS "ub_o_orderstatus", F0."lb_o_orderstatus" AS "lb_o_orderstatus", F0."ub_o_totalprice" AS "ub_o_totalprice", F0."lb_o_totalprice" AS "lb_o_totalprice", F0."ub_o_orderdate" AS "ub_o_orderdate", F0."lb_o_orderdate" AS "lb_o_orderdate", F0."ub_o_orderpriority" AS "ub_o_orderpriority", F0."lb_o_orderpriority" AS "lb_o_orderpriority", F0."ub_o_clerk" AS "ub_o_clerk", F0."lb_o_clerk" AS "lb_o_clerk", F0."ub_o_shippriority" AS "ub_o_shippriority", F0."lb_o_shippriority" AS "lb_o_shippriority", F0."ub_o_comment" AS "ub_o_comment", F0."lb_o_comment" AS "lb_o_comment", F0."cet_r" AS "cet_r", F0."bst_r" AS "bst_r", F0."pos_r" AS "pos_r"
FROM "orders_radb" AS F0),
_temp_view_26 AS (
SELECT /*+ materialize */ F0."tid" AS "tid", F0."o_orderkey" AS "o_orderkey", F0."o_custkey" AS "o_custkey", F0."o_orderstatus" AS "o_orderstatus", F0."o_totalprice" AS "o_totalprice", F0."o_orderdate" AS "o_orderdate", F0."o_orderpriority" AS "o_orderpriority", F0."o_clerk" AS "o_clerk", F0."o_shippriority" AS "o_shippriority", F0."o_comment" AS "o_comment", F0."ub_tid" AS "ub_tid", F0."lb_tid" AS "lb_tid", F0."ub_o_orderkey" AS "ub_o_orderkey", F0."lb_o_orderkey" AS "lb_o_orderkey", F0."ub_o_custkey" AS "ub_o_custkey", F0."lb_o_custkey" AS "lb_o_custkey", F0."ub_o_orderstatus" AS "ub_o_orderstatus", F0."lb_o_orderstatus" AS "lb_o_orderstatus", F0."ub_o_totalprice" AS "ub_o_totalprice", F0."lb_o_totalprice" AS "lb_o_totalprice", F0."ub_o_orderdate" AS "ub_o_orderdate", F0."lb_o_orderdate" AS "lb_o_orderdate", F0."ub_o_orderpriority" AS "ub_o_orderpriority", F0."lb_o_orderpriority" AS "lb_o_orderpriority", F0."ub_o_clerk" AS "ub_o_clerk", F0."lb_o_clerk" AS "lb_o_clerk", F0."ub_o_shippriority" AS "ub_o_shippriority", F0."lb_o_shippriority" AS "lb_o_shippriority", F0."ub_o_comment" AS "ub_o_comment", F0."lb_o_comment" AS "lb_o_comment", (CASE  WHEN (F0."lb_o_orderdate" > '1995-03-15') THEN 1 ELSE 0 END) AS "cet_r", (CASE  WHEN (F0."o_orderdate" > '1995-03-15') THEN 1 ELSE 0 END) AS "bst_r", F0."pos_r" AS "pos_r"
FROM (
SELECT F0."tid" AS "tid", F0."o_orderkey" AS "o_orderkey", F0."o_custkey" AS "o_custkey", F0."o_orderstatus" AS "o_orderstatus", F0."o_totalprice" AS "o_totalprice", F0."o_orderdate" AS "o_orderdate", F0."o_orderpriority" AS "o_orderpriority", F0."o_clerk" AS "o_clerk", F0."o_shippriority" AS "o_shippriority", F0."o_comment" AS "o_comment", F0."ub_tid" AS "ub_tid", F0."lb_tid" AS "lb_tid", F0."ub_o_orderkey" AS "ub_o_orderkey", F0."lb_o_orderkey" AS "lb_o_orderkey", F0."ub_o_custkey" AS "ub_o_custkey", F0."lb_o_custkey" AS "lb_o_custkey", F0."ub_o_orderstatus" AS "ub_o_orderstatus", F0."lb_o_orderstatus" AS "lb_o_orderstatus", F0."ub_o_totalprice" AS "ub_o_totalprice", F0."lb_o_totalprice" AS "lb_o_totalprice", F0."ub_o_orderdate" AS "ub_o_orderdate", F0."lb_o_orderdate" AS "lb_o_orderdate", F0."ub_o_orderpriority" AS "ub_o_orderpriority", F0."lb_o_orderpriority" AS "lb_o_orderpriority", F0."ub_o_clerk" AS "ub_o_clerk", F0."lb_o_clerk" AS "lb_o_clerk", F0."ub_o_shippriority" AS "ub_o_shippriority", F0."lb_o_shippriority" AS "lb_o_shippriority", F0."ub_o_comment" AS "ub_o_comment", F0."lb_o_comment" AS "lb_o_comment", F0."cet_r" AS "cet_r", F0."bst_r" AS "bst_r", F0."pos_r" AS "pos_r"
FROM (SELECT * FROM _temp_view_27) F0) F0
WHERE (F0."ub_o_orderdate" > '1995-03-15')),
_temp_view_25 AS (
SELECT /*+ materialize */ F0."o_custkey" AS "o_custkey", F0."o_orderkey" AS "o_orderkey", F0."o_orderdate" AS "o_orderdate", F0."o_shippriority" AS "o_shippriority", F0."ub_o_custkey" AS "ub_o_custkey", F0."lb_o_custkey" AS "lb_o_custkey", F0."ub_o_orderkey" AS "ub_o_orderkey", F0."lb_o_orderkey" AS "lb_o_orderkey", F0."ub_o_orderdate" AS "ub_o_orderdate", F0."lb_o_orderdate" AS "lb_o_orderdate", F0."ub_o_shippriority" AS "ub_o_shippriority", F0."lb_o_shippriority" AS "lb_o_shippriority", F0."cet_r" AS "cet_r", F0."bst_r" AS "bst_r", F0."pos_r" AS "pos_r"
FROM (SELECT * FROM _temp_view_26) F0),
_temp_view_24 AS (
SELECT /*+ materialize */ F0."o_custkey" AS "o_custkey", F0."o_orderkey" AS "o_orderkey", F0."o_orderdate" AS "o_orderdate", F0."o_shippriority" AS "o_shippriority", F0."ub_o_custkey" AS "ub_o_custkey", F0."lb_o_custkey" AS "lb_o_custkey", F0."ub_o_orderkey" AS "ub_o_orderkey", F0."lb_o_orderkey" AS "lb_o_orderkey", F0."ub_o_orderdate" AS "ub_o_orderdate", F0."lb_o_orderdate" AS "lb_o_orderdate", F0."ub_o_shippriority" AS "ub_o_shippriority", F0."lb_o_shippriority" AS "lb_o_shippriority", 0 AS "cet_r", 0 AS "bst_r", F0."bst_r" AS "pos_r"
FROM (SELECT * FROM _temp_view_25) F0),
_temp_view_15 AS (
SELECT /*+ materialize */ F0."c_custkey" AS "c_custkey", F0."o_custkey" AS "o_custkey", F0."o_orderkey" AS "o_orderkey", F0."o_orderdate" AS "o_orderdate", F0."o_shippriority" AS "o_shippriority", F0."ub_c_custkey" AS "ub_c_custkey", F0."lb_c_custkey" AS "lb_c_custkey", F0."ub_o_custkey" AS "ub_o_custkey", F0."lb_o_custkey" AS "lb_o_custkey", F0."ub_o_orderkey" AS "ub_o_orderkey", F0."lb_o_orderkey" AS "lb_o_orderkey", F0."ub_o_orderdate" AS "ub_o_orderdate", F0."lb_o_orderdate" AS "lb_o_orderdate", F0."ub_o_shippriority" AS "ub_o_shippriority", F0."lb_o_shippriority" AS "lb_o_shippriority", F0."cet_r" AS "cet_r", F0."bst_r" AS "bst_r", F0."pos_r" AS "pos_r"
FROM (
SELECT F0."c_custkey" AS "c_custkey", F1."o_custkey" AS "o_custkey", F1."o_orderkey" AS "o_orderkey", F1."o_orderdate" AS "o_orderdate", F1."o_shippriority" AS "o_shippriority", F0."ub_c_custkey" AS "ub_c_custkey", F0."lb_c_custkey" AS "lb_c_custkey", F1."ub_o_custkey" AS "ub_o_custkey", F1."lb_o_custkey" AS "lb_o_custkey", F1."ub_o_orderkey" AS "ub_o_orderkey", F1."lb_o_orderkey" AS "lb_o_orderkey", F1."ub_o_orderdate" AS "ub_o_orderdate", F1."lb_o_orderdate" AS "lb_o_orderdate", F1."ub_o_shippriority" AS "ub_o_shippriority", F1."lb_o_shippriority" AS "lb_o_shippriority", (F0."cet_r" * F1."cet_r") AS "cet_r", (F0."bst_r" * F1."bst_r") AS "bst_r", (F0."pos_r" * F1."pos_r") AS "pos_r"
FROM ((
SELECT F0."c_custkey" AS "c_custkey", F0."c_custkey" AS "ub_c_custkey", F0."c_custkey" AS "lb_c_custkey", (CASE  WHEN (F0."ub_c_custkey" = F0."lb_c_custkey") THEN F0."cet_r" ELSE 0 END) AS "cet_r", F0."bst_r" AS "bst_r", F0."bst_r" AS "pos_r"
FROM (
SELECT F0."c_custkey" AS "c_custkey", F0."ub_c_custkey" AS "ub_c_custkey", F0."lb_c_custkey" AS "lb_c_custkey", F0."cet_r" AS "cet_r", F0."bst_r" AS "bst_r", F0."pos_r" AS "pos_r"
FROM (SELECT * FROM _temp_view_16) F0) F0
WHERE (F0."bst_r" > 0)) F0 JOIN (
SELECT F0."o_custkey" AS "o_custkey", F0."o_orderkey" AS "o_orderkey", F0."o_orderdate" AS "o_orderdate", F0."o_shippriority" AS "o_shippriority", F0."o_custkey" AS "ub_o_custkey", F0."o_custkey" AS "lb_o_custkey", F0."o_orderkey" AS "ub_o_orderkey", F0."o_orderkey" AS "lb_o_orderkey", F0."o_orderdate" AS "ub_o_orderdate", F0."o_orderdate" AS "lb_o_orderdate", F0."o_shippriority" AS "ub_o_shippriority", F0."o_shippriority" AS "lb_o_shippriority", (CASE  WHEN ((((F0."ub_o_custkey" = F0."lb_o_custkey") AND (F0."ub_o_orderkey" = F0."lb_o_orderkey")) AND (F0."ub_o_orderdate" = F0."lb_o_orderdate")) AND (F0."ub_o_shippriority" = F0."lb_o_shippriority")) THEN F0."cet_r" ELSE 0 END) AS "cet_r", F0."bst_r" AS "bst_r", F0."bst_r" AS "pos_r"
FROM (
SELECT F0."o_custkey" AS "o_custkey", F0."o_orderkey" AS "o_orderkey", F0."o_orderdate" AS "o_orderdate", F0."o_shippriority" AS "o_shippriority", F0."ub_o_custkey" AS "ub_o_custkey", F0."lb_o_custkey" AS "lb_o_custkey", F0."ub_o_orderkey" AS "ub_o_orderkey", F0."lb_o_orderkey" AS "lb_o_orderkey", F0."ub_o_orderdate" AS "ub_o_orderdate", F0."lb_o_orderdate" AS "lb_o_orderdate", F0."ub_o_shippriority" AS "ub_o_shippriority", F0."lb_o_shippriority" AS "lb_o_shippriority", F0."cet_r" AS "cet_r", F0."bst_r" AS "bst_r", F0."pos_r" AS "pos_r"
FROM (SELECT * FROM _temp_view_18) F0) F0
WHERE (F0."bst_r" > 0)) F1 ON ((F0."c_custkey" = F1."o_custkey"))) UNION ALL 
SELECT F0."c_custkey" AS "c_custkey", F1."o_custkey" AS "o_custkey", F1."o_orderkey" AS "o_orderkey", F1."o_orderdate" AS "o_orderdate", F1."o_shippriority" AS "o_shippriority", F0."ub_c_custkey" AS "ub_c_custkey", F0."lb_c_custkey" AS "lb_c_custkey", F1."ub_o_custkey" AS "ub_o_custkey", F1."lb_o_custkey" AS "lb_o_custkey", F1."ub_o_orderkey" AS "ub_o_orderkey", F1."lb_o_orderkey" AS "lb_o_orderkey", F1."ub_o_orderdate" AS "ub_o_orderdate", F1."lb_o_orderdate" AS "lb_o_orderdate", F1."ub_o_shippriority" AS "ub_o_shippriority", F1."lb_o_shippriority" AS "lb_o_shippriority", ((F0."cet_r" * F1."cet_r") * (CASE  WHEN ((F0."c_custkey" = F1."o_custkey") AND ((F0."ub_c_custkey" = F0."lb_c_custkey") AND (F1."ub_o_custkey" = F1."lb_o_custkey"))) THEN 1 ELSE 0 END)) AS "cet_r", ((F0."bst_r" * F1."bst_r") * (CASE  WHEN (F0."c_custkey" = F1."o_custkey") THEN 1 ELSE 0 END)) AS "bst_r", (F0."pos_r" * F1."pos_r") AS "pos_r"
FROM ((
SELECT (CASE  WHEN (F0."c_custkey" >= 7500) THEN 7500 WHEN ((F0."c_custkey" < 7500) AND (F0."c_custkey" >= 1)) THEN 1 ELSE 1 END) AS "c_custkey", max(F0."ub_c_custkey") AS "ub_c_custkey", min(F0."lb_c_custkey") AS "lb_c_custkey", sum(F0."cet_r") AS "cet_r", sum(F0."bst_r") AS "bst_r", sum(F0."pos_r") AS "pos_r"
FROM (SELECT * FROM _temp_view_20) F0
GROUP BY (CASE  WHEN (F0."c_custkey" >= 7500) THEN 7500 WHEN ((F0."c_custkey" < 7500) AND (F0."c_custkey" >= 1)) THEN 1 ELSE 1 END)) F0 JOIN (
SELECT (CASE  WHEN (F0."o_custkey" >= 7500) THEN 7500 WHEN ((F0."o_custkey" < 7500) AND (F0."o_custkey" >= 1)) THEN 1 ELSE 1 END) AS "o_custkey", min(F0."o_orderkey") AS "o_orderkey", min(F0."o_orderdate") AS "o_orderdate", min(F0."o_shippriority") AS "o_shippriority", max(F0."ub_o_custkey") AS "ub_o_custkey", min(F0."lb_o_custkey") AS "lb_o_custkey", max(F0."ub_o_orderkey") AS "ub_o_orderkey", min(F0."lb_o_orderkey") AS "lb_o_orderkey", max(F0."ub_o_orderdate") AS "ub_o_orderdate", min(F0."lb_o_orderdate") AS "lb_o_orderdate", max(F0."ub_o_shippriority") AS "ub_o_shippriority", min(F0."lb_o_shippriority") AS "lb_o_shippriority", sum(F0."cet_r") AS "cet_r", sum(F0."bst_r") AS "bst_r", sum(F0."pos_r") AS "pos_r"
FROM (SELECT * FROM _temp_view_24) F0
GROUP BY (CASE  WHEN (F0."o_custkey" >= 7500) THEN 7500 WHEN ((F0."o_custkey" < 7500) AND (F0."o_custkey" >= 1)) THEN 1 ELSE 1 END)) F1 ON (((F0."lb_c_custkey" <= F1."ub_o_custkey") AND (F0."ub_c_custkey" >= F1."lb_o_custkey"))))) F0),
_temp_view_14 AS (
SELECT /*+ materialize */ F0."c_custkey" AS "c_custkey", F0."o_custkey" AS "o_custkey", F0."o_orderkey" AS "o_orderkey", F0."o_orderdate" AS "o_orderdate", F0."o_shippriority" AS "o_shippriority", F0."ub_c_custkey" AS "ub_c_custkey", F0."lb_c_custkey" AS "lb_c_custkey", F0."ub_o_custkey" AS "ub_o_custkey", F0."lb_o_custkey" AS "lb_o_custkey", F0."ub_o_orderkey" AS "ub_o_orderkey", F0."lb_o_orderkey" AS "lb_o_orderkey", F0."ub_o_orderdate" AS "ub_o_orderdate", F0."lb_o_orderdate" AS "lb_o_orderdate", F0."ub_o_shippriority" AS "ub_o_shippriority", F0."lb_o_shippriority" AS "lb_o_shippriority", 0 AS "cet_r", 0 AS "bst_r", F0."bst_r" AS "pos_r"
FROM (SELECT * FROM _temp_view_15) F0),
_temp_view_31 AS (
SELECT /*+ materialize */ F0."tid" AS "tid", F0."l_orderkey" AS "l_orderkey", F0."l_partkey" AS "l_partkey", F0."l_suppkey" AS "l_suppkey", F0."l_linenumber" AS "l_linenumber", F0."l_quantity" AS "l_quantity", F0."l_extendedprice" AS "l_extendedprice", F0."l_discount" AS "l_discount", F0."l_tax" AS "l_tax", F0."l_returnflag" AS "l_returnflag", F0."l_linestatus" AS "l_linestatus", F0."l_shipdate" AS "l_shipdate", F0."l_commitdate" AS "l_commitdate", F0."l_receiptdate" AS "l_receiptdate", F0."l_shipinstruct" AS "l_shipinstruct", F0."l_shipmode" AS "l_shipmode", F0."l_comment" AS "l_comment", F0."ub_tid" AS "ub_tid", F0."lb_tid" AS "lb_tid", F0."ub_l_orderkey" AS "ub_l_orderkey", F0."lb_l_orderkey" AS "lb_l_orderkey", F0."ub_l_partkey" AS "ub_l_partkey", F0."lb_l_partkey" AS "lb_l_partkey", F0."ub_l_suppkey" AS "ub_l_suppkey", F0."lb_l_suppkey" AS "lb_l_suppkey", F0."ub_l_linenumber" AS "ub_l_linenumber", F0."lb_l_linenumber" AS "lb_l_linenumber", F0."ub_l_quantity" AS "ub_l_quantity", F0."lb_l_quantity" AS "lb_l_quantity", F0."ub_l_extendedprice" AS "ub_l_extendedprice", F0."lb_l_extendedprice" AS "lb_l_extendedprice", F0."ub_l_discount" AS "ub_l_discount", F0."lb_l_discount" AS "lb_l_discount", F0."ub_l_tax" AS "ub_l_tax", F0."lb_l_tax" AS "lb_l_tax", F0."ub_l_returnflag" AS "ub_l_returnflag", F0."lb_l_returnflag" AS "lb_l_returnflag", F0."ub_l_linestatus" AS "ub_l_linestatus", F0."lb_l_linestatus" AS "lb_l_linestatus", F0."ub_l_shipdate" AS "ub_l_shipdate", F0."lb_l_shipdate" AS "lb_l_shipdate", F0."ub_l_commitdate" AS "ub_l_commitdate", F0."lb_l_commitdate" AS "lb_l_commitdate", F0."ub_l_receiptdate" AS "ub_l_receiptdate", F0."lb_l_receiptdate" AS "lb_l_receiptdate", F0."ub_l_shipinstruct" AS "ub_l_shipinstruct", F0."lb_l_shipinstruct" AS "lb_l_shipinstruct", F0."ub_l_shipmode" AS "ub_l_shipmode", F0."lb_l_shipmode" AS "lb_l_shipmode", F0."ub_l_comment" AS "ub_l_comment", F0."lb_l_comment" AS "lb_l_comment", F0."cet_r" AS "cet_r", F0."bst_r" AS "bst_r", F0."pos_r" AS "pos_r"
FROM "lineitem_radb" AS F0),
_temp_view_30 AS (
SELECT /*+ materialize */ F0."tid" AS "tid", F0."l_orderkey" AS "l_orderkey", F0."l_partkey" AS "l_partkey", F0."l_suppkey" AS "l_suppkey", F0."l_linenumber" AS "l_linenumber", F0."l_quantity" AS "l_quantity", F0."l_extendedprice" AS "l_extendedprice", F0."l_discount" AS "l_discount", F0."l_tax" AS "l_tax", F0."l_returnflag" AS "l_returnflag", F0."l_linestatus" AS "l_linestatus", F0."l_shipdate" AS "l_shipdate", F0."l_commitdate" AS "l_commitdate", F0."l_receiptdate" AS "l_receiptdate", F0."l_shipinstruct" AS "l_shipinstruct", F0."l_shipmode" AS "l_shipmode", F0."l_comment" AS "l_comment", F0."ub_tid" AS "ub_tid", F0."lb_tid" AS "lb_tid", F0."ub_l_orderkey" AS "ub_l_orderkey", F0."lb_l_orderkey" AS "lb_l_orderkey", F0."ub_l_partkey" AS "ub_l_partkey", F0."lb_l_partkey" AS "lb_l_partkey", F0."ub_l_suppkey" AS "ub_l_suppkey", F0."lb_l_suppkey" AS "lb_l_suppkey", F0."ub_l_linenumber" AS "ub_l_linenumber", F0."lb_l_linenumber" AS "lb_l_linenumber", F0."ub_l_quantity" AS "ub_l_quantity", F0."lb_l_quantity" AS "lb_l_quantity", F0."ub_l_extendedprice" AS "ub_l_extendedprice", F0."lb_l_extendedprice" AS "lb_l_extendedprice", F0."ub_l_discount" AS "ub_l_discount", F0."lb_l_discount" AS "lb_l_discount", F0."ub_l_tax" AS "ub_l_tax", F0."lb_l_tax" AS "lb_l_tax", F0."ub_l_returnflag" AS "ub_l_returnflag", F0."lb_l_returnflag" AS "lb_l_returnflag", F0."ub_l_linestatus" AS "ub_l_linestatus", F0."lb_l_linestatus" AS "lb_l_linestatus", F0."ub_l_shipdate" AS "ub_l_shipdate", F0."lb_l_shipdate" AS "lb_l_shipdate", F0."ub_l_commitdate" AS "ub_l_commitdate", F0."lb_l_commitdate" AS "lb_l_commitdate", F0."ub_l_receiptdate" AS "ub_l_receiptdate", F0."lb_l_receiptdate" AS "lb_l_receiptdate", F0."ub_l_shipinstruct" AS "ub_l_shipinstruct", F0."lb_l_shipinstruct" AS "lb_l_shipinstruct", F0."ub_l_shipmode" AS "ub_l_shipmode", F0."lb_l_shipmode" AS "lb_l_shipmode", F0."ub_l_comment" AS "ub_l_comment", F0."lb_l_comment" AS "lb_l_comment", (CASE  WHEN (F0."ub_l_shipdate" < '1995-03-17') THEN 1 ELSE 0 END) AS "cet_r", (CASE  WHEN (F0."l_shipdate" < '1995-03-17') THEN 1 ELSE 0 END) AS "bst_r", F0."pos_r" AS "pos_r"
FROM (
SELECT F0."tid" AS "tid", F0."l_orderkey" AS "l_orderkey", F0."l_partkey" AS "l_partkey", F0."l_suppkey" AS "l_suppkey", F0."l_linenumber" AS "l_linenumber", F0."l_quantity" AS "l_quantity", F0."l_extendedprice" AS "l_extendedprice", F0."l_discount" AS "l_discount", F0."l_tax" AS "l_tax", F0."l_returnflag" AS "l_returnflag", F0."l_linestatus" AS "l_linestatus", F0."l_shipdate" AS "l_shipdate", F0."l_commitdate" AS "l_commitdate", F0."l_receiptdate" AS "l_receiptdate", F0."l_shipinstruct" AS "l_shipinstruct", F0."l_shipmode" AS "l_shipmode", F0."l_comment" AS "l_comment", F0."ub_tid" AS "ub_tid", F0."lb_tid" AS "lb_tid", F0."ub_l_orderkey" AS "ub_l_orderkey", F0."lb_l_orderkey" AS "lb_l_orderkey", F0."ub_l_partkey" AS "ub_l_partkey", F0."lb_l_partkey" AS "lb_l_partkey", F0."ub_l_suppkey" AS "ub_l_suppkey", F0."lb_l_suppkey" AS "lb_l_suppkey", F0."ub_l_linenumber" AS "ub_l_linenumber", F0."lb_l_linenumber" AS "lb_l_linenumber", F0."ub_l_quantity" AS "ub_l_quantity", F0."lb_l_quantity" AS "lb_l_quantity", F0."ub_l_extendedprice" AS "ub_l_extendedprice", F0."lb_l_extendedprice" AS "lb_l_extendedprice", F0."ub_l_discount" AS "ub_l_discount", F0."lb_l_discount" AS "lb_l_discount", F0."ub_l_tax" AS "ub_l_tax", F0."lb_l_tax" AS "lb_l_tax", F0."ub_l_returnflag" AS "ub_l_returnflag", F0."lb_l_returnflag" AS "lb_l_returnflag", F0."ub_l_linestatus" AS "ub_l_linestatus", F0."lb_l_linestatus" AS "lb_l_linestatus", F0."ub_l_shipdate" AS "ub_l_shipdate", F0."lb_l_shipdate" AS "lb_l_shipdate", F0."ub_l_commitdate" AS "ub_l_commitdate", F0."lb_l_commitdate" AS "lb_l_commitdate", F0."ub_l_receiptdate" AS "ub_l_receiptdate", F0."lb_l_receiptdate" AS "lb_l_receiptdate", F0."ub_l_shipinstruct" AS "ub_l_shipinstruct", F0."lb_l_shipinstruct" AS "lb_l_shipinstruct", F0."ub_l_shipmode" AS "ub_l_shipmode", F0."lb_l_shipmode" AS "lb_l_shipmode", F0."ub_l_comment" AS "ub_l_comment", F0."lb_l_comment" AS "lb_l_comment", F0."cet_r" AS "cet_r", F0."bst_r" AS "bst_r", F0."pos_r" AS "pos_r"
FROM (SELECT * FROM _temp_view_31) F0) F0
WHERE (F0."lb_l_shipdate" < '1995-03-17')),
_temp_view_29 AS (
SELECT /*+ materialize */ F0."l_orderkey" AS "l_orderkey", F0."ub_l_orderkey" AS "ub_l_orderkey", F0."lb_l_orderkey" AS "lb_l_orderkey", F0."cet_r" AS "cet_r", F0."bst_r" AS "bst_r", F0."pos_r" AS "pos_r"
FROM (SELECT * FROM _temp_view_30) F0),
_temp_view_28 AS (
SELECT /*+ materialize */ F0."l_orderkey" AS "l_orderkey", F0."ub_l_orderkey" AS "ub_l_orderkey", F0."lb_l_orderkey" AS "lb_l_orderkey", 0 AS "cet_r", 0 AS "bst_r", F0."bst_r" AS "pos_r"
FROM (SELECT * FROM _temp_view_29) F0)
SELECT F0."o_orderkey" AS "o_orderkey", F0."o_orderdate" AS "o_orderdate", F0."o_shippriority" AS "o_shippriority", F0."ub_o_orderkey" AS "ub_o_orderkey", F0."lb_o_orderkey" AS "lb_o_orderkey", F0."ub_o_orderdate" AS "ub_o_orderdate", F0."lb_o_orderdate" AS "lb_o_orderdate", F0."ub_o_shippriority" AS "ub_o_shippriority", F0."lb_o_shippriority" AS "lb_o_shippriority", F0."cet_r" AS "cet_r", F0."bst_r" AS "bst_r", F0."pos_r" AS "pos_r"
FROM (
SELECT F0."c_custkey" AS "c_custkey", F0."o_custkey" AS "o_custkey", F0."o_orderkey" AS "o_orderkey", F0."o_orderdate" AS "o_orderdate", F0."o_shippriority" AS "o_shippriority", F1."l_orderkey" AS "l_orderkey", F0."ub_c_custkey" AS "ub_c_custkey", F0."lb_c_custkey" AS "lb_c_custkey", F0."ub_o_custkey" AS "ub_o_custkey", F0."lb_o_custkey" AS "lb_o_custkey", F0."ub_o_orderkey" AS "ub_o_orderkey", F0."lb_o_orderkey" AS "lb_o_orderkey", F0."ub_o_orderdate" AS "ub_o_orderdate", F0."lb_o_orderdate" AS "lb_o_orderdate", F0."ub_o_shippriority" AS "ub_o_shippriority", F0."lb_o_shippriority" AS "lb_o_shippriority", F1."ub_l_orderkey" AS "ub_l_orderkey", F1."lb_l_orderkey" AS "lb_l_orderkey", (F0."cet_r" * F1."cet_r") AS "cet_r", (F0."bst_r" * F1."bst_r") AS "bst_r", (F0."pos_r" * F1."pos_r") AS "pos_r"
FROM ((
SELECT F0."c_custkey" AS "c_custkey", F0."o_custkey" AS "o_custkey", F0."o_orderkey" AS "o_orderkey", F0."o_orderdate" AS "o_orderdate", F0."o_shippriority" AS "o_shippriority", F0."c_custkey" AS "ub_c_custkey", F0."c_custkey" AS "lb_c_custkey", F0."o_custkey" AS "ub_o_custkey", F0."o_custkey" AS "lb_o_custkey", F0."o_orderkey" AS "ub_o_orderkey", F0."o_orderkey" AS "lb_o_orderkey", F0."o_orderdate" AS "ub_o_orderdate", F0."o_orderdate" AS "lb_o_orderdate", F0."o_shippriority" AS "ub_o_shippriority", F0."o_shippriority" AS "lb_o_shippriority", (CASE  WHEN (((((F0."ub_c_custkey" = F0."lb_c_custkey") AND (F0."ub_o_custkey" = F0."lb_o_custkey")) AND (F0."ub_o_orderkey" = F0."lb_o_orderkey")) AND (F0."ub_o_orderdate" = F0."lb_o_orderdate")) AND (F0."ub_o_shippriority" = F0."lb_o_shippriority")) THEN F0."cet_r" ELSE 0 END) AS "cet_r", F0."bst_r" AS "bst_r", F0."bst_r" AS "pos_r"
FROM (
SELECT F0."c_custkey" AS "c_custkey", F0."o_custkey" AS "o_custkey", F0."o_orderkey" AS "o_orderkey", F0."o_orderdate" AS "o_orderdate", F0."o_shippriority" AS "o_shippriority", F0."ub_c_custkey" AS "ub_c_custkey", F0."lb_c_custkey" AS "lb_c_custkey", F0."ub_o_custkey" AS "ub_o_custkey", F0."lb_o_custkey" AS "lb_o_custkey", F0."ub_o_orderkey" AS "ub_o_orderkey", F0."lb_o_orderkey" AS "lb_o_orderkey", F0."ub_o_orderdate" AS "ub_o_orderdate", F0."lb_o_orderdate" AS "lb_o_orderdate", F0."ub_o_shippriority" AS "ub_o_shippriority", F0."lb_o_shippriority" AS "lb_o_shippriority", F0."cet_r" AS "cet_r", F0."bst_r" AS "bst_r", F0."pos_r" AS "pos_r"
FROM (
SELECT F0."c_custkey" AS "c_custkey", F1."o_custkey" AS "o_custkey", F1."o_orderkey" AS "o_orderkey", F1."o_orderdate" AS "o_orderdate", F1."o_shippriority" AS "o_shippriority", F0."ub_c_custkey" AS "ub_c_custkey", F0."lb_c_custkey" AS "lb_c_custkey", F1."ub_o_custkey" AS "ub_o_custkey", F1."lb_o_custkey" AS "lb_o_custkey", F1."ub_o_orderkey" AS "ub_o_orderkey", F1."lb_o_orderkey" AS "lb_o_orderkey", F1."ub_o_orderdate" AS "ub_o_orderdate", F1."lb_o_orderdate" AS "lb_o_orderdate", F1."ub_o_shippriority" AS "ub_o_shippriority", F1."lb_o_shippriority" AS "lb_o_shippriority", (F0."cet_r" * F1."cet_r") AS "cet_r", (F0."bst_r" * F1."bst_r") AS "bst_r", (F0."pos_r" * F1."pos_r") AS "pos_r"
FROM ((
SELECT F0."c_custkey" AS "c_custkey", F0."c_custkey" AS "ub_c_custkey", F0."c_custkey" AS "lb_c_custkey", (CASE  WHEN (F0."ub_c_custkey" = F0."lb_c_custkey") THEN F0."cet_r" ELSE 0 END) AS "cet_r", F0."bst_r" AS "bst_r", F0."bst_r" AS "pos_r"
FROM (
SELECT F0."c_custkey" AS "c_custkey", F0."ub_c_custkey" AS "ub_c_custkey", F0."lb_c_custkey" AS "lb_c_custkey", F0."cet_r" AS "cet_r", F0."bst_r" AS "bst_r", F0."pos_r" AS "pos_r"
FROM (SELECT * FROM _temp_view_0) F0) F0
WHERE (F0."bst_r" > 0)) F0 JOIN (
SELECT F0."o_custkey" AS "o_custkey", F0."o_orderkey" AS "o_orderkey", F0."o_orderdate" AS "o_orderdate", F0."o_shippriority" AS "o_shippriority", F0."o_custkey" AS "ub_o_custkey", F0."o_custkey" AS "lb_o_custkey", F0."o_orderkey" AS "ub_o_orderkey", F0."o_orderkey" AS "lb_o_orderkey", F0."o_orderdate" AS "ub_o_orderdate", F0."o_orderdate" AS "lb_o_orderdate", F0."o_shippriority" AS "ub_o_shippriority", F0."o_shippriority" AS "lb_o_shippriority", (CASE  WHEN ((((F0."ub_o_custkey" = F0."lb_o_custkey") AND (F0."ub_o_orderkey" = F0."lb_o_orderkey")) AND (F0."ub_o_orderdate" = F0."lb_o_orderdate")) AND (F0."ub_o_shippriority" = F0."lb_o_shippriority")) THEN F0."cet_r" ELSE 0 END) AS "cet_r", F0."bst_r" AS "bst_r", F0."bst_r" AS "pos_r"
FROM (
SELECT F0."o_custkey" AS "o_custkey", F0."o_orderkey" AS "o_orderkey", F0."o_orderdate" AS "o_orderdate", F0."o_shippriority" AS "o_shippriority", F0."ub_o_custkey" AS "ub_o_custkey", F0."lb_o_custkey" AS "lb_o_custkey", F0."ub_o_orderkey" AS "ub_o_orderkey", F0."lb_o_orderkey" AS "lb_o_orderkey", F0."ub_o_orderdate" AS "ub_o_orderdate", F0."lb_o_orderdate" AS "lb_o_orderdate", F0."ub_o_shippriority" AS "ub_o_shippriority", F0."lb_o_shippriority" AS "lb_o_shippriority", F0."cet_r" AS "cet_r", F0."bst_r" AS "bst_r", F0."pos_r" AS "pos_r"
FROM (SELECT * FROM _temp_view_2) F0) F0
WHERE (F0."bst_r" > 0)) F1 ON ((F0."c_custkey" = F1."o_custkey"))) UNION ALL 
SELECT F0."c_custkey" AS "c_custkey", F1."o_custkey" AS "o_custkey", F1."o_orderkey" AS "o_orderkey", F1."o_orderdate" AS "o_orderdate", F1."o_shippriority" AS "o_shippriority", F0."ub_c_custkey" AS "ub_c_custkey", F0."lb_c_custkey" AS "lb_c_custkey", F1."ub_o_custkey" AS "ub_o_custkey", F1."lb_o_custkey" AS "lb_o_custkey", F1."ub_o_orderkey" AS "ub_o_orderkey", F1."lb_o_orderkey" AS "lb_o_orderkey", F1."ub_o_orderdate" AS "ub_o_orderdate", F1."lb_o_orderdate" AS "lb_o_orderdate", F1."ub_o_shippriority" AS "ub_o_shippriority", F1."lb_o_shippriority" AS "lb_o_shippriority", ((F0."cet_r" * F1."cet_r") * (CASE  WHEN ((F0."c_custkey" = F1."o_custkey") AND ((F0."ub_c_custkey" = F0."lb_c_custkey") AND (F1."ub_o_custkey" = F1."lb_o_custkey"))) THEN 1 ELSE 0 END)) AS "cet_r", ((F0."bst_r" * F1."bst_r") * (CASE  WHEN (F0."c_custkey" = F1."o_custkey") THEN 1 ELSE 0 END)) AS "bst_r", (F0."pos_r" * F1."pos_r") AS "pos_r"
FROM ((
SELECT (CASE  WHEN (F0."c_custkey" >= 7500) THEN 7500 WHEN ((F0."c_custkey" < 7500) AND (F0."c_custkey" >= 1)) THEN 1 ELSE 1 END) AS "c_custkey", max(F0."ub_c_custkey") AS "ub_c_custkey", min(F0."lb_c_custkey") AS "lb_c_custkey", sum(F0."cet_r") AS "cet_r", sum(F0."bst_r") AS "bst_r", sum(F0."pos_r") AS "pos_r"
FROM (SELECT * FROM _temp_view_4) F0
GROUP BY (CASE  WHEN (F0."c_custkey" >= 7500) THEN 7500 WHEN ((F0."c_custkey" < 7500) AND (F0."c_custkey" >= 1)) THEN 1 ELSE 1 END)) F0 JOIN (
SELECT (CASE  WHEN (F0."o_custkey" >= 7500) THEN 7500 WHEN ((F0."o_custkey" < 7500) AND (F0."o_custkey" >= 1)) THEN 1 ELSE 1 END) AS "o_custkey", min(F0."o_orderkey") AS "o_orderkey", min(F0."o_orderdate") AS "o_orderdate", min(F0."o_shippriority") AS "o_shippriority", max(F0."ub_o_custkey") AS "ub_o_custkey", min(F0."lb_o_custkey") AS "lb_o_custkey", max(F0."ub_o_orderkey") AS "ub_o_orderkey", min(F0."lb_o_orderkey") AS "lb_o_orderkey", max(F0."ub_o_orderdate") AS "ub_o_orderdate", min(F0."lb_o_orderdate") AS "lb_o_orderdate", max(F0."ub_o_shippriority") AS "ub_o_shippriority", min(F0."lb_o_shippriority") AS "lb_o_shippriority", sum(F0."cet_r") AS "cet_r", sum(F0."bst_r") AS "bst_r", sum(F0."pos_r") AS "pos_r"
FROM (SELECT * FROM _temp_view_8) F0
GROUP BY (CASE  WHEN (F0."o_custkey" >= 7500) THEN 7500 WHEN ((F0."o_custkey" < 7500) AND (F0."o_custkey" >= 1)) THEN 1 ELSE 1 END)) F1 ON (((F0."lb_c_custkey" <= F1."ub_o_custkey") AND (F0."ub_c_custkey" >= F1."lb_o_custkey"))))) F0) F0
WHERE (F0."bst_r" > 0)) F0 JOIN (
SELECT F0."l_orderkey" AS "l_orderkey", F0."l_orderkey" AS "ub_l_orderkey", F0."l_orderkey" AS "lb_l_orderkey", (CASE  WHEN (F0."ub_l_orderkey" = F0."lb_l_orderkey") THEN F0."cet_r" ELSE 0 END) AS "cet_r", F0."bst_r" AS "bst_r", F0."bst_r" AS "pos_r"
FROM (
SELECT F0."l_orderkey" AS "l_orderkey", F0."ub_l_orderkey" AS "ub_l_orderkey", F0."lb_l_orderkey" AS "lb_l_orderkey", F0."cet_r" AS "cet_r", F0."bst_r" AS "bst_r", F0."pos_r" AS "pos_r"
FROM (SELECT * FROM _temp_view_12) F0) F0
WHERE (F0."bst_r" > 0)) F1 ON ((F0."o_orderkey" = F1."l_orderkey"))) UNION ALL 
SELECT F0."c_custkey" AS "c_custkey", F0."o_custkey" AS "o_custkey", F0."o_orderkey" AS "o_orderkey", F0."o_orderdate" AS "o_orderdate", F0."o_shippriority" AS "o_shippriority", F1."l_orderkey" AS "l_orderkey", F0."ub_c_custkey" AS "ub_c_custkey", F0."lb_c_custkey" AS "lb_c_custkey", F0."ub_o_custkey" AS "ub_o_custkey", F0."lb_o_custkey" AS "lb_o_custkey", F0."ub_o_orderkey" AS "ub_o_orderkey", F0."lb_o_orderkey" AS "lb_o_orderkey", F0."ub_o_orderdate" AS "ub_o_orderdate", F0."lb_o_orderdate" AS "lb_o_orderdate", F0."ub_o_shippriority" AS "ub_o_shippriority", F0."lb_o_shippriority" AS "lb_o_shippriority", F1."ub_l_orderkey" AS "ub_l_orderkey", F1."lb_l_orderkey" AS "lb_l_orderkey", ((F0."cet_r" * F1."cet_r") * (CASE  WHEN ((F0."o_orderkey" = F1."l_orderkey") AND ((F0."ub_o_orderkey" = F0."lb_o_orderkey") AND (F1."ub_l_orderkey" = F1."lb_l_orderkey"))) THEN 1 ELSE 0 END)) AS "cet_r", ((F0."bst_r" * F1."bst_r") * (CASE  WHEN (F0."o_orderkey" = F1."l_orderkey") THEN 1 ELSE 0 END)) AS "bst_r", (F0."pos_r" * F1."pos_r") AS "pos_r"
FROM ((
SELECT min(F0."c_custkey") AS "c_custkey", min(F0."o_custkey") AS "o_custkey", (CASE  WHEN (F0."o_orderkey" >= 300000) THEN 300000 WHEN ((F0."o_orderkey" < 300000) AND (F0."o_orderkey" >= 1)) THEN 1 ELSE 1 END) AS "o_orderkey", min(F0."o_orderdate") AS "o_orderdate", min(F0."o_shippriority") AS "o_shippriority", max(F0."ub_c_custkey") AS "ub_c_custkey", min(F0."lb_c_custkey") AS "lb_c_custkey", max(F0."ub_o_custkey") AS "ub_o_custkey", min(F0."lb_o_custkey") AS "lb_o_custkey", max(F0."ub_o_orderkey") AS "ub_o_orderkey", min(F0."lb_o_orderkey") AS "lb_o_orderkey", max(F0."ub_o_orderdate") AS "ub_o_orderdate", min(F0."lb_o_orderdate") AS "lb_o_orderdate", max(F0."ub_o_shippriority") AS "ub_o_shippriority", min(F0."lb_o_shippriority") AS "lb_o_shippriority", sum(F0."cet_r") AS "cet_r", sum(F0."bst_r") AS "bst_r", sum(F0."pos_r") AS "pos_r"
FROM (SELECT * FROM _temp_view_14) F0
GROUP BY (CASE  WHEN (F0."o_orderkey" >= 300000) THEN 300000 WHEN ((F0."o_orderkey" < 300000) AND (F0."o_orderkey" >= 1)) THEN 1 ELSE 1 END)) F0 JOIN (
SELECT (CASE  WHEN (F0."l_orderkey" >= 300000) THEN 300000 WHEN ((F0."l_orderkey" < 300000) AND (F0."l_orderkey" >= 1)) THEN 1 ELSE 1 END) AS "l_orderkey", max(F0."ub_l_orderkey") AS "ub_l_orderkey", min(F0."lb_l_orderkey") AS "lb_l_orderkey", sum(F0."cet_r") AS "cet_r", sum(F0."bst_r") AS "bst_r", sum(F0."pos_r") AS "pos_r"
FROM (SELECT * FROM _temp_view_28) F0
GROUP BY (CASE  WHEN (F0."l_orderkey" >= 300000) THEN 300000 WHEN ((F0."l_orderkey" < 300000) AND (F0."l_orderkey" >= 1)) THEN 1 ELSE 1 END)) F1 ON (((F0."lb_o_orderkey" <= F1."ub_l_orderkey") AND (F0."ub_o_orderkey" >= F1."lb_l_orderkey"))))) F0;