drop table cust_c_custkey;
commit;
drop table cust_c_name;
commit;
drop table cust_c_address;
commit;
drop table cust_c_nationkey;
commit;
drop table cust_c_phone;
commit;
drop table cust_c_acctbal;
commit;
drop table cust_c_mktsegment;
commit;
drop table cust_c_comment;
commit;
create trio table cust_c_custkey (tid int, c_custkey int, uncertain(c_custkey));
commit;
create trio table cust_c_name (tid int, c_name varchar(25), uncertain(c_name));
commit;
create trio table cust_c_address (tid int, c_address varchar(40), uncertain(c_address));
commit;
create trio table cust_c_nationkey (tid int, c_nationkey int, uncertain(c_nationkey));
commit;
create trio table cust_c_phone (tid int, c_phone varchar(15), uncertain(c_phone));
commit;
create trio table cust_c_acctbal (tid int, c_acctbal float, uncertain(c_acctbal));
commit;
create trio table cust_c_mktsegment (tid int, c_mktsegment varchar(10), uncertain(c_mktsegment));
commit;
create trio table cust_c_comment (tid int, c_comment varchar(255), uncertain(c_comment));
commit;