drop table lineitem_l_orderkey;
commit;
drop table lineitem_l_partkey;
commit;
drop table lineitem_l_suppkey;
commit;
drop table lineitem_l_linenumber;
commit;
drop table lineitem_l_quantity;
commit;
drop table lineitem_l_extendedprice;
commit;
drop table lineitem_l_discount;
commit;
drop table lineitem_l_tax;
commit;
drop table lineitem_l_returnflag;
commit;
drop table lineitem_l_linestatus;
commit;
drop table lineitem_l_shipdate;
commit;
drop table lineitem_l_commitdate;
commit;
drop table lineitem_l_receiptdate;
commit;
drop table lineitem_l_shipinstruct;
commit;
drop table lineitem_l_shipmode;
commit;
drop table lineitem_l_comment;
commit;
create trio table lineitem_l_orderkey (tid int, l_orderkey int, uncertain(l_orderkey));
commit;
create trio table lineitem_l_partkey (tid int, l_partkey int, uncertain(l_partkey));
commit;
create trio table lineitem_l_suppkey (tid int, l_suppkey int, uncertain(l_suppkey));
commit;
create trio table lineitem_l_linenumber (tid int, l_linenumber int, uncertain(l_linenumber));
commit;
create trio table lineitem_l_quantity (tid int, l_quantity int, uncertain(l_quantity));
commit;
create trio table lineitem_l_extendedprice (tid int, l_extendedprice float, uncertain(l_extendedprice));
commit;
create trio table lineitem_l_discount (tid int, l_discount float, uncertain(l_discount));
commit;
create trio table lineitem_l_tax (tid int, l_tax float, uncertain(l_tax));
commit;
create trio table lineitem_l_returnflag (tid int, l_returnflag varchar(1), uncertain(l_returnflag));
commit;
create trio table lineitem_l_linestatus (tid int, l_linestatus varchar(1), uncertain(l_linestatus));
commit;
create trio table lineitem_l_shipdate (tid int, l_shipdate varchar, uncertain(l_shipdate));
commit;
create trio table lineitem_l_commitdate (tid int, l_commitdate varchar, uncertain(l_commitdate));
commit;
create trio table lineitem_l_receiptdate (tid int, l_receiptdate varchar, uncertain(l_receiptdate));
commit;
create trio table lineitem_l_shipinstruct (tid int, l_shipinstruct varchar(25), uncertain(l_shipinstruct));
commit;
create trio table lineitem_l_shipmode (tid int, l_shipmode varchar(10), uncertain(l_shipmode));
commit;
create trio table lineitem_l_comment (tid int, l_comment varchar(255), uncertain(l_comment));
commit;