create table part_p_partkey (c1 integer, w1 integer, tid integer, p_partkey integer);
create table part_p_name (c1 integer, w1 integer, tid integer, p_name varchar(55));
create table part_p_mfgr (c1 integer, w1 integer, tid integer, p_mfgr char(25));
create table part_p_brand (c1 integer, w1 integer, tid integer, p_brand char(10));
create table part_p_type (c1 integer, w1 integer, tid integer, p_type varchar(25));
create table part_p_size (c1 integer, w1 integer, tid integer, p_size integer);
create table part_p_container (c1 integer, w1 integer, tid integer, p_container char(10));
create table part_p_retailprice (c1 integer, w1 integer, tid integer, p_retailprice float);
create table part_p_comment (c1 integer, w1 integer, tid integer, p_comment varchar(255));