SELECT F0."AGG_GB_ARG1" AS "n_name", min(F0."AGG_GB_ARG0") AS "revenue", F0."ub_agg_gb_arg1" AS "ub_n_name", F0."lb_agg_gb_arg1" AS "lb_n_name", sum((F1."ub_agg_gb_arg0" * (CASE  WHEN (F1."ub_agg_gb_arg0" > 0) THEN F1."pos_r" ELSE 0 END))) AS "ub_revenue", sum((F1."lb_agg_gb_arg0" * (CASE  WHEN (F1."lb_agg_gb_arg0" > 0) THEN 0 ELSE F1."pos_r" END))) AS "lb_revenue", max((CASE  WHEN (F0."cet_r" > 0) THEN 1 ELSE 0 END)) AS "cet_r", max((CASE  WHEN (F0."bst_r" > 0) THEN 1 ELSE 0 END)) AS "bst_r", sum(F1."pos_r") AS "pos_r"
FROM ((
SELECT max(F0."ub_n_name") AS "ub_agg_gb_arg1", min(F0."lb_n_name") AS "lb_agg_gb_arg1", sum(((F1."l_extendedprice" * (1 - F1."l_discount")) * (F0."bst_r" * F1."bst_r"))) AS "AGG_GB_ARG0", max(((CASE  WHEN (F0."ub_n_name" = F0."lb_n_name") THEN 1 ELSE 0 END) * (F0."cet_r" * F1."cet_r"))) AS "cet_r", max((F0."bst_r" * F1."bst_r")) AS "bst_r", F0."n_name" AS "AGG_GB_ARG1"
FROM ((
SELECT F0."r_regionkey" AS "r_regionkey", F1."n_name" AS "n_name", F1."n_nationkey" AS "n_nationkey", F1."n_regionkey" AS "n_regionkey", F0."ub_r_regionkey" AS "ub_r_regionkey", F0."lb_r_regionkey" AS "lb_r_regionkey", F1."ub_n_name" AS "ub_n_name", F1."lb_n_name" AS "lb_n_name", F1."ub_n_nationkey" AS "ub_n_nationkey", F1."lb_n_nationkey" AS "lb_n_nationkey", F1."ub_n_regionkey" AS "ub_n_regionkey", F1."lb_n_regionkey" AS "lb_n_regionkey", (F0."cet_r" * F1."cet_r") AS "cet_r", (F0."bst_r" * F1."bst_r") AS "bst_r", (F0."pos_r" * F1."pos_r") AS "pos_r"
FROM ((
SELECT F0."r_regionkey" AS "r_regionkey", F0."r_regionkey" AS "ub_r_regionkey", F0."r_regionkey" AS "lb_r_regionkey", (CASE  WHEN (F0."ub_r_regionkey" = F0."lb_r_regionkey") THEN F0."cet_r" ELSE 0 END) AS "cet_r", F0."bst_r" AS "bst_r", F0."bst_r" AS "pos_r"
FROM (
SELECT F0."r_regionkey" AS "r_regionkey", F0."ub_r_regionkey" AS "ub_r_regionkey", F0."lb_r_regionkey" AS "lb_r_regionkey", (CASE  WHEN ((F0."r_name" = 'ASIA') AND ((F0."ub_r_name" = F0."lb_r_name") AND ('ASIA' = 'ASIA'))) THEN 1 ELSE 0 END) AS "cet_r", (CASE  WHEN (F0."r_name" = 'ASIA') THEN 1 ELSE 0 END) AS "bst_r", F0."pos_r" AS "pos_r"
FROM (
SELECT F0."tid" AS "tid", F0."r_regionkey" AS "r_regionkey", F0."r_name" AS "r_name", F0."r_comment" AS "r_comment", F0."ub_tid" AS "ub_tid", F0."lb_tid" AS "lb_tid", F0."ub_r_regionkey" AS "ub_r_regionkey", F0."lb_r_regionkey" AS "lb_r_regionkey", F0."ub_r_name" AS "ub_r_name", F0."lb_r_name" AS "lb_r_name", F0."ub_r_comment" AS "ub_r_comment", F0."lb_r_comment" AS "lb_r_comment", F0."cet_r" AS "cet_r", F0."bst_r" AS "bst_r", F0."pos_r" AS "pos_r"
FROM "region_radb" AS F0) F0
WHERE ((F0."lb_r_name" <= 'ASIA') AND (F0."ub_r_name" >= 'ASIA'))) F0
WHERE (F0."bst_r" > 0)) F0 JOIN (
SELECT F0."n_name" AS "n_name", F0."n_nationkey" AS "n_nationkey", F0."n_regionkey" AS "n_regionkey", F0."n_name" AS "ub_n_name", F0."n_name" AS "lb_n_name", F0."n_nationkey" AS "ub_n_nationkey", F0."n_nationkey" AS "lb_n_nationkey", F0."n_regionkey" AS "ub_n_regionkey", F0."n_regionkey" AS "lb_n_regionkey", (CASE  WHEN (((F0."ub_n_name" = F0."lb_n_name") AND (F0."ub_n_nationkey" = F0."lb_n_nationkey")) AND (F0."ub_n_regionkey" = F0."lb_n_regionkey")) THEN F0."cet_r" ELSE 0 END) AS "cet_r", F0."bst_r" AS "bst_r", F0."bst_r" AS "pos_r"
FROM (
SELECT F0."n_name" AS "n_name", F0."n_nationkey" AS "n_nationkey", F0."n_regionkey" AS "n_regionkey", F0."ub_n_name" AS "ub_n_name", F0."lb_n_name" AS "lb_n_name", F0."ub_n_nationkey" AS "ub_n_nationkey", F0."lb_n_nationkey" AS "lb_n_nationkey", F0."ub_n_regionkey" AS "ub_n_regionkey", F0."lb_n_regionkey" AS "lb_n_regionkey", F0."cet_r" AS "cet_r", F0."bst_r" AS "bst_r", F0."pos_r" AS "pos_r"
FROM "nation_radb" AS F0) F0
WHERE (F0."bst_r" > 0)) F1 ON ((F0."r_regionkey" = F1."n_regionkey")))) F0 JOIN (
SELECT F0."o_orderkey" AS "o_orderkey", F0."o_custkey" AS "o_custkey", F0."l_orderkey" AS "l_orderkey", F0."l_suppkey" AS "l_suppkey", F0."l_extendedprice" AS "l_extendedprice", F0."l_discount" AS "l_discount", F0."c_custkey" AS "c_custkey", F0."c_nationkey" AS "c_nationkey", F0."s_suppkey" AS "s_suppkey", F0."s_nationkey" AS "s_nationkey", F0."ub_o_orderkey" AS "ub_o_orderkey", F0."lb_o_orderkey" AS "lb_o_orderkey", F0."ub_o_custkey" AS "ub_o_custkey", F0."lb_o_custkey" AS "lb_o_custkey", F0."ub_l_orderkey" AS "ub_l_orderkey", F0."lb_l_orderkey" AS "lb_l_orderkey", F0."ub_l_suppkey" AS "ub_l_suppkey", F0."lb_l_suppkey" AS "lb_l_suppkey", F0."ub_l_extendedprice" AS "ub_l_extendedprice", F0."lb_l_extendedprice" AS "lb_l_extendedprice", F0."ub_l_discount" AS "ub_l_discount", F0."lb_l_discount" AS "lb_l_discount", F0."ub_c_custkey" AS "ub_c_custkey", F0."lb_c_custkey" AS "lb_c_custkey", F0."ub_c_nationkey" AS "ub_c_nationkey", F0."lb_c_nationkey" AS "lb_c_nationkey", F0."ub_s_suppkey" AS "ub_s_suppkey", F0."lb_s_suppkey" AS "lb_s_suppkey", F0."ub_s_nationkey" AS "ub_s_nationkey", F0."lb_s_nationkey" AS "lb_s_nationkey", (CASE  WHEN ((F0."c_nationkey" = F0."s_nationkey") AND ((F0."ub_c_nationkey" = F0."lb_c_nationkey") AND (F0."ub_s_nationkey" = F0."lb_s_nationkey"))) THEN 1 ELSE 0 END) AS "cet_r", (CASE  WHEN (F0."c_nationkey" = F0."s_nationkey") THEN 1 ELSE 0 END) AS "bst_r", F0."pos_r" AS "pos_r"
FROM (
SELECT F0."o_orderkey" AS "o_orderkey", F0."o_custkey" AS "o_custkey", F0."l_orderkey" AS "l_orderkey", F0."l_suppkey" AS "l_suppkey", F0."l_extendedprice" AS "l_extendedprice", F0."l_discount" AS "l_discount", F0."c_custkey" AS "c_custkey", F0."c_nationkey" AS "c_nationkey", F1."s_suppkey" AS "s_suppkey", F1."s_nationkey" AS "s_nationkey", F0."ub_o_orderkey" AS "ub_o_orderkey", F0."lb_o_orderkey" AS "lb_o_orderkey", F0."ub_o_custkey" AS "ub_o_custkey", F0."lb_o_custkey" AS "lb_o_custkey", F0."ub_l_orderkey" AS "ub_l_orderkey", F0."lb_l_orderkey" AS "lb_l_orderkey", F0."ub_l_suppkey" AS "ub_l_suppkey", F0."lb_l_suppkey" AS "lb_l_suppkey", F0."ub_l_extendedprice" AS "ub_l_extendedprice", F0."lb_l_extendedprice" AS "lb_l_extendedprice", F0."ub_l_discount" AS "ub_l_discount", F0."lb_l_discount" AS "lb_l_discount", F0."ub_c_custkey" AS "ub_c_custkey", F0."lb_c_custkey" AS "lb_c_custkey", F0."ub_c_nationkey" AS "ub_c_nationkey", F0."lb_c_nationkey" AS "lb_c_nationkey", F1."ub_s_suppkey" AS "ub_s_suppkey", F1."lb_s_suppkey" AS "lb_s_suppkey", F1."ub_s_nationkey" AS "ub_s_nationkey", F1."lb_s_nationkey" AS "lb_s_nationkey", (F0."cet_r" * F1."cet_r") AS "cet_r", (F0."bst_r" * F1."bst_r") AS "bst_r", (F0."pos_r" * F1."pos_r") AS "pos_r"
FROM ((
SELECT F0."o_orderkey" AS "o_orderkey", F0."o_custkey" AS "o_custkey", F0."l_orderkey" AS "l_orderkey", F0."l_suppkey" AS "l_suppkey", F0."l_extendedprice" AS "l_extendedprice", F0."l_discount" AS "l_discount", F1."c_custkey" AS "c_custkey", F1."c_nationkey" AS "c_nationkey", F0."ub_o_orderkey" AS "ub_o_orderkey", F0."lb_o_orderkey" AS "lb_o_orderkey", F0."ub_o_custkey" AS "ub_o_custkey", F0."lb_o_custkey" AS "lb_o_custkey", F0."ub_l_orderkey" AS "ub_l_orderkey", F0."lb_l_orderkey" AS "lb_l_orderkey", F0."ub_l_suppkey" AS "ub_l_suppkey", F0."lb_l_suppkey" AS "lb_l_suppkey", F0."ub_l_extendedprice" AS "ub_l_extendedprice", F0."lb_l_extendedprice" AS "lb_l_extendedprice", F0."ub_l_discount" AS "ub_l_discount", F0."lb_l_discount" AS "lb_l_discount", F1."ub_c_custkey" AS "ub_c_custkey", F1."lb_c_custkey" AS "lb_c_custkey", F1."ub_c_nationkey" AS "ub_c_nationkey", F1."lb_c_nationkey" AS "lb_c_nationkey", (F0."cet_r" * F1."cet_r") AS "cet_r", (F0."bst_r" * F1."bst_r") AS "bst_r", (F0."pos_r" * F1."pos_r") AS "pos_r"
FROM ((
SELECT F0."o_orderkey" AS "o_orderkey", F0."o_custkey" AS "o_custkey", F1."l_orderkey" AS "l_orderkey", F1."l_suppkey" AS "l_suppkey", F1."l_extendedprice" AS "l_extendedprice", F1."l_discount" AS "l_discount", F0."ub_o_orderkey" AS "ub_o_orderkey", F0."lb_o_orderkey" AS "lb_o_orderkey", F0."ub_o_custkey" AS "ub_o_custkey", F0."lb_o_custkey" AS "lb_o_custkey", F1."ub_l_orderkey" AS "ub_l_orderkey", F1."lb_l_orderkey" AS "lb_l_orderkey", F1."ub_l_suppkey" AS "ub_l_suppkey", F1."lb_l_suppkey" AS "lb_l_suppkey", F1."ub_l_extendedprice" AS "ub_l_extendedprice", F1."lb_l_extendedprice" AS "lb_l_extendedprice", F1."ub_l_discount" AS "ub_l_discount", F1."lb_l_discount" AS "lb_l_discount", (F0."cet_r" * F1."cet_r") AS "cet_r", (F0."bst_r" * F1."bst_r") AS "bst_r", (F0."pos_r" * F1."pos_r") AS "pos_r"
FROM ((
SELECT F0."o_orderkey" AS "o_orderkey", F0."o_custkey" AS "o_custkey", F0."o_orderkey" AS "ub_o_orderkey", F0."o_orderkey" AS "lb_o_orderkey", F0."o_custkey" AS "ub_o_custkey", F0."o_custkey" AS "lb_o_custkey", (CASE  WHEN ((F0."ub_o_orderkey" = F0."lb_o_orderkey") AND (F0."ub_o_custkey" = F0."lb_o_custkey")) THEN F0."cet_r" ELSE 0 END) AS "cet_r", F0."bst_r" AS "bst_r", F0."bst_r" AS "pos_r"
FROM (
SELECT F0."o_orderkey" AS "o_orderkey", F0."o_custkey" AS "o_custkey", F0."ub_o_orderkey" AS "ub_o_orderkey", F0."lb_o_orderkey" AS "lb_o_orderkey", F0."ub_o_custkey" AS "ub_o_custkey", F0."lb_o_custkey" AS "lb_o_custkey", (CASE  WHEN ((F0."lb_o_orderdate" >= '1994-01-01') AND (F0."ub_o_orderdate" < '1995-01-01')) THEN 1 ELSE 0 END) AS "cet_r", (CASE  WHEN ((F0."o_orderdate" >= '1994-01-01') and (F0."o_orderdate" < '1995-01-01')) THEN 1 ELSE 0 END) AS "bst_r", F0."pos_r" AS "pos_r"
FROM (
SELECT F0."tid" AS "tid", F0."o_orderkey" AS "o_orderkey", F0."o_custkey" AS "o_custkey", F0."o_orderstatus" AS "o_orderstatus", F0."o_totalprice" AS "o_totalprice", F0."o_orderdate" AS "o_orderdate", F0."o_orderpriority" AS "o_orderpriority", F0."o_clerk" AS "o_clerk", F0."o_shippriority" AS "o_shippriority", F0."o_comment" AS "o_comment", F0."ub_tid" AS "ub_tid", F0."lb_tid" AS "lb_tid", F0."ub_o_orderkey" AS "ub_o_orderkey", F0."lb_o_orderkey" AS "lb_o_orderkey", F0."ub_o_custkey" AS "ub_o_custkey", F0."lb_o_custkey" AS "lb_o_custkey", F0."ub_o_orderstatus" AS "ub_o_orderstatus", F0."lb_o_orderstatus" AS "lb_o_orderstatus", F0."ub_o_totalprice" AS "ub_o_totalprice", F0."lb_o_totalprice" AS "lb_o_totalprice", F0."ub_o_orderdate" AS "ub_o_orderdate", F0."lb_o_orderdate" AS "lb_o_orderdate", F0."ub_o_orderpriority" AS "ub_o_orderpriority", F0."lb_o_orderpriority" AS "lb_o_orderpriority", F0."ub_o_clerk" AS "ub_o_clerk", F0."lb_o_clerk" AS "lb_o_clerk", F0."ub_o_shippriority" AS "ub_o_shippriority", F0."lb_o_shippriority" AS "lb_o_shippriority", F0."ub_o_comment" AS "ub_o_comment", F0."lb_o_comment" AS "lb_o_comment", F0."cet_r" AS "cet_r", F0."bst_r" AS "bst_r", F0."pos_r" AS "pos_r"
FROM "orders_radb" AS F0) F0
WHERE ((F0."ub_o_orderdate" >= '1994-01-01') AND (F0."lb_o_orderdate" < '1995-01-01'))) F0
WHERE (F0."bst_r" > 0)) F0 JOIN (
SELECT F0."l_orderkey" AS "l_orderkey", F0."l_suppkey" AS "l_suppkey", F0."l_extendedprice" AS "l_extendedprice", F0."l_discount" AS "l_discount", F0."l_orderkey" AS "ub_l_orderkey", F0."l_orderkey" AS "lb_l_orderkey", F0."l_suppkey" AS "ub_l_suppkey", F0."l_suppkey" AS "lb_l_suppkey", F0."l_extendedprice" AS "ub_l_extendedprice", F0."l_extendedprice" AS "lb_l_extendedprice", F0."l_discount" AS "ub_l_discount", F0."l_discount" AS "lb_l_discount", (CASE  WHEN ((((F0."ub_l_orderkey" = F0."lb_l_orderkey") AND (F0."ub_l_suppkey" = F0."lb_l_suppkey")) AND (F0."ub_l_extendedprice" = F0."lb_l_extendedprice")) AND (F0."ub_l_discount" = F0."lb_l_discount")) THEN F0."cet_r" ELSE 0 END) AS "cet_r", F0."bst_r" AS "bst_r", F0."bst_r" AS "pos_r"
FROM (
SELECT F0."l_orderkey" AS "l_orderkey", F0."l_suppkey" AS "l_suppkey", F0."l_extendedprice" AS "l_extendedprice", F0."l_discount" AS "l_discount", F0."ub_l_orderkey" AS "ub_l_orderkey", F0."lb_l_orderkey" AS "lb_l_orderkey", F0."ub_l_suppkey" AS "ub_l_suppkey", F0."lb_l_suppkey" AS "lb_l_suppkey", F0."ub_l_extendedprice" AS "ub_l_extendedprice", F0."lb_l_extendedprice" AS "lb_l_extendedprice", F0."ub_l_discount" AS "ub_l_discount", F0."lb_l_discount" AS "lb_l_discount", F0."cet_r" AS "cet_r", F0."bst_r" AS "bst_r", F0."pos_r" AS "pos_r"
FROM "lineitem_radb" AS F0) F0
WHERE (F0."bst_r" > 0)) F1 ON ((F0."o_orderkey" = F1."l_orderkey")))) F0 JOIN (
SELECT F0."c_custkey" AS "c_custkey", F0."c_nationkey" AS "c_nationkey", F0."c_custkey" AS "ub_c_custkey", F0."c_custkey" AS "lb_c_custkey", F0."c_nationkey" AS "ub_c_nationkey", F0."c_nationkey" AS "lb_c_nationkey", (CASE  WHEN ((F0."ub_c_custkey" = F0."lb_c_custkey") AND (F0."ub_c_nationkey" = F0."lb_c_nationkey")) THEN F0."cet_r" ELSE 0 END) AS "cet_r", F0."bst_r" AS "bst_r", F0."bst_r" AS "pos_r"
FROM (
SELECT F0."c_custkey" AS "c_custkey", F0."c_nationkey" AS "c_nationkey", F0."ub_c_custkey" AS "ub_c_custkey", F0."lb_c_custkey" AS "lb_c_custkey", F0."ub_c_nationkey" AS "ub_c_nationkey", F0."lb_c_nationkey" AS "lb_c_nationkey", F0."cet_r" AS "cet_r", F0."bst_r" AS "bst_r", F0."pos_r" AS "pos_r"
FROM "customer_radb" AS F0) F0
WHERE (F0."bst_r" > 0)) F1 ON ((F0."o_custkey" = F1."c_custkey")))) F0 JOIN (
SELECT F0."s_suppkey" AS "s_suppkey", F0."s_nationkey" AS "s_nationkey", F0."s_suppkey" AS "ub_s_suppkey", F0."s_suppkey" AS "lb_s_suppkey", F0."s_nationkey" AS "ub_s_nationkey", F0."s_nationkey" AS "lb_s_nationkey", (CASE  WHEN ((F0."ub_s_suppkey" = F0."lb_s_suppkey") AND (F0."ub_s_nationkey" = F0."lb_s_nationkey")) THEN F0."cet_r" ELSE 0 END) AS "cet_r", F0."bst_r" AS "bst_r", F0."bst_r" AS "pos_r"
FROM (
SELECT F0."s_suppkey" AS "s_suppkey", F0."s_nationkey" AS "s_nationkey", F0."ub_s_suppkey" AS "ub_s_suppkey", F0."lb_s_suppkey" AS "lb_s_suppkey", F0."ub_s_nationkey" AS "ub_s_nationkey", F0."lb_s_nationkey" AS "lb_s_nationkey", F0."cet_r" AS "cet_r", F0."bst_r" AS "bst_r", F0."pos_r" AS "pos_r"
FROM "supplier_radb" AS F0) F0
WHERE (F0."bst_r" > 0)) F1 ON ((F0."l_suppkey" = F1."s_suppkey")))) F0
WHERE ((F0."lb_c_nationkey" <= F0."ub_s_nationkey") AND (F0."ub_c_nationkey" >= F0."lb_s_nationkey"))) F1 ON ((F0."n_nationkey" = F1."s_nationkey")))
GROUP BY F0."n_name") F0 JOIN (
SELECT (F1."l_extendedprice" * (1 - F1."l_discount")) AS "AGG_GB_ARG0", F0."n_name" AS "AGG_GB_ARG1", greatest(greatest((F1."ub_l_extendedprice" * (1 - F1."lb_l_discount")), (F1."ub_l_extendedprice" * (1 - F1."ub_l_discount"))), greatest((F1."lb_l_extendedprice" * (1 - F1."lb_l_discount")), (F1."lb_l_extendedprice" * (1 - F1."ub_l_discount")))) AS "ub_agg_gb_arg0", least(least((F1."ub_l_extendedprice" * (1 - F1."lb_l_discount")), (F1."ub_l_extendedprice" * (1 - F1."ub_l_discount"))), least((F1."lb_l_extendedprice" * (1 - F1."lb_l_discount")), (F1."lb_l_extendedprice" * (1 - F1."ub_l_discount")))) AS "lb_agg_gb_arg0", F0."ub_n_name" AS "ub_agg_gb_arg1", F0."lb_n_name" AS "lb_agg_gb_arg1", ((F0."cet_r" + F1."cet_r") + (CASE  WHEN ((F0."n_nationkey" = F1."s_nationkey") AND ((F0."ub_n_nationkey" = F0."lb_n_nationkey") AND (F1."ub_s_nationkey" = F1."lb_s_nationkey"))) THEN 1 ELSE 0 END)) AS "cet_r", ((F0."bst_r" + F1."bst_r") + (CASE  WHEN (F0."n_nationkey" = F1."s_nationkey") THEN 1 ELSE 0 END)) AS "bst_r", (F0."pos_r" + F1."pos_r") AS "pos_r"
FROM ((
SELECT F0."r_regionkey" AS "r_regionkey", F1."n_name" AS "n_name", F1."n_nationkey" AS "n_nationkey", F1."n_regionkey" AS "n_regionkey", F0."ub_r_regionkey" AS "ub_r_regionkey", F0."lb_r_regionkey" AS "lb_r_regionkey", F1."ub_n_name" AS "ub_n_name", F1."lb_n_name" AS "lb_n_name", F1."ub_n_nationkey" AS "ub_n_nationkey", F1."lb_n_nationkey" AS "lb_n_nationkey", F1."ub_n_regionkey" AS "ub_n_regionkey", F1."lb_n_regionkey" AS "lb_n_regionkey", ((F0."cet_r" + F1."cet_r") + (CASE  WHEN ((F0."r_regionkey" = F1."n_regionkey") AND ((F0."ub_r_regionkey" = F0."lb_r_regionkey") AND (F1."ub_n_regionkey" = F1."lb_n_regionkey"))) THEN 1 ELSE 0 END)) AS "cet_r", ((F0."bst_r" + F1."bst_r") + (CASE  WHEN (F0."r_regionkey" = F1."n_regionkey") THEN 1 ELSE 0 END)) AS "bst_r", (F0."pos_r" + F1."pos_r") AS "pos_r"
FROM ((
SELECT (CASE  WHEN (F0."r_regionkey" >= 2) THEN 2 WHEN ((F0."r_regionkey" < 2) AND (F0."r_regionkey" >= 0)) THEN 0 ELSE 0 END) AS "r_regionkey", max(F0."ub_r_regionkey") AS "ub_r_regionkey", min(F0."lb_r_regionkey") AS "lb_r_regionkey", sum(0) AS "cet_r", sum(0) AS "bst_r", sum((CASE  WHEN (F0."r_name" = 'ASIA') THEN 1 ELSE 0 END)) AS "pos_r"
FROM (
SELECT F0."tid" AS "tid", F0."r_regionkey" AS "r_regionkey", F0."r_name" AS "r_name", F0."r_comment" AS "r_comment", F0."ub_tid" AS "ub_tid", F0."lb_tid" AS "lb_tid", F0."ub_r_regionkey" AS "ub_r_regionkey", F0."lb_r_regionkey" AS "lb_r_regionkey", F0."ub_r_name" AS "ub_r_name", F0."lb_r_name" AS "lb_r_name", F0."ub_r_comment" AS "ub_r_comment", F0."lb_r_comment" AS "lb_r_comment", F0."cet_r" AS "cet_r", F0."bst_r" AS "bst_r", F0."pos_r" AS "pos_r"
FROM "region_radb" AS F0) F0
WHERE ((F0."lb_r_name" <= 'ASIA') AND (F0."ub_r_name" >= 'ASIA'))
GROUP BY (CASE  WHEN (F0."r_regionkey" >= 2) THEN 2 WHEN ((F0."r_regionkey" < 2) AND (F0."r_regionkey" >= 0)) THEN 0 ELSE 0 END)) F0 JOIN (
SELECT min(F0."n_name") AS "n_name", min(F0."n_nationkey") AS "n_nationkey", (CASE  WHEN (F0."n_regionkey" >= 2) THEN 2 WHEN ((F0."n_regionkey" < 2) AND (F0."n_regionkey" >= 0)) THEN 0 ELSE 0 END) AS "n_regionkey", max(F0."ub_n_name") AS "ub_n_name", min(F0."lb_n_name") AS "lb_n_name", max(F0."ub_n_nationkey") AS "ub_n_nationkey", min(F0."lb_n_nationkey") AS "lb_n_nationkey", max(F0."ub_n_regionkey") AS "ub_n_regionkey", min(F0."lb_n_regionkey") AS "lb_n_regionkey", sum(0) AS "cet_r", sum(0) AS "bst_r", sum(F0."bst_r") AS "pos_r"
FROM "nation_radb" AS F0
GROUP BY (CASE  WHEN (F0."n_regionkey" >= 2) THEN 2 WHEN ((F0."n_regionkey" < 2) AND (F0."n_regionkey" >= 0)) THEN 0 ELSE 0 END)) F1 ON (((F0."lb_r_regionkey" <= F1."ub_n_regionkey") AND (F0."ub_r_regionkey" >= F1."lb_n_regionkey"))))) F0 JOIN (
SELECT F0."o_orderkey" AS "o_orderkey", F0."o_custkey" AS "o_custkey", F0."l_orderkey" AS "l_orderkey", F0."l_suppkey" AS "l_suppkey", F0."l_extendedprice" AS "l_extendedprice", F0."l_discount" AS "l_discount", F0."c_custkey" AS "c_custkey", F0."c_nationkey" AS "c_nationkey", F0."s_suppkey" AS "s_suppkey", F0."s_nationkey" AS "s_nationkey", F0."ub_o_orderkey" AS "ub_o_orderkey", F0."lb_o_orderkey" AS "lb_o_orderkey", F0."ub_o_custkey" AS "ub_o_custkey", F0."lb_o_custkey" AS "lb_o_custkey", F0."ub_l_orderkey" AS "ub_l_orderkey", F0."lb_l_orderkey" AS "lb_l_orderkey", F0."ub_l_suppkey" AS "ub_l_suppkey", F0."lb_l_suppkey" AS "lb_l_suppkey", F0."ub_l_extendedprice" AS "ub_l_extendedprice", F0."lb_l_extendedprice" AS "lb_l_extendedprice", F0."ub_l_discount" AS "ub_l_discount", F0."lb_l_discount" AS "lb_l_discount", F0."ub_c_custkey" AS "ub_c_custkey", F0."lb_c_custkey" AS "lb_c_custkey", F0."ub_c_nationkey" AS "ub_c_nationkey", F0."lb_c_nationkey" AS "lb_c_nationkey", F0."ub_s_suppkey" AS "ub_s_suppkey", F0."lb_s_suppkey" AS "lb_s_suppkey", F0."ub_s_nationkey" AS "ub_s_nationkey", F0."lb_s_nationkey" AS "lb_s_nationkey", (CASE  WHEN ((F0."c_nationkey" = F0."s_nationkey") AND ((F0."ub_c_nationkey" = F0."lb_c_nationkey") AND (F0."ub_s_nationkey" = F0."lb_s_nationkey"))) THEN 1 ELSE 0 END) AS "cet_r", (CASE  WHEN (F0."c_nationkey" = F0."s_nationkey") THEN 1 ELSE 0 END) AS "bst_r", F0."pos_r" AS "pos_r"
FROM (
SELECT F0."o_orderkey" AS "o_orderkey", F0."o_custkey" AS "o_custkey", F0."l_orderkey" AS "l_orderkey", F0."l_suppkey" AS "l_suppkey", F0."l_extendedprice" AS "l_extendedprice", F0."l_discount" AS "l_discount", F0."c_custkey" AS "c_custkey", F0."c_nationkey" AS "c_nationkey", F1."s_suppkey" AS "s_suppkey", F1."s_nationkey" AS "s_nationkey", F0."ub_o_orderkey" AS "ub_o_orderkey", F0."lb_o_orderkey" AS "lb_o_orderkey", F0."ub_o_custkey" AS "ub_o_custkey", F0."lb_o_custkey" AS "lb_o_custkey", F0."ub_l_orderkey" AS "ub_l_orderkey", F0."lb_l_orderkey" AS "lb_l_orderkey", F0."ub_l_suppkey" AS "ub_l_suppkey", F0."lb_l_suppkey" AS "lb_l_suppkey", F0."ub_l_extendedprice" AS "ub_l_extendedprice", F0."lb_l_extendedprice" AS "lb_l_extendedprice", F0."ub_l_discount" AS "ub_l_discount", F0."lb_l_discount" AS "lb_l_discount", F0."ub_c_custkey" AS "ub_c_custkey", F0."lb_c_custkey" AS "lb_c_custkey", F0."ub_c_nationkey" AS "ub_c_nationkey", F0."lb_c_nationkey" AS "lb_c_nationkey", F1."ub_s_suppkey" AS "ub_s_suppkey", F1."lb_s_suppkey" AS "lb_s_suppkey", F1."ub_s_nationkey" AS "ub_s_nationkey", F1."lb_s_nationkey" AS "lb_s_nationkey", ((F0."cet_r" + F1."cet_r") + (CASE  WHEN ((F0."l_suppkey" = F1."s_suppkey") AND ((F0."ub_l_suppkey" = F0."lb_l_suppkey") AND (F1."ub_s_suppkey" = F1."lb_s_suppkey"))) THEN 1 ELSE 0 END)) AS "cet_r", ((F0."bst_r" + F1."bst_r") + (CASE  WHEN (F0."l_suppkey" = F1."s_suppkey") THEN 1 ELSE 0 END)) AS "bst_r", (F0."pos_r" + F1."pos_r") AS "pos_r"
FROM ((
SELECT F0."o_orderkey" AS "o_orderkey", F0."o_custkey" AS "o_custkey", F0."l_orderkey" AS "l_orderkey", F0."l_suppkey" AS "l_suppkey", F0."l_extendedprice" AS "l_extendedprice", F0."l_discount" AS "l_discount", F1."c_custkey" AS "c_custkey", F1."c_nationkey" AS "c_nationkey", F0."ub_o_orderkey" AS "ub_o_orderkey", F0."lb_o_orderkey" AS "lb_o_orderkey", F0."ub_o_custkey" AS "ub_o_custkey", F0."lb_o_custkey" AS "lb_o_custkey", F0."ub_l_orderkey" AS "ub_l_orderkey", F0."lb_l_orderkey" AS "lb_l_orderkey", F0."ub_l_suppkey" AS "ub_l_suppkey", F0."lb_l_suppkey" AS "lb_l_suppkey", F0."ub_l_extendedprice" AS "ub_l_extendedprice", F0."lb_l_extendedprice" AS "lb_l_extendedprice", F0."ub_l_discount" AS "ub_l_discount", F0."lb_l_discount" AS "lb_l_discount", F1."ub_c_custkey" AS "ub_c_custkey", F1."lb_c_custkey" AS "lb_c_custkey", F1."ub_c_nationkey" AS "ub_c_nationkey", F1."lb_c_nationkey" AS "lb_c_nationkey", ((F0."cet_r" + F1."cet_r") + (CASE  WHEN ((F0."o_custkey" = F1."c_custkey") AND ((F0."ub_o_custkey" = F0."lb_o_custkey") AND (F1."ub_c_custkey" = F1."lb_c_custkey"))) THEN 1 ELSE 0 END)) AS "cet_r", ((F0."bst_r" + F1."bst_r") + (CASE  WHEN (F0."o_custkey" = F1."c_custkey") THEN 1 ELSE 0 END)) AS "bst_r", (F0."pos_r" + F1."pos_r") AS "pos_r"
FROM ((
SELECT F0."o_orderkey" AS "o_orderkey", F0."o_custkey" AS "o_custkey", F1."l_orderkey" AS "l_orderkey", F1."l_suppkey" AS "l_suppkey", F1."l_extendedprice" AS "l_extendedprice", F1."l_discount" AS "l_discount", F0."ub_o_orderkey" AS "ub_o_orderkey", F0."lb_o_orderkey" AS "lb_o_orderkey", F0."ub_o_custkey" AS "ub_o_custkey", F0."lb_o_custkey" AS "lb_o_custkey", F1."ub_l_orderkey" AS "ub_l_orderkey", F1."lb_l_orderkey" AS "lb_l_orderkey", F1."ub_l_suppkey" AS "ub_l_suppkey", F1."lb_l_suppkey" AS "lb_l_suppkey", F1."ub_l_extendedprice" AS "ub_l_extendedprice", F1."lb_l_extendedprice" AS "lb_l_extendedprice", F1."ub_l_discount" AS "ub_l_discount", F1."lb_l_discount" AS "lb_l_discount", ((F0."cet_r" + F1."cet_r") + (CASE  WHEN ((F0."o_orderkey" = F1."l_orderkey") AND ((F0."ub_o_orderkey" = F0."lb_o_orderkey") AND (F1."ub_l_orderkey" = F1."lb_l_orderkey"))) THEN 1 ELSE 0 END)) AS "cet_r", ((F0."bst_r" + F1."bst_r") + (CASE  WHEN (F0."o_orderkey" = F1."l_orderkey") THEN 1 ELSE 0 END)) AS "bst_r", (F0."pos_r" + F1."pos_r") AS "pos_r"
FROM ((
SELECT (CASE  WHEN (F0."o_orderkey" >= 300000) THEN 300000 WHEN ((F0."o_orderkey" < 300000) AND (F0."o_orderkey" >= 1)) THEN 1 ELSE 1 END) AS "o_orderkey", min(F0."o_custkey") AS "o_custkey", max(F0."ub_o_orderkey") AS "ub_o_orderkey", min(F0."lb_o_orderkey") AS "lb_o_orderkey", max(F0."ub_o_custkey") AS "ub_o_custkey", min(F0."lb_o_custkey") AS "lb_o_custkey", sum(0) AS "cet_r", sum(0) AS "bst_r", sum((CASE  WHEN ((F0."o_orderdate" >= '1994-01-01') and (F0."o_orderdate" < '1995-01-01')) THEN 1 ELSE 0 END)) AS "pos_r"
FROM (
SELECT F0."tid" AS "tid", F0."o_orderkey" AS "o_orderkey", F0."o_custkey" AS "o_custkey", F0."o_orderstatus" AS "o_orderstatus", F0."o_totalprice" AS "o_totalprice", F0."o_orderdate" AS "o_orderdate", F0."o_orderpriority" AS "o_orderpriority", F0."o_clerk" AS "o_clerk", F0."o_shippriority" AS "o_shippriority", F0."o_comment" AS "o_comment", F0."ub_tid" AS "ub_tid", F0."lb_tid" AS "lb_tid", F0."ub_o_orderkey" AS "ub_o_orderkey", F0."lb_o_orderkey" AS "lb_o_orderkey", F0."ub_o_custkey" AS "ub_o_custkey", F0."lb_o_custkey" AS "lb_o_custkey", F0."ub_o_orderstatus" AS "ub_o_orderstatus", F0."lb_o_orderstatus" AS "lb_o_orderstatus", F0."ub_o_totalprice" AS "ub_o_totalprice", F0."lb_o_totalprice" AS "lb_o_totalprice", F0."ub_o_orderdate" AS "ub_o_orderdate", F0."lb_o_orderdate" AS "lb_o_orderdate", F0."ub_o_orderpriority" AS "ub_o_orderpriority", F0."lb_o_orderpriority" AS "lb_o_orderpriority", F0."ub_o_clerk" AS "ub_o_clerk", F0."lb_o_clerk" AS "lb_o_clerk", F0."ub_o_shippriority" AS "ub_o_shippriority", F0."lb_o_shippriority" AS "lb_o_shippriority", F0."ub_o_comment" AS "ub_o_comment", F0."lb_o_comment" AS "lb_o_comment", F0."cet_r" AS "cet_r", F0."bst_r" AS "bst_r", F0."pos_r" AS "pos_r"
FROM "orders_radb" AS F0) F0
WHERE ((F0."ub_o_orderdate" >= '1994-01-01') AND (F0."lb_o_orderdate" < '1995-01-01'))
GROUP BY (CASE  WHEN (F0."o_orderkey" >= 300000) THEN 300000 WHEN ((F0."o_orderkey" < 300000) AND (F0."o_orderkey" >= 1)) THEN 1 ELSE 1 END)) F0 JOIN (
SELECT (CASE  WHEN (F0."l_orderkey" >= 300000) THEN 300000 WHEN ((F0."l_orderkey" < 300000) AND (F0."l_orderkey" >= 1)) THEN 1 ELSE 1 END) AS "l_orderkey", min(F0."l_suppkey") AS "l_suppkey", min(F0."l_extendedprice") AS "l_extendedprice", min(F0."l_discount") AS "l_discount", max(F0."ub_l_orderkey") AS "ub_l_orderkey", min(F0."lb_l_orderkey") AS "lb_l_orderkey", max(F0."ub_l_suppkey") AS "ub_l_suppkey", min(F0."lb_l_suppkey") AS "lb_l_suppkey", max(F0."ub_l_extendedprice") AS "ub_l_extendedprice", min(F0."lb_l_extendedprice") AS "lb_l_extendedprice", max(F0."ub_l_discount") AS "ub_l_discount", min(F0."lb_l_discount") AS "lb_l_discount", sum(0) AS "cet_r", sum(0) AS "bst_r", sum(F0."bst_r") AS "pos_r"
FROM "lineitem_radb" AS F0
GROUP BY (CASE  WHEN (F0."l_orderkey" >= 300000) THEN 300000 WHEN ((F0."l_orderkey" < 300000) AND (F0."l_orderkey" >= 1)) THEN 1 ELSE 1 END)) F1 ON (((F0."lb_o_orderkey" <= F1."ub_l_orderkey") AND (F0."ub_o_orderkey" >= F1."lb_l_orderkey"))))) F0 JOIN (
SELECT (CASE  WHEN (F0."c_custkey" >= 7500) THEN 7500 WHEN ((F0."c_custkey" < 7500) AND (F0."c_custkey" >= 1)) THEN 1 ELSE 1 END) AS "c_custkey", min(F0."c_nationkey") AS "c_nationkey", max(F0."ub_c_custkey") AS "ub_c_custkey", min(F0."lb_c_custkey") AS "lb_c_custkey", max(F0."ub_c_nationkey") AS "ub_c_nationkey", min(F0."lb_c_nationkey") AS "lb_c_nationkey", sum(0) AS "cet_r", sum(0) AS "bst_r", sum(F0."bst_r") AS "pos_r"
FROM "customer_radb" AS F0
GROUP BY (CASE  WHEN (F0."c_custkey" >= 7500) THEN 7500 WHEN ((F0."c_custkey" < 7500) AND (F0."c_custkey" >= 1)) THEN 1 ELSE 1 END)) F1 ON (((F0."lb_o_custkey" <= F1."ub_c_custkey") AND (F0."ub_o_custkey" >= F1."lb_c_custkey"))))) F0 JOIN (
SELECT (CASE  WHEN (F0."s_suppkey" >= 500) THEN 500 WHEN ((F0."s_suppkey" < 500) AND (F0."s_suppkey" >= 1)) THEN 1 ELSE 1 END) AS "s_suppkey", min(F0."s_nationkey") AS "s_nationkey", max(F0."ub_s_suppkey") AS "ub_s_suppkey", min(F0."lb_s_suppkey") AS "lb_s_suppkey", max(F0."ub_s_nationkey") AS "ub_s_nationkey", min(F0."lb_s_nationkey") AS "lb_s_nationkey", sum(0) AS "cet_r", sum(0) AS "bst_r", sum(F0."bst_r") AS "pos_r"
FROM "supplier_radb" AS F0
GROUP BY (CASE  WHEN (F0."s_suppkey" >= 500) THEN 500 WHEN ((F0."s_suppkey" < 500) AND (F0."s_suppkey" >= 1)) THEN 1 ELSE 1 END)) F1 ON (((F0."lb_l_suppkey" <= F1."ub_s_suppkey") AND (F0."ub_l_suppkey" >= F1."lb_s_suppkey"))))) F0
WHERE ((F0."lb_c_nationkey" <= F0."ub_s_nationkey") AND (F0."ub_c_nationkey" >= F0."lb_s_nationkey"))) F1 ON (((F0."lb_n_nationkey" <= F1."ub_s_nationkey") AND (F0."ub_n_nationkey" >= F1."lb_s_nationkey"))))) F1 ON (((F0."ub_agg_gb_arg1" >= F1."lb_agg_gb_arg1") AND (F1."ub_agg_gb_arg1" >= F0."lb_agg_gb_arg1"))))
GROUP BY F0."AGG_GB_ARG1", F0."ub_agg_gb_arg1", F0."lb_agg_gb_arg1";