SELECT F0."supp_nation" AS "supp_nation", F0."cust_nation" AS "cust_nation", F0."l_year" AS "l_year", min(F0."volume") AS "revenue", F0."ub_supp_nation" AS "ub_supp_nation", F0."lb_supp_nation" AS "lb_supp_nation", F0."ub_cust_nation" AS "ub_cust_nation", F0."lb_cust_nation" AS "lb_cust_nation", F0."ub_l_year" AS "ub_l_year", F0."lb_l_year" AS "lb_l_year", sum((F1."ub_volume" * (CASE  WHEN (F1."ub_volume" > 0) THEN F1."pos_r" ELSE 0 END))) AS "ub_revenue", sum((F1."lb_volume" * (CASE  WHEN (F1."lb_volume" > 0) THEN 0 ELSE F1."pos_r" END))) AS "lb_revenue", max((CASE  WHEN (F0."cet_r" > 0) THEN 1 ELSE 0 END)) AS "cet_r", max((CASE  WHEN (F0."bst_r" > 0) THEN 1 ELSE 0 END)) AS "bst_r", sum(F1."pos_r") AS "pos_r"
FROM ((
SELECT max(F0."ub_name1") AS "ub_supp_nation", min(F0."lb_name1") AS "lb_supp_nation", max(F0."ub_name2") AS "ub_cust_nation", min(F0."lb_name2") AS "lb_cust_nation", max(date_part('year', F0."ub_l_shipdate")) AS "ub_l_year", min(date_part('year', F0."lb_l_shipdate")) AS "lb_l_year", sum(((F0."l_extendedprice" * (1 - F0."l_discount")) * (CASE  WHEN (((F0."name1" = 'FRANCE') and (F0."name2" = 'GERMANY')) or ((F0."name1" = 'GERMANY') and (F0."name2" = 'FRANCE'))) THEN 1 ELSE 0 END))) AS "volume", max(((CASE  WHEN (((F0."ub_name1" = F0."lb_name1") AND (F0."ub_name2" = F0."lb_name2")) AND (date_part('year', F0."ub_l_shipdate") = date_part('year', F0."lb_l_shipdate"))) THEN 1 ELSE 0 END) * (CASE  WHEN ((((F0."name1" = 'FRANCE') AND ((F0."ub_name1" = F0."lb_name1") AND ('FRANCE' = 'FRANCE'))) AND ((F0."name2" = 'GERMANY') AND ((F0."ub_name2" = F0."lb_name2") AND ('GERMANY' = 'GERMANY')))) OR (((F0."name1" = 'GERMANY') AND ((F0."ub_name1" = F0."lb_name1") AND ('GERMANY' = 'GERMANY'))) AND ((F0."name2" = 'FRANCE') AND ((F0."ub_name2" = F0."lb_name2") AND ('FRANCE' = 'FRANCE'))))) THEN 1 ELSE 0 END))) AS "cet_r", max((CASE  WHEN (((F0."name1" = 'FRANCE') and (F0."name2" = 'GERMANY')) or ((F0."name1" = 'GERMANY') and (F0."name2" = 'FRANCE'))) THEN 1 ELSE 0 END)) AS "bst_r", F0."name1" AS "supp_nation", F0."name2" AS "cust_nation", date_part('year', F0."l_shipdate") AS "l_year"
FROM (
SELECT F0."nk1" AS "nk1", F0."name1" AS "name1", F0."s_nationkey" AS "s_nationkey", F0."s_suppkey" AS "s_suppkey", F0."l_shipdate" AS "l_shipdate", F0."l_extendedprice" AS "l_extendedprice", F0."l_discount" AS "l_discount", F0."l_suppkey" AS "l_suppkey", F0."l_orderkey" AS "l_orderkey", F0."o_orderkey" AS "o_orderkey", F0."o_custkey" AS "o_custkey", F0."c_custkey" AS "c_custkey", F0."c_nationkey" AS "c_nationkey", F1."nk2" AS "nk2", F1."name2" AS "name2", F0."ub_nk1" AS "ub_nk1", F0."lb_nk1" AS "lb_nk1", F0."ub_name1" AS "ub_name1", F0."lb_name1" AS "lb_name1", F0."ub_s_nationkey" AS "ub_s_nationkey", F0."lb_s_nationkey" AS "lb_s_nationkey", F0."ub_s_suppkey" AS "ub_s_suppkey", F0."lb_s_suppkey" AS "lb_s_suppkey", F0."ub_l_shipdate" AS "ub_l_shipdate", F0."lb_l_shipdate" AS "lb_l_shipdate", F0."ub_l_extendedprice" AS "ub_l_extendedprice", F0."lb_l_extendedprice" AS "lb_l_extendedprice", F0."ub_l_discount" AS "ub_l_discount", F0."lb_l_discount" AS "lb_l_discount", F0."ub_l_suppkey" AS "ub_l_suppkey", F0."lb_l_suppkey" AS "lb_l_suppkey", F0."ub_l_orderkey" AS "ub_l_orderkey", F0."lb_l_orderkey" AS "lb_l_orderkey", F0."ub_o_orderkey" AS "ub_o_orderkey", F0."lb_o_orderkey" AS "lb_o_orderkey", F0."ub_o_custkey" AS "ub_o_custkey", F0."lb_o_custkey" AS "lb_o_custkey", F0."ub_c_custkey" AS "ub_c_custkey", F0."lb_c_custkey" AS "lb_c_custkey", F0."ub_c_nationkey" AS "ub_c_nationkey", F0."lb_c_nationkey" AS "lb_c_nationkey", F1."ub_nk2" AS "ub_nk2", F1."lb_nk2" AS "lb_nk2", F1."ub_name2" AS "ub_name2", F1."lb_name2" AS "lb_name2", (F0."cet_r" * F1."cet_r") AS "cet_r", (F0."bst_r" * F1."bst_r") AS "bst_r", (F0."pos_r" * F1."pos_r") AS "pos_r"
FROM ((
SELECT F0."nk1" AS "nk1", F0."name1" AS "name1", F0."s_nationkey" AS "s_nationkey", F0."s_suppkey" AS "s_suppkey", F0."l_shipdate" AS "l_shipdate", F0."l_extendedprice" AS "l_extendedprice", F0."l_discount" AS "l_discount", F0."l_suppkey" AS "l_suppkey", F0."l_orderkey" AS "l_orderkey", F0."o_orderkey" AS "o_orderkey", F0."o_custkey" AS "o_custkey", F1."c_custkey" AS "c_custkey", F1."c_nationkey" AS "c_nationkey", F0."ub_nk1" AS "ub_nk1", F0."lb_nk1" AS "lb_nk1", F0."ub_name1" AS "ub_name1", F0."lb_name1" AS "lb_name1", F0."ub_s_nationkey" AS "ub_s_nationkey", F0."lb_s_nationkey" AS "lb_s_nationkey", F0."ub_s_suppkey" AS "ub_s_suppkey", F0."lb_s_suppkey" AS "lb_s_suppkey", F0."ub_l_shipdate" AS "ub_l_shipdate", F0."lb_l_shipdate" AS "lb_l_shipdate", F0."ub_l_extendedprice" AS "ub_l_extendedprice", F0."lb_l_extendedprice" AS "lb_l_extendedprice", F0."ub_l_discount" AS "ub_l_discount", F0."lb_l_discount" AS "lb_l_discount", F0."ub_l_suppkey" AS "ub_l_suppkey", F0."lb_l_suppkey" AS "lb_l_suppkey", F0."ub_l_orderkey" AS "ub_l_orderkey", F0."lb_l_orderkey" AS "lb_l_orderkey", F0."ub_o_orderkey" AS "ub_o_orderkey", F0."lb_o_orderkey" AS "lb_o_orderkey", F0."ub_o_custkey" AS "ub_o_custkey", F0."lb_o_custkey" AS "lb_o_custkey", F1."ub_c_custkey" AS "ub_c_custkey", F1."lb_c_custkey" AS "lb_c_custkey", F1."ub_c_nationkey" AS "ub_c_nationkey", F1."lb_c_nationkey" AS "lb_c_nationkey", (F0."cet_r" * F1."cet_r") AS "cet_r", (F0."bst_r" * F1."bst_r") AS "bst_r", (F0."pos_r" * F1."pos_r") AS "pos_r"
FROM ((
SELECT F0."nk1" AS "nk1", F0."name1" AS "name1", F0."s_nationkey" AS "s_nationkey", F0."s_suppkey" AS "s_suppkey", F0."l_shipdate" AS "l_shipdate", F0."l_extendedprice" AS "l_extendedprice", F0."l_discount" AS "l_discount", F0."l_suppkey" AS "l_suppkey", F0."l_orderkey" AS "l_orderkey", F1."o_orderkey" AS "o_orderkey", F1."o_custkey" AS "o_custkey", F0."ub_nk1" AS "ub_nk1", F0."lb_nk1" AS "lb_nk1", F0."ub_name1" AS "ub_name1", F0."lb_name1" AS "lb_name1", F0."ub_s_nationkey" AS "ub_s_nationkey", F0."lb_s_nationkey" AS "lb_s_nationkey", F0."ub_s_suppkey" AS "ub_s_suppkey", F0."lb_s_suppkey" AS "lb_s_suppkey", F0."ub_l_shipdate" AS "ub_l_shipdate", F0."lb_l_shipdate" AS "lb_l_shipdate", F0."ub_l_extendedprice" AS "ub_l_extendedprice", F0."lb_l_extendedprice" AS "lb_l_extendedprice", F0."ub_l_discount" AS "ub_l_discount", F0."lb_l_discount" AS "lb_l_discount", F0."ub_l_suppkey" AS "ub_l_suppkey", F0."lb_l_suppkey" AS "lb_l_suppkey", F0."ub_l_orderkey" AS "ub_l_orderkey", F0."lb_l_orderkey" AS "lb_l_orderkey", F1."ub_o_orderkey" AS "ub_o_orderkey", F1."lb_o_orderkey" AS "lb_o_orderkey", F1."ub_o_custkey" AS "ub_o_custkey", F1."lb_o_custkey" AS "lb_o_custkey", (F0."cet_r" * F1."cet_r") AS "cet_r", (F0."bst_r" * F1."bst_r") AS "bst_r", (F0."pos_r" * F1."pos_r") AS "pos_r"
FROM ((
SELECT F0."nk1" AS "nk1", F0."name1" AS "name1", F0."s_nationkey" AS "s_nationkey", F0."s_suppkey" AS "s_suppkey", F1."l_shipdate" AS "l_shipdate", F1."l_extendedprice" AS "l_extendedprice", F1."l_discount" AS "l_discount", F1."l_suppkey" AS "l_suppkey", F1."l_orderkey" AS "l_orderkey", F0."ub_nk1" AS "ub_nk1", F0."lb_nk1" AS "lb_nk1", F0."ub_name1" AS "ub_name1", F0."lb_name1" AS "lb_name1", F0."ub_s_nationkey" AS "ub_s_nationkey", F0."lb_s_nationkey" AS "lb_s_nationkey", F0."ub_s_suppkey" AS "ub_s_suppkey", F0."lb_s_suppkey" AS "lb_s_suppkey", F1."ub_l_shipdate" AS "ub_l_shipdate", F1."lb_l_shipdate" AS "lb_l_shipdate", F1."ub_l_extendedprice" AS "ub_l_extendedprice", F1."lb_l_extendedprice" AS "lb_l_extendedprice", F1."ub_l_discount" AS "ub_l_discount", F1."lb_l_discount" AS "lb_l_discount", F1."ub_l_suppkey" AS "ub_l_suppkey", F1."lb_l_suppkey" AS "lb_l_suppkey", F1."ub_l_orderkey" AS "ub_l_orderkey", F1."lb_l_orderkey" AS "lb_l_orderkey", (F0."cet_r" * F1."cet_r") AS "cet_r", (F0."bst_r" * F1."bst_r") AS "bst_r", (F0."pos_r" * F1."pos_r") AS "pos_r"
FROM ((
SELECT F0."nk1" AS "nk1", F0."name1" AS "name1", F1."s_nationkey" AS "s_nationkey", F1."s_suppkey" AS "s_suppkey", F0."ub_nk1" AS "ub_nk1", F0."lb_nk1" AS "lb_nk1", F0."ub_name1" AS "ub_name1", F0."lb_name1" AS "lb_name1", F1."ub_s_nationkey" AS "ub_s_nationkey", F1."lb_s_nationkey" AS "lb_s_nationkey", F1."ub_s_suppkey" AS "ub_s_suppkey", F1."lb_s_suppkey" AS "lb_s_suppkey", (F0."cet_r" * F1."cet_r") AS "cet_r", (F0."bst_r" * F1."bst_r") AS "bst_r", (F0."pos_r" * F1."pos_r") AS "pos_r"
FROM ((
SELECT F0."nk1" AS "nk1", F0."name1" AS "name1", F0."nk1" AS "ub_nk1", F0."nk1" AS "lb_nk1", F0."name1" AS "ub_name1", F0."name1" AS "lb_name1", (CASE  WHEN ((F0."ub_nk1" = F0."lb_nk1") AND (F0."ub_name1" = F0."lb_name1")) THEN F0."cet_r" ELSE 0 END) AS "cet_r", F0."bst_r" AS "bst_r", F0."bst_r" AS "pos_r"
FROM (
SELECT F0."n_nationkey" AS "nk1", F0."n_name" AS "name1", F0."ub_n_nationkey" AS "ub_nk1", F0."lb_n_nationkey" AS "lb_nk1", F0."ub_n_name" AS "ub_name1", F0."lb_n_name" AS "lb_name1", F0."cet_r" AS "cet_r", F0."bst_r" AS "bst_r", F0."pos_r" AS "pos_r"
FROM "nation_radb" AS F0) F0
WHERE (F0."bst_r" > 0)) F0 JOIN (
SELECT F0."s_nationkey" AS "s_nationkey", F0."s_suppkey" AS "s_suppkey", F0."s_nationkey" AS "ub_s_nationkey", F0."s_nationkey" AS "lb_s_nationkey", F0."s_suppkey" AS "ub_s_suppkey", F0."s_suppkey" AS "lb_s_suppkey", (CASE  WHEN ((F0."ub_s_nationkey" = F0."lb_s_nationkey") AND (F0."ub_s_suppkey" = F0."lb_s_suppkey")) THEN F0."cet_r" ELSE 0 END) AS "cet_r", F0."bst_r" AS "bst_r", F0."bst_r" AS "pos_r"
FROM (
SELECT F0."s_nationkey" AS "s_nationkey", F0."s_suppkey" AS "s_suppkey", F0."ub_s_nationkey" AS "ub_s_nationkey", F0."lb_s_nationkey" AS "lb_s_nationkey", F0."ub_s_suppkey" AS "ub_s_suppkey", F0."lb_s_suppkey" AS "lb_s_suppkey", F0."cet_r" AS "cet_r", F0."bst_r" AS "bst_r", F0."pos_r" AS "pos_r"
FROM "supplier_radb" AS F0) F0
WHERE (F0."bst_r" > 0)) F1 ON ((F0."nk1" = F1."s_nationkey")))) F0 JOIN (
SELECT F0."l_shipdate" AS "l_shipdate", F0."l_extendedprice" AS "l_extendedprice", F0."l_discount" AS "l_discount", F0."l_suppkey" AS "l_suppkey", F0."l_orderkey" AS "l_orderkey", F0."l_shipdate" AS "ub_l_shipdate", F0."l_shipdate" AS "lb_l_shipdate", F0."l_extendedprice" AS "ub_l_extendedprice", F0."l_extendedprice" AS "lb_l_extendedprice", F0."l_discount" AS "ub_l_discount", F0."l_discount" AS "lb_l_discount", F0."l_suppkey" AS "ub_l_suppkey", F0."l_suppkey" AS "lb_l_suppkey", F0."l_orderkey" AS "ub_l_orderkey", F0."l_orderkey" AS "lb_l_orderkey", (CASE  WHEN (((((F0."ub_l_shipdate" = F0."lb_l_shipdate") AND (F0."ub_l_extendedprice" = F0."lb_l_extendedprice")) AND (F0."ub_l_discount" = F0."lb_l_discount")) AND (F0."ub_l_suppkey" = F0."lb_l_suppkey")) AND (F0."ub_l_orderkey" = F0."lb_l_orderkey")) THEN F0."cet_r" ELSE 0 END) AS "cet_r", F0."bst_r" AS "bst_r", F0."bst_r" AS "pos_r"
FROM (
SELECT F0."l_shipdate" AS "l_shipdate", F0."l_extendedprice" AS "l_extendedprice", F0."l_discount" AS "l_discount", F0."l_suppkey" AS "l_suppkey", F0."l_orderkey" AS "l_orderkey", F0."ub_l_shipdate" AS "ub_l_shipdate", F0."lb_l_shipdate" AS "lb_l_shipdate", F0."ub_l_extendedprice" AS "ub_l_extendedprice", F0."lb_l_extendedprice" AS "lb_l_extendedprice", F0."ub_l_discount" AS "ub_l_discount", F0."lb_l_discount" AS "lb_l_discount", F0."ub_l_suppkey" AS "ub_l_suppkey", F0."lb_l_suppkey" AS "lb_l_suppkey", F0."ub_l_orderkey" AS "ub_l_orderkey", F0."lb_l_orderkey" AS "lb_l_orderkey", (CASE  WHEN ((F0."lb_l_shipdate" > '1995-01-01') AND (F0."ub_l_shipdate" < '1996-12-31')) THEN 1 ELSE 0 END) AS "cet_r", (CASE  WHEN ((F0."l_shipdate" > '1995-01-01') and (F0."l_shipdate" < '1996-12-31')) THEN 1 ELSE 0 END) AS "bst_r", F0."pos_r" AS "pos_r"
FROM (
SELECT F0."tid" AS "tid", F0."l_orderkey" AS "l_orderkey", F0."l_partkey" AS "l_partkey", F0."l_suppkey" AS "l_suppkey", F0."l_linenumber" AS "l_linenumber", F0."l_quantity" AS "l_quantity", F0."l_extendedprice" AS "l_extendedprice", F0."l_discount" AS "l_discount", F0."l_tax" AS "l_tax", F0."l_returnflag" AS "l_returnflag", F0."l_linestatus" AS "l_linestatus", F0."l_shipdate" AS "l_shipdate", F0."l_commitdate" AS "l_commitdate", F0."l_receiptdate" AS "l_receiptdate", F0."l_shipinstruct" AS "l_shipinstruct", F0."l_shipmode" AS "l_shipmode", F0."l_comment" AS "l_comment", F0."ub_tid" AS "ub_tid", F0."lb_tid" AS "lb_tid", F0."ub_l_orderkey" AS "ub_l_orderkey", F0."lb_l_orderkey" AS "lb_l_orderkey", F0."ub_l_partkey" AS "ub_l_partkey", F0."lb_l_partkey" AS "lb_l_partkey", F0."ub_l_suppkey" AS "ub_l_suppkey", F0."lb_l_suppkey" AS "lb_l_suppkey", F0."ub_l_linenumber" AS "ub_l_linenumber", F0."lb_l_linenumber" AS "lb_l_linenumber", F0."ub_l_quantity" AS "ub_l_quantity", F0."lb_l_quantity" AS "lb_l_quantity", F0."ub_l_extendedprice" AS "ub_l_extendedprice", F0."lb_l_extendedprice" AS "lb_l_extendedprice", F0."ub_l_discount" AS "ub_l_discount", F0."lb_l_discount" AS "lb_l_discount", F0."ub_l_tax" AS "ub_l_tax", F0."lb_l_tax" AS "lb_l_tax", F0."ub_l_returnflag" AS "ub_l_returnflag", F0."lb_l_returnflag" AS "lb_l_returnflag", F0."ub_l_linestatus" AS "ub_l_linestatus", F0."lb_l_linestatus" AS "lb_l_linestatus", F0."ub_l_shipdate" AS "ub_l_shipdate", F0."lb_l_shipdate" AS "lb_l_shipdate", F0."ub_l_commitdate" AS "ub_l_commitdate", F0."lb_l_commitdate" AS "lb_l_commitdate", F0."ub_l_receiptdate" AS "ub_l_receiptdate", F0."lb_l_receiptdate" AS "lb_l_receiptdate", F0."ub_l_shipinstruct" AS "ub_l_shipinstruct", F0."lb_l_shipinstruct" AS "lb_l_shipinstruct", F0."ub_l_shipmode" AS "ub_l_shipmode", F0."lb_l_shipmode" AS "lb_l_shipmode", F0."ub_l_comment" AS "ub_l_comment", F0."lb_l_comment" AS "lb_l_comment", F0."cet_r" AS "cet_r", F0."bst_r" AS "bst_r", F0."pos_r" AS "pos_r"
FROM "lineitem_radb" AS F0) F0
WHERE ((F0."ub_l_shipdate" > '1995-01-01') AND (F0."lb_l_shipdate" < '1996-12-31'))) F0
WHERE (F0."bst_r" > 0)) F1 ON ((F0."s_suppkey" = F1."l_suppkey")))) F0 JOIN (
SELECT F0."o_orderkey" AS "o_orderkey", F0."o_custkey" AS "o_custkey", F0."o_orderkey" AS "ub_o_orderkey", F0."o_orderkey" AS "lb_o_orderkey", F0."o_custkey" AS "ub_o_custkey", F0."o_custkey" AS "lb_o_custkey", (CASE  WHEN ((F0."ub_o_orderkey" = F0."lb_o_orderkey") AND (F0."ub_o_custkey" = F0."lb_o_custkey")) THEN F0."cet_r" ELSE 0 END) AS "cet_r", F0."bst_r" AS "bst_r", F0."bst_r" AS "pos_r"
FROM (
SELECT F0."o_orderkey" AS "o_orderkey", F0."o_custkey" AS "o_custkey", F0."ub_o_orderkey" AS "ub_o_orderkey", F0."lb_o_orderkey" AS "lb_o_orderkey", F0."ub_o_custkey" AS "ub_o_custkey", F0."lb_o_custkey" AS "lb_o_custkey", F0."cet_r" AS "cet_r", F0."bst_r" AS "bst_r", F0."pos_r" AS "pos_r"
FROM "orders_radb" AS F0) F0
WHERE (F0."bst_r" > 0)) F1 ON ((F0."l_orderkey" = F1."o_orderkey")))) F0 JOIN (
SELECT F0."c_custkey" AS "c_custkey", F0."c_nationkey" AS "c_nationkey", F0."c_custkey" AS "ub_c_custkey", F0."c_custkey" AS "lb_c_custkey", F0."c_nationkey" AS "ub_c_nationkey", F0."c_nationkey" AS "lb_c_nationkey", (CASE  WHEN ((F0."ub_c_custkey" = F0."lb_c_custkey") AND (F0."ub_c_nationkey" = F0."lb_c_nationkey")) THEN F0."cet_r" ELSE 0 END) AS "cet_r", F0."bst_r" AS "bst_r", F0."bst_r" AS "pos_r"
FROM (
SELECT F0."c_custkey" AS "c_custkey", F0."c_nationkey" AS "c_nationkey", F0."ub_c_custkey" AS "ub_c_custkey", F0."lb_c_custkey" AS "lb_c_custkey", F0."ub_c_nationkey" AS "ub_c_nationkey", F0."lb_c_nationkey" AS "lb_c_nationkey", F0."cet_r" AS "cet_r", F0."bst_r" AS "bst_r", F0."pos_r" AS "pos_r"
FROM "customer_radb" AS F0) F0
WHERE (F0."bst_r" > 0)) F1 ON ((F0."o_custkey" = F1."c_custkey")))) F0 JOIN (
SELECT F0."nk2" AS "nk2", F0."name2" AS "name2", F0."nk2" AS "ub_nk2", F0."nk2" AS "lb_nk2", F0."name2" AS "ub_name2", F0."name2" AS "lb_name2", (CASE  WHEN ((F0."ub_nk2" = F0."lb_nk2") AND (F0."ub_name2" = F0."lb_name2")) THEN F0."cet_r" ELSE 0 END) AS "cet_r", F0."bst_r" AS "bst_r", F0."bst_r" AS "pos_r"
FROM (
SELECT F0."n_nationkey" AS "nk2", F0."n_name" AS "name2", F0."ub_n_nationkey" AS "ub_nk2", F0."lb_n_nationkey" AS "lb_nk2", F0."ub_n_name" AS "ub_name2", F0."lb_n_name" AS "lb_name2", F0."cet_r" AS "cet_r", F0."bst_r" AS "bst_r", F0."pos_r" AS "pos_r"
FROM "nation_radb" AS F0) F0
WHERE (F0."bst_r" > 0)) F1 ON ((F0."c_nationkey" = F1."nk2")))) F0
WHERE ((((F0."lb_name1" <= 'FRANCE') AND (F0."ub_name1" >= 'FRANCE')) AND ((F0."lb_name2" <= 'GERMANY') AND (F0."ub_name2" >= 'GERMANY'))) OR (((F0."lb_name1" <= 'GERMANY') AND (F0."ub_name1" >= 'GERMANY')) AND ((F0."lb_name2" <= 'FRANCE') AND (F0."ub_name2" >= 'FRANCE'))))
GROUP BY F0."name1", F0."name2", date_part('year', F0."l_shipdate")) F0 JOIN (
SELECT F0."name1" AS "supp_nation", F0."name2" AS "cust_nation", date_part('year', F0."l_shipdate") AS "l_year", (F0."l_extendedprice" * (1 - F0."l_discount")) AS "volume", F0."ub_name1" AS "ub_supp_nation", F0."lb_name1" AS "lb_supp_nation", F0."ub_name2" AS "ub_cust_nation", F0."lb_name2" AS "lb_cust_nation", date_part('year', F0."ub_l_shipdate") AS "ub_l_year", date_part('year', F0."lb_l_shipdate") AS "lb_l_year", greatest(greatest((F0."ub_l_extendedprice" * (1 - F0."lb_l_discount")), (F0."ub_l_extendedprice" * (1 - F0."ub_l_discount"))), greatest((F0."lb_l_extendedprice" * (1 - F0."lb_l_discount")), (F0."lb_l_extendedprice" * (1 - F0."ub_l_discount")))) AS "ub_volume", least(least((F0."ub_l_extendedprice" * (1 - F0."lb_l_discount")), (F0."ub_l_extendedprice" * (1 - F0."ub_l_discount"))), least((F0."lb_l_extendedprice" * (1 - F0."lb_l_discount")), (F0."lb_l_extendedprice" * (1 - F0."ub_l_discount")))) AS "lb_volume", (CASE  WHEN ((((F0."name1" = 'FRANCE') AND ((F0."ub_name1" = F0."lb_name1") AND ('FRANCE' = 'FRANCE'))) AND ((F0."name2" = 'GERMANY') AND ((F0."ub_name2" = F0."lb_name2") AND ('GERMANY' = 'GERMANY')))) OR (((F0."name1" = 'GERMANY') AND ((F0."ub_name1" = F0."lb_name1") AND ('GERMANY' = 'GERMANY'))) AND ((F0."name2" = 'FRANCE') AND ((F0."ub_name2" = F0."lb_name2") AND ('FRANCE' = 'FRANCE'))))) THEN 1 ELSE 0 END) AS "cet_r", (CASE  WHEN (((F0."name1" = 'FRANCE') and (F0."name2" = 'GERMANY')) or ((F0."name1" = 'GERMANY') and (F0."name2" = 'FRANCE'))) THEN 1 ELSE 0 END) AS "bst_r", F0."pos_r" AS "pos_r"
FROM (
SELECT F0."nk1" AS "nk1", F0."name1" AS "name1", F0."s_nationkey" AS "s_nationkey", F0."s_suppkey" AS "s_suppkey", F0."l_shipdate" AS "l_shipdate", F0."l_extendedprice" AS "l_extendedprice", F0."l_discount" AS "l_discount", F0."l_suppkey" AS "l_suppkey", F0."l_orderkey" AS "l_orderkey", F0."o_orderkey" AS "o_orderkey", F0."o_custkey" AS "o_custkey", F0."c_custkey" AS "c_custkey", F0."c_nationkey" AS "c_nationkey", F1."nk2" AS "nk2", F1."name2" AS "name2", F0."ub_nk1" AS "ub_nk1", F0."lb_nk1" AS "lb_nk1", F0."ub_name1" AS "ub_name1", F0."lb_name1" AS "lb_name1", F0."ub_s_nationkey" AS "ub_s_nationkey", F0."lb_s_nationkey" AS "lb_s_nationkey", F0."ub_s_suppkey" AS "ub_s_suppkey", F0."lb_s_suppkey" AS "lb_s_suppkey", F0."ub_l_shipdate" AS "ub_l_shipdate", F0."lb_l_shipdate" AS "lb_l_shipdate", F0."ub_l_extendedprice" AS "ub_l_extendedprice", F0."lb_l_extendedprice" AS "lb_l_extendedprice", F0."ub_l_discount" AS "ub_l_discount", F0."lb_l_discount" AS "lb_l_discount", F0."ub_l_suppkey" AS "ub_l_suppkey", F0."lb_l_suppkey" AS "lb_l_suppkey", F0."ub_l_orderkey" AS "ub_l_orderkey", F0."lb_l_orderkey" AS "lb_l_orderkey", F0."ub_o_orderkey" AS "ub_o_orderkey", F0."lb_o_orderkey" AS "lb_o_orderkey", F0."ub_o_custkey" AS "ub_o_custkey", F0."lb_o_custkey" AS "lb_o_custkey", F0."ub_c_custkey" AS "ub_c_custkey", F0."lb_c_custkey" AS "lb_c_custkey", F0."ub_c_nationkey" AS "ub_c_nationkey", F0."lb_c_nationkey" AS "lb_c_nationkey", F1."ub_nk2" AS "ub_nk2", F1."lb_nk2" AS "lb_nk2", F1."ub_name2" AS "ub_name2", F1."lb_name2" AS "lb_name2", ((F0."cet_r" + F1."cet_r") + (CASE  WHEN ((F0."c_nationkey" = F1."nk2") AND ((F0."ub_c_nationkey" = F0."lb_c_nationkey") AND (F1."ub_nk2" = F1."lb_nk2"))) THEN 1 ELSE 0 END)) AS "cet_r", ((F0."bst_r" + F1."bst_r") + (CASE  WHEN (F0."c_nationkey" = F1."nk2") THEN 1 ELSE 0 END)) AS "bst_r", (F0."pos_r" + F1."pos_r") AS "pos_r"
FROM ((
SELECT F0."nk1" AS "nk1", F0."name1" AS "name1", F0."s_nationkey" AS "s_nationkey", F0."s_suppkey" AS "s_suppkey", F0."l_shipdate" AS "l_shipdate", F0."l_extendedprice" AS "l_extendedprice", F0."l_discount" AS "l_discount", F0."l_suppkey" AS "l_suppkey", F0."l_orderkey" AS "l_orderkey", F0."o_orderkey" AS "o_orderkey", F0."o_custkey" AS "o_custkey", F1."c_custkey" AS "c_custkey", F1."c_nationkey" AS "c_nationkey", F0."ub_nk1" AS "ub_nk1", F0."lb_nk1" AS "lb_nk1", F0."ub_name1" AS "ub_name1", F0."lb_name1" AS "lb_name1", F0."ub_s_nationkey" AS "ub_s_nationkey", F0."lb_s_nationkey" AS "lb_s_nationkey", F0."ub_s_suppkey" AS "ub_s_suppkey", F0."lb_s_suppkey" AS "lb_s_suppkey", F0."ub_l_shipdate" AS "ub_l_shipdate", F0."lb_l_shipdate" AS "lb_l_shipdate", F0."ub_l_extendedprice" AS "ub_l_extendedprice", F0."lb_l_extendedprice" AS "lb_l_extendedprice", F0."ub_l_discount" AS "ub_l_discount", F0."lb_l_discount" AS "lb_l_discount", F0."ub_l_suppkey" AS "ub_l_suppkey", F0."lb_l_suppkey" AS "lb_l_suppkey", F0."ub_l_orderkey" AS "ub_l_orderkey", F0."lb_l_orderkey" AS "lb_l_orderkey", F0."ub_o_orderkey" AS "ub_o_orderkey", F0."lb_o_orderkey" AS "lb_o_orderkey", F0."ub_o_custkey" AS "ub_o_custkey", F0."lb_o_custkey" AS "lb_o_custkey", F1."ub_c_custkey" AS "ub_c_custkey", F1."lb_c_custkey" AS "lb_c_custkey", F1."ub_c_nationkey" AS "ub_c_nationkey", F1."lb_c_nationkey" AS "lb_c_nationkey", ((F0."cet_r" + F1."cet_r") + (CASE  WHEN ((F0."o_custkey" = F1."c_custkey") AND ((F0."ub_o_custkey" = F0."lb_o_custkey") AND (F1."ub_c_custkey" = F1."lb_c_custkey"))) THEN 1 ELSE 0 END)) AS "cet_r", ((F0."bst_r" + F1."bst_r") + (CASE  WHEN (F0."o_custkey" = F1."c_custkey") THEN 1 ELSE 0 END)) AS "bst_r", (F0."pos_r" + F1."pos_r") AS "pos_r"
FROM ((
SELECT F0."nk1" AS "nk1", F0."name1" AS "name1", F0."s_nationkey" AS "s_nationkey", F0."s_suppkey" AS "s_suppkey", F0."l_shipdate" AS "l_shipdate", F0."l_extendedprice" AS "l_extendedprice", F0."l_discount" AS "l_discount", F0."l_suppkey" AS "l_suppkey", F0."l_orderkey" AS "l_orderkey", F1."o_orderkey" AS "o_orderkey", F1."o_custkey" AS "o_custkey", F0."ub_nk1" AS "ub_nk1", F0."lb_nk1" AS "lb_nk1", F0."ub_name1" AS "ub_name1", F0."lb_name1" AS "lb_name1", F0."ub_s_nationkey" AS "ub_s_nationkey", F0."lb_s_nationkey" AS "lb_s_nationkey", F0."ub_s_suppkey" AS "ub_s_suppkey", F0."lb_s_suppkey" AS "lb_s_suppkey", F0."ub_l_shipdate" AS "ub_l_shipdate", F0."lb_l_shipdate" AS "lb_l_shipdate", F0."ub_l_extendedprice" AS "ub_l_extendedprice", F0."lb_l_extendedprice" AS "lb_l_extendedprice", F0."ub_l_discount" AS "ub_l_discount", F0."lb_l_discount" AS "lb_l_discount", F0."ub_l_suppkey" AS "ub_l_suppkey", F0."lb_l_suppkey" AS "lb_l_suppkey", F0."ub_l_orderkey" AS "ub_l_orderkey", F0."lb_l_orderkey" AS "lb_l_orderkey", F1."ub_o_orderkey" AS "ub_o_orderkey", F1."lb_o_orderkey" AS "lb_o_orderkey", F1."ub_o_custkey" AS "ub_o_custkey", F1."lb_o_custkey" AS "lb_o_custkey", ((F0."cet_r" + F1."cet_r") + (CASE  WHEN ((F0."l_orderkey" = F1."o_orderkey") AND ((F0."ub_l_orderkey" = F0."lb_l_orderkey") AND (F1."ub_o_orderkey" = F1."lb_o_orderkey"))) THEN 1 ELSE 0 END)) AS "cet_r", ((F0."bst_r" + F1."bst_r") + (CASE  WHEN (F0."l_orderkey" = F1."o_orderkey") THEN 1 ELSE 0 END)) AS "bst_r", (F0."pos_r" + F1."pos_r") AS "pos_r"
FROM ((
SELECT F0."nk1" AS "nk1", F0."name1" AS "name1", F0."s_nationkey" AS "s_nationkey", F0."s_suppkey" AS "s_suppkey", F1."l_shipdate" AS "l_shipdate", F1."l_extendedprice" AS "l_extendedprice", F1."l_discount" AS "l_discount", F1."l_suppkey" AS "l_suppkey", F1."l_orderkey" AS "l_orderkey", F0."ub_nk1" AS "ub_nk1", F0."lb_nk1" AS "lb_nk1", F0."ub_name1" AS "ub_name1", F0."lb_name1" AS "lb_name1", F0."ub_s_nationkey" AS "ub_s_nationkey", F0."lb_s_nationkey" AS "lb_s_nationkey", F0."ub_s_suppkey" AS "ub_s_suppkey", F0."lb_s_suppkey" AS "lb_s_suppkey", F1."ub_l_shipdate" AS "ub_l_shipdate", F1."lb_l_shipdate" AS "lb_l_shipdate", F1."ub_l_extendedprice" AS "ub_l_extendedprice", F1."lb_l_extendedprice" AS "lb_l_extendedprice", F1."ub_l_discount" AS "ub_l_discount", F1."lb_l_discount" AS "lb_l_discount", F1."ub_l_suppkey" AS "ub_l_suppkey", F1."lb_l_suppkey" AS "lb_l_suppkey", F1."ub_l_orderkey" AS "ub_l_orderkey", F1."lb_l_orderkey" AS "lb_l_orderkey", ((F0."cet_r" + F1."cet_r") + (CASE  WHEN ((F0."s_suppkey" = F1."l_suppkey") AND ((F0."ub_s_suppkey" = F0."lb_s_suppkey") AND (F1."ub_l_suppkey" = F1."lb_l_suppkey"))) THEN 1 ELSE 0 END)) AS "cet_r", ((F0."bst_r" + F1."bst_r") + (CASE  WHEN (F0."s_suppkey" = F1."l_suppkey") THEN 1 ELSE 0 END)) AS "bst_r", (F0."pos_r" + F1."pos_r") AS "pos_r"
FROM ((
SELECT F0."nk1" AS "nk1", F0."name1" AS "name1", F1."s_nationkey" AS "s_nationkey", F1."s_suppkey" AS "s_suppkey", F0."ub_nk1" AS "ub_nk1", F0."lb_nk1" AS "lb_nk1", F0."ub_name1" AS "ub_name1", F0."lb_name1" AS "lb_name1", F1."ub_s_nationkey" AS "ub_s_nationkey", F1."lb_s_nationkey" AS "lb_s_nationkey", F1."ub_s_suppkey" AS "ub_s_suppkey", F1."lb_s_suppkey" AS "lb_s_suppkey", ((F0."cet_r" + F1."cet_r") + (CASE  WHEN ((F0."nk1" = F1."s_nationkey") AND ((F0."ub_nk1" = F0."lb_nk1") AND (F1."ub_s_nationkey" = F1."lb_s_nationkey"))) THEN 1 ELSE 0 END)) AS "cet_r", ((F0."bst_r" + F1."bst_r") + (CASE  WHEN (F0."nk1" = F1."s_nationkey") THEN 1 ELSE 0 END)) AS "bst_r", (F0."pos_r" + F1."pos_r") AS "pos_r"
FROM ((
SELECT (CASE  WHEN (F0."n_nationkey" >= 12) THEN 12 WHEN ((F0."n_nationkey" < 12) AND (F0."n_nationkey" >= 0)) THEN 0 ELSE 0 END) AS "nk1", min(F0."n_name") AS "name1", max(F0."ub_n_nationkey") AS "ub_nk1", min(F0."lb_n_nationkey") AS "lb_nk1", max(F0."ub_n_name") AS "ub_name1", min(F0."lb_n_name") AS "lb_name1", sum(0) AS "cet_r", sum(0) AS "bst_r", sum(F0."bst_r") AS "pos_r"
FROM "nation_radb" AS F0
GROUP BY (CASE  WHEN (F0."n_nationkey" >= 12) THEN 12 WHEN ((F0."n_nationkey" < 12) AND (F0."n_nationkey" >= 0)) THEN 0 ELSE 0 END)) F0 JOIN (
SELECT (CASE  WHEN (F0."s_nationkey" >= 12) THEN 12 WHEN ((F0."s_nationkey" < 12) AND (F0."s_nationkey" >= 0)) THEN 0 ELSE 0 END) AS "s_nationkey", min(F0."s_suppkey") AS "s_suppkey", max(F0."ub_s_nationkey") AS "ub_s_nationkey", min(F0."lb_s_nationkey") AS "lb_s_nationkey", max(F0."ub_s_suppkey") AS "ub_s_suppkey", min(F0."lb_s_suppkey") AS "lb_s_suppkey", sum(0) AS "cet_r", sum(0) AS "bst_r", sum(F0."bst_r") AS "pos_r"
FROM "supplier_radb" AS F0
GROUP BY (CASE  WHEN (F0."s_nationkey" >= 12) THEN 12 WHEN ((F0."s_nationkey" < 12) AND (F0."s_nationkey" >= 0)) THEN 0 ELSE 0 END)) F1 ON (((F0."lb_nk1" <= F1."ub_s_nationkey") AND (F0."ub_nk1" >= F1."lb_s_nationkey"))))) F0 JOIN (
SELECT min(F0."l_shipdate") AS "l_shipdate", min(F0."l_extendedprice") AS "l_extendedprice", min(F0."l_discount") AS "l_discount", (CASE  WHEN (F0."l_suppkey" >= 500) THEN 500 WHEN ((F0."l_suppkey" < 500) AND (F0."l_suppkey" >= 1)) THEN 1 ELSE 1 END) AS "l_suppkey", min(F0."l_orderkey") AS "l_orderkey", max(F0."ub_l_shipdate") AS "ub_l_shipdate", min(F0."lb_l_shipdate") AS "lb_l_shipdate", max(F0."ub_l_extendedprice") AS "ub_l_extendedprice", min(F0."lb_l_extendedprice") AS "lb_l_extendedprice", max(F0."ub_l_discount") AS "ub_l_discount", min(F0."lb_l_discount") AS "lb_l_discount", max(F0."ub_l_suppkey") AS "ub_l_suppkey", min(F0."lb_l_suppkey") AS "lb_l_suppkey", max(F0."ub_l_orderkey") AS "ub_l_orderkey", min(F0."lb_l_orderkey") AS "lb_l_orderkey", sum(0) AS "cet_r", sum(0) AS "bst_r", sum((CASE  WHEN ((F0."l_shipdate" > '1995-01-01') and (F0."l_shipdate" < '1996-12-31')) THEN 1 ELSE 0 END)) AS "pos_r"
FROM (
SELECT F0."tid" AS "tid", F0."l_orderkey" AS "l_orderkey", F0."l_partkey" AS "l_partkey", F0."l_suppkey" AS "l_suppkey", F0."l_linenumber" AS "l_linenumber", F0."l_quantity" AS "l_quantity", F0."l_extendedprice" AS "l_extendedprice", F0."l_discount" AS "l_discount", F0."l_tax" AS "l_tax", F0."l_returnflag" AS "l_returnflag", F0."l_linestatus" AS "l_linestatus", F0."l_shipdate" AS "l_shipdate", F0."l_commitdate" AS "l_commitdate", F0."l_receiptdate" AS "l_receiptdate", F0."l_shipinstruct" AS "l_shipinstruct", F0."l_shipmode" AS "l_shipmode", F0."l_comment" AS "l_comment", F0."ub_tid" AS "ub_tid", F0."lb_tid" AS "lb_tid", F0."ub_l_orderkey" AS "ub_l_orderkey", F0."lb_l_orderkey" AS "lb_l_orderkey", F0."ub_l_partkey" AS "ub_l_partkey", F0."lb_l_partkey" AS "lb_l_partkey", F0."ub_l_suppkey" AS "ub_l_suppkey", F0."lb_l_suppkey" AS "lb_l_suppkey", F0."ub_l_linenumber" AS "ub_l_linenumber", F0."lb_l_linenumber" AS "lb_l_linenumber", F0."ub_l_quantity" AS "ub_l_quantity", F0."lb_l_quantity" AS "lb_l_quantity", F0."ub_l_extendedprice" AS "ub_l_extendedprice", F0."lb_l_extendedprice" AS "lb_l_extendedprice", F0."ub_l_discount" AS "ub_l_discount", F0."lb_l_discount" AS "lb_l_discount", F0."ub_l_tax" AS "ub_l_tax", F0."lb_l_tax" AS "lb_l_tax", F0."ub_l_returnflag" AS "ub_l_returnflag", F0."lb_l_returnflag" AS "lb_l_returnflag", F0."ub_l_linestatus" AS "ub_l_linestatus", F0."lb_l_linestatus" AS "lb_l_linestatus", F0."ub_l_shipdate" AS "ub_l_shipdate", F0."lb_l_shipdate" AS "lb_l_shipdate", F0."ub_l_commitdate" AS "ub_l_commitdate", F0."lb_l_commitdate" AS "lb_l_commitdate", F0."ub_l_receiptdate" AS "ub_l_receiptdate", F0."lb_l_receiptdate" AS "lb_l_receiptdate", F0."ub_l_shipinstruct" AS "ub_l_shipinstruct", F0."lb_l_shipinstruct" AS "lb_l_shipinstruct", F0."ub_l_shipmode" AS "ub_l_shipmode", F0."lb_l_shipmode" AS "lb_l_shipmode", F0."ub_l_comment" AS "ub_l_comment", F0."lb_l_comment" AS "lb_l_comment", F0."cet_r" AS "cet_r", F0."bst_r" AS "bst_r", F0."pos_r" AS "pos_r"
FROM "lineitem_radb" AS F0) F0
WHERE ((F0."ub_l_shipdate" > '1995-01-01') AND (F0."lb_l_shipdate" < '1996-12-31'))
GROUP BY (CASE  WHEN (F0."l_suppkey" >= 500) THEN 500 WHEN ((F0."l_suppkey" < 500) AND (F0."l_suppkey" >= 1)) THEN 1 ELSE 1 END)) F1 ON (((F0."lb_s_suppkey" <= F1."ub_l_suppkey") AND (F0."ub_s_suppkey" >= F1."lb_l_suppkey"))))) F0 JOIN (
SELECT (CASE  WHEN (F0."o_orderkey" >= 300000) THEN 300000 WHEN ((F0."o_orderkey" < 300000) AND (F0."o_orderkey" >= 1)) THEN 1 ELSE 1 END) AS "o_orderkey", min(F0."o_custkey") AS "o_custkey", max(F0."ub_o_orderkey") AS "ub_o_orderkey", min(F0."lb_o_orderkey") AS "lb_o_orderkey", max(F0."ub_o_custkey") AS "ub_o_custkey", min(F0."lb_o_custkey") AS "lb_o_custkey", sum(0) AS "cet_r", sum(0) AS "bst_r", sum(F0."bst_r") AS "pos_r"
FROM "orders_radb" AS F0
GROUP BY (CASE  WHEN (F0."o_orderkey" >= 300000) THEN 300000 WHEN ((F0."o_orderkey" < 300000) AND (F0."o_orderkey" >= 1)) THEN 1 ELSE 1 END)) F1 ON (((F0."lb_l_orderkey" <= F1."ub_o_orderkey") AND (F0."ub_l_orderkey" >= F1."lb_o_orderkey"))))) F0 JOIN (
SELECT (CASE  WHEN (F0."c_custkey" >= 7500) THEN 7500 WHEN ((F0."c_custkey" < 7500) AND (F0."c_custkey" >= 1)) THEN 1 ELSE 1 END) AS "c_custkey", min(F0."c_nationkey") AS "c_nationkey", max(F0."ub_c_custkey") AS "ub_c_custkey", min(F0."lb_c_custkey") AS "lb_c_custkey", max(F0."ub_c_nationkey") AS "ub_c_nationkey", min(F0."lb_c_nationkey") AS "lb_c_nationkey", sum(0) AS "cet_r", sum(0) AS "bst_r", sum(F0."bst_r") AS "pos_r"
FROM "customer_radb" AS F0
GROUP BY (CASE  WHEN (F0."c_custkey" >= 7500) THEN 7500 WHEN ((F0."c_custkey" < 7500) AND (F0."c_custkey" >= 1)) THEN 1 ELSE 1 END)) F1 ON (((F0."lb_o_custkey" <= F1."ub_c_custkey") AND (F0."ub_o_custkey" >= F1."lb_c_custkey"))))) F0 JOIN (
SELECT (CASE  WHEN (F0."n_nationkey" >= 12) THEN 12 WHEN ((F0."n_nationkey" < 12) AND (F0."n_nationkey" >= 0)) THEN 0 ELSE 0 END) AS "nk2", min(F0."n_name") AS "name2", max(F0."ub_n_nationkey") AS "ub_nk2", min(F0."lb_n_nationkey") AS "lb_nk2", max(F0."ub_n_name") AS "ub_name2", min(F0."lb_n_name") AS "lb_name2", sum(0) AS "cet_r", sum(0) AS "bst_r", sum(F0."bst_r") AS "pos_r"
FROM "nation_radb" AS F0
GROUP BY (CASE  WHEN (F0."n_nationkey" >= 12) THEN 12 WHEN ((F0."n_nationkey" < 12) AND (F0."n_nationkey" >= 0)) THEN 0 ELSE 0 END)) F1 ON (((F0."lb_c_nationkey" <= F1."ub_nk2") AND (F0."ub_c_nationkey" >= F1."lb_nk2"))))) F0
WHERE ((((F0."lb_name1" <= 'FRANCE') AND (F0."ub_name1" >= 'FRANCE')) AND ((F0."lb_name2" <= 'GERMANY') AND (F0."ub_name2" >= 'GERMANY'))) OR (((F0."lb_name1" <= 'GERMANY') AND (F0."ub_name1" >= 'GERMANY')) AND ((F0."lb_name2" <= 'FRANCE') AND (F0."ub_name2" >= 'FRANCE'))))) F1 ON ((((F0."ub_l_year" >= F1."lb_l_year") AND (F1."ub_l_year" >= F0."lb_l_year")) AND (((F0."ub_cust_nation" >= F1."lb_cust_nation") AND (F1."ub_cust_nation" >= F0."lb_cust_nation")) AND ((F0."ub_supp_nation" >= F1."lb_supp_nation") AND (F1."ub_supp_nation" >= F0."lb_supp_nation"))))))
GROUP BY F0."supp_nation", F0."ub_supp_nation", F0."lb_supp_nation", F0."cust_nation", F0."ub_cust_nation", F0."lb_cust_nation", F0."l_year", F0."ub_l_year", F0."lb_l_year";