SELECT F0."n1" AS "n1", F1."n2" AS "n2", F0."ub_n1" AS "ub_n1", F0."lb_n1" AS "lb_n1", F1."ub_n2" AS "ub_n2", F1."lb_n2" AS "lb_n2", (F0."cet_r" * F1."cet_r") AS "cet_r", (F0."bst_r" * F1."bst_r") AS "bst_r", (F0."pos_r" * F1."pos_r") AS "pos_r"
FROM ((
SELECT F0."n_name" AS "n1", F1."o_orderkey" AS "o1", F0."ub_n_name" AS "ub_n1", F0."lb_n_name" AS "lb_n1", F1."ub_o_orderkey" AS "ub_o1", F1."lb_o_orderkey" AS "lb_o1", (F0."cet_r" * F1."cet_r") AS "cet_r", (F0."bst_r" * F1."bst_r") AS "bst_r", (F0."pos_r" * F1."pos_r") AS "pos_r"
FROM ((
SELECT F0."tid" AS "tid", F0."c_custkey" AS "c_custkey", F0."c_name" AS "c_name", F0."c_address" AS "c_address", F0."c_nationkey" AS "c_nationkey", F0."c_phone" AS "c_phone", F0."c_acctbal" AS "c_acctbal", F0."c_mktsegment" AS "c_mktsegment", F0."c_comment" AS "c_comment", F1."tid" AS "tid1", F1."n_nationkey" AS "n_nationkey", F1."n_name" AS "n_name", F1."n_regionkey" AS "n_regionkey", F1."n_comment" AS "n_comment", F0."ub_tid" AS "ub_tid", F0."lb_tid" AS "lb_tid", F0."ub_c_custkey" AS "ub_c_custkey", F0."lb_c_custkey" AS "lb_c_custkey", F0."ub_c_name" AS "ub_c_name", F0."lb_c_name" AS "lb_c_name", F0."ub_c_address" AS "ub_c_address", F0."lb_c_address" AS "lb_c_address", F0."ub_c_nationkey" AS "ub_c_nationkey", F0."lb_c_nationkey" AS "lb_c_nationkey", F0."ub_c_phone" AS "ub_c_phone", F0."lb_c_phone" AS "lb_c_phone", F0."ub_c_acctbal" AS "ub_c_acctbal", F0."lb_c_acctbal" AS "lb_c_acctbal", F0."ub_c_mktsegment" AS "ub_c_mktsegment", F0."lb_c_mktsegment" AS "lb_c_mktsegment", F0."ub_c_comment" AS "ub_c_comment", F0."lb_c_comment" AS "lb_c_comment", F1."ub_tid" AS "ub_tid1", F1."lb_tid" AS "lb_tid1", F1."ub_n_nationkey" AS "ub_n_nationkey", F1."lb_n_nationkey" AS "lb_n_nationkey", F1."ub_n_name" AS "ub_n_name", F1."lb_n_name" AS "lb_n_name", F1."ub_n_regionkey" AS "ub_n_regionkey", F1."lb_n_regionkey" AS "lb_n_regionkey", F1."ub_n_comment" AS "ub_n_comment", F1."lb_n_comment" AS "lb_n_comment", (F0."cet_r" * F1."cet_r") AS "cet_r", (F0."bst_r" * F1."bst_r") AS "bst_r", (F0."pos_r" * F1."pos_r") AS "pos_r"
FROM ((
SELECT F0."tid" AS "tid", F0."c_custkey" AS "c_custkey", F0."c_name" AS "c_name", F0."c_address" AS "c_address", F0."c_nationkey" AS "c_nationkey", F0."c_phone" AS "c_phone", F0."c_acctbal" AS "c_acctbal", F0."c_mktsegment" AS "c_mktsegment", F0."c_comment" AS "c_comment", F0."tid" AS "ub_tid", F0."tid" AS "lb_tid", F0."c_custkey" AS "ub_c_custkey", F0."c_custkey" AS "lb_c_custkey", F0."c_name" AS "ub_c_name", F0."c_name" AS "lb_c_name", F0."c_address" AS "ub_c_address", F0."c_address" AS "lb_c_address", F0."c_nationkey" AS "ub_c_nationkey", F0."c_nationkey" AS "lb_c_nationkey", F0."c_phone" AS "ub_c_phone", F0."c_phone" AS "lb_c_phone", F0."c_acctbal" AS "ub_c_acctbal", F0."c_acctbal" AS "lb_c_acctbal", F0."c_mktsegment" AS "ub_c_mktsegment", F0."c_mktsegment" AS "lb_c_mktsegment", F0."c_comment" AS "ub_c_comment", F0."c_comment" AS "lb_c_comment", (CASE  WHEN (((((((((F0."ub_tid" = F0."lb_tid") AND (F0."ub_c_custkey" = F0."lb_c_custkey")) AND (F0."ub_c_name" = F0."lb_c_name")) AND (F0."ub_c_address" = F0."lb_c_address")) AND (F0."ub_c_nationkey" = F0."lb_c_nationkey")) AND (F0."ub_c_phone" = F0."lb_c_phone")) AND (F0."ub_c_acctbal" = F0."lb_c_acctbal")) AND (F0."ub_c_mktsegment" = F0."lb_c_mktsegment")) AND (F0."ub_c_comment" = F0."lb_c_comment")) THEN F0."cet_r" ELSE 0 END) AS "cet_r", F0."bst_r" AS "bst_r", F0."bst_r" AS "pos_r"
FROM (
SELECT F0."tid" AS "tid", F0."c_custkey" AS "c_custkey", F0."c_name" AS "c_name", F0."c_address" AS "c_address", F0."c_nationkey" AS "c_nationkey", F0."c_phone" AS "c_phone", F0."c_acctbal" AS "c_acctbal", F0."c_mktsegment" AS "c_mktsegment", F0."c_comment" AS "c_comment", F0."ub_tid" AS "ub_tid", F0."lb_tid" AS "lb_tid", F0."ub_c_custkey" AS "ub_c_custkey", F0."lb_c_custkey" AS "lb_c_custkey", F0."ub_c_name" AS "ub_c_name", F0."lb_c_name" AS "lb_c_name", F0."ub_c_address" AS "ub_c_address", F0."lb_c_address" AS "lb_c_address", F0."ub_c_nationkey" AS "ub_c_nationkey", F0."lb_c_nationkey" AS "lb_c_nationkey", F0."ub_c_phone" AS "ub_c_phone", F0."lb_c_phone" AS "lb_c_phone", F0."ub_c_acctbal" AS "ub_c_acctbal", F0."lb_c_acctbal" AS "lb_c_acctbal", F0."ub_c_mktsegment" AS "ub_c_mktsegment", F0."lb_c_mktsegment" AS "lb_c_mktsegment", F0."ub_c_comment" AS "ub_c_comment", F0."lb_c_comment" AS "lb_c_comment", F0."cet_r" AS "cet_r", F0."bst_r" AS "bst_r", F0."pos_r" AS "pos_r"
FROM "customer_radb" AS F0) F0
WHERE (F0."bst_r" > 0)) F0 JOIN (
SELECT F0."tid" AS "tid", F0."n_nationkey" AS "n_nationkey", F0."n_name" AS "n_name", F0."n_regionkey" AS "n_regionkey", F0."n_comment" AS "n_comment", F0."tid" AS "ub_tid", F0."tid" AS "lb_tid", F0."n_nationkey" AS "ub_n_nationkey", F0."n_nationkey" AS "lb_n_nationkey", F0."n_name" AS "ub_n_name", F0."n_name" AS "lb_n_name", F0."n_regionkey" AS "ub_n_regionkey", F0."n_regionkey" AS "lb_n_regionkey", F0."n_comment" AS "ub_n_comment", F0."n_comment" AS "lb_n_comment", (CASE  WHEN (((((F0."ub_tid" = F0."lb_tid") AND (F0."ub_n_nationkey" = F0."lb_n_nationkey")) AND (F0."ub_n_name" = F0."lb_n_name")) AND (F0."ub_n_regionkey" = F0."lb_n_regionkey")) AND (F0."ub_n_comment" = F0."lb_n_comment")) THEN F0."cet_r" ELSE 0 END) AS "cet_r", F0."bst_r" AS "bst_r", F0."bst_r" AS "pos_r"
FROM (
SELECT F0."tid" AS "tid", F0."n_nationkey" AS "n_nationkey", F0."n_name" AS "n_name", F0."n_regionkey" AS "n_regionkey", F0."n_comment" AS "n_comment", F0."ub_tid" AS "ub_tid", F0."lb_tid" AS "lb_tid", F0."ub_n_nationkey" AS "ub_n_nationkey", F0."lb_n_nationkey" AS "lb_n_nationkey", F0."ub_n_name" AS "ub_n_name", F0."lb_n_name" AS "lb_n_name", F0."ub_n_regionkey" AS "ub_n_regionkey", F0."lb_n_regionkey" AS "lb_n_regionkey", F0."ub_n_comment" AS "ub_n_comment", F0."lb_n_comment" AS "lb_n_comment", (CASE  WHEN ((F0."n_name" = 'CHINA') AND ((F0."ub_n_name" = F0."lb_n_name") AND ('CHINA' = 'CHINA'))) THEN 1 ELSE 0 END) AS "cet_r", (CASE  WHEN (F0."n_name" = 'CHINA') THEN 1 ELSE 0 END) AS "bst_r", F0."pos_r" AS "pos_r"
FROM (
SELECT F0."tid" AS "tid", F0."n_nationkey" AS "n_nationkey", F0."n_name" AS "n_name", F0."n_regionkey" AS "n_regionkey", F0."n_comment" AS "n_comment", F0."ub_tid" AS "ub_tid", F0."lb_tid" AS "lb_tid", F0."ub_n_nationkey" AS "ub_n_nationkey", F0."lb_n_nationkey" AS "lb_n_nationkey", F0."ub_n_name" AS "ub_n_name", F0."lb_n_name" AS "lb_n_name", F0."ub_n_regionkey" AS "ub_n_regionkey", F0."lb_n_regionkey" AS "lb_n_regionkey", F0."ub_n_comment" AS "ub_n_comment", F0."lb_n_comment" AS "lb_n_comment", F0."cet_r" AS "cet_r", F0."bst_r" AS "bst_r", F0."pos_r" AS "pos_r"
FROM "nation_radb" AS F0) F0
WHERE ((F0."lb_n_name" <= 'CHINA') AND (F0."ub_n_name" >= 'CHINA'))) F0
WHERE (F0."bst_r" > 0)) F1 ON ((F0."c_nationkey" = F1."n_nationkey")))) F0 JOIN (
SELECT F0."tid" AS "tid", F0."o_orderkey" AS "o_orderkey", F0."o_custkey" AS "o_custkey", F0."o_orderstatus" AS "o_orderstatus", F0."o_totalprice" AS "o_totalprice", F0."o_orderdate" AS "o_orderdate", F0."o_orderpriority" AS "o_orderpriority", F0."o_clerk" AS "o_clerk", F0."o_shippriority" AS "o_shippriority", F0."o_comment" AS "o_comment", F0."tid" AS "ub_tid", F0."tid" AS "lb_tid", F0."o_orderkey" AS "ub_o_orderkey", F0."o_orderkey" AS "lb_o_orderkey", F0."o_custkey" AS "ub_o_custkey", F0."o_custkey" AS "lb_o_custkey", F0."o_orderstatus" AS "ub_o_orderstatus", F0."o_orderstatus" AS "lb_o_orderstatus", F0."o_totalprice" AS "ub_o_totalprice", F0."o_totalprice" AS "lb_o_totalprice", F0."o_orderdate" AS "ub_o_orderdate", F0."o_orderdate" AS "lb_o_orderdate", F0."o_orderpriority" AS "ub_o_orderpriority", F0."o_orderpriority" AS "lb_o_orderpriority", F0."o_clerk" AS "ub_o_clerk", F0."o_clerk" AS "lb_o_clerk", F0."o_shippriority" AS "ub_o_shippriority", F0."o_shippriority" AS "lb_o_shippriority", F0."o_comment" AS "ub_o_comment", F0."o_comment" AS "lb_o_comment", (CASE  WHEN ((((((((((F0."ub_tid" = F0."lb_tid") AND (F0."ub_o_orderkey" = F0."lb_o_orderkey")) AND (F0."ub_o_custkey" = F0."lb_o_custkey")) AND (F0."ub_o_orderstatus" = F0."lb_o_orderstatus")) AND (F0."ub_o_totalprice" = F0."lb_o_totalprice")) AND (F0."ub_o_orderdate" = F0."lb_o_orderdate")) AND (F0."ub_o_orderpriority" = F0."lb_o_orderpriority")) AND (F0."ub_o_clerk" = F0."lb_o_clerk")) AND (F0."ub_o_shippriority" = F0."lb_o_shippriority")) AND (F0."ub_o_comment" = F0."lb_o_comment")) THEN F0."cet_r" ELSE 0 END) AS "cet_r", F0."bst_r" AS "bst_r", F0."bst_r" AS "pos_r"
FROM (
SELECT F0."tid" AS "tid", F0."o_orderkey" AS "o_orderkey", F0."o_custkey" AS "o_custkey", F0."o_orderstatus" AS "o_orderstatus", F0."o_totalprice" AS "o_totalprice", F0."o_orderdate" AS "o_orderdate", F0."o_orderpriority" AS "o_orderpriority", F0."o_clerk" AS "o_clerk", F0."o_shippriority" AS "o_shippriority", F0."o_comment" AS "o_comment", F0."ub_tid" AS "ub_tid", F0."lb_tid" AS "lb_tid", F0."ub_o_orderkey" AS "ub_o_orderkey", F0."lb_o_orderkey" AS "lb_o_orderkey", F0."ub_o_custkey" AS "ub_o_custkey", F0."lb_o_custkey" AS "lb_o_custkey", F0."ub_o_orderstatus" AS "ub_o_orderstatus", F0."lb_o_orderstatus" AS "lb_o_orderstatus", F0."ub_o_totalprice" AS "ub_o_totalprice", F0."lb_o_totalprice" AS "lb_o_totalprice", F0."ub_o_orderdate" AS "ub_o_orderdate", F0."lb_o_orderdate" AS "lb_o_orderdate", F0."ub_o_orderpriority" AS "ub_o_orderpriority", F0."lb_o_orderpriority" AS "lb_o_orderpriority", F0."ub_o_clerk" AS "ub_o_clerk", F0."lb_o_clerk" AS "lb_o_clerk", F0."ub_o_shippriority" AS "ub_o_shippriority", F0."lb_o_shippriority" AS "lb_o_shippriority", F0."ub_o_comment" AS "ub_o_comment", F0."lb_o_comment" AS "lb_o_comment", F0."cet_r" AS "cet_r", F0."bst_r" AS "bst_r", F0."pos_r" AS "pos_r"
FROM "orders_radb" AS F0) F0
WHERE (F0."bst_r" > 0)) F1 ON ((F0."c_custkey" = F1."o_custkey")))) F0 JOIN (
SELECT F0."n_name" AS "n2", F1."o_orderkey" AS "o2", F0."ub_n_name" AS "ub_n2", F0."lb_n_name" AS "lb_n2", F1."ub_o_orderkey" AS "ub_o2", F1."lb_o_orderkey" AS "lb_o2", (F0."cet_r" * F1."cet_r") AS "cet_r", (F0."bst_r" * F1."bst_r") AS "bst_r", (F0."pos_r" * F1."pos_r") AS "pos_r"
FROM ((
SELECT F0."n_name" AS "n_name", F0."n_nationkey" AS "n_nationkey", F0."s_suppkey" AS "s_suppkey", F0."s_nationkey" AS "s_nationkey", F1."l_orderkey" AS "l_orderkey", F1."l_suppkey" AS "l_suppkey", F0."ub_n_name" AS "ub_n_name", F0."lb_n_name" AS "lb_n_name", F0."ub_n_nationkey" AS "ub_n_nationkey", F0."lb_n_nationkey" AS "lb_n_nationkey", F0."ub_s_suppkey" AS "ub_s_suppkey", F0."lb_s_suppkey" AS "lb_s_suppkey", F0."ub_s_nationkey" AS "ub_s_nationkey", F0."lb_s_nationkey" AS "lb_s_nationkey", F1."ub_l_orderkey" AS "ub_l_orderkey", F1."lb_l_orderkey" AS "lb_l_orderkey", F1."ub_l_suppkey" AS "ub_l_suppkey", F1."lb_l_suppkey" AS "lb_l_suppkey", (F0."cet_r" * F1."cet_r") AS "cet_r", (F0."bst_r" * F1."bst_r") AS "bst_r", (F0."pos_r" * F1."pos_r") AS "pos_r"
FROM ((
SELECT F0."n_name" AS "n_name", F0."n_nationkey" AS "n_nationkey", F1."s_suppkey" AS "s_suppkey", F1."s_nationkey" AS "s_nationkey", F0."ub_n_name" AS "ub_n_name", F0."lb_n_name" AS "lb_n_name", F0."ub_n_nationkey" AS "ub_n_nationkey", F0."lb_n_nationkey" AS "lb_n_nationkey", F1."ub_s_suppkey" AS "ub_s_suppkey", F1."lb_s_suppkey" AS "lb_s_suppkey", F1."ub_s_nationkey" AS "ub_s_nationkey", F1."lb_s_nationkey" AS "lb_s_nationkey", (F0."cet_r" * F1."cet_r") AS "cet_r", (F0."bst_r" * F1."bst_r") AS "bst_r", (F0."pos_r" * F1."pos_r") AS "pos_r"
FROM ((
SELECT F0."n_name" AS "n_name", F0."n_nationkey" AS "n_nationkey", F0."n_name" AS "ub_n_name", F0."n_name" AS "lb_n_name", F0."n_nationkey" AS "ub_n_nationkey", F0."n_nationkey" AS "lb_n_nationkey", (CASE  WHEN ((F0."ub_n_name" = F0."lb_n_name") AND (F0."ub_n_nationkey" = F0."lb_n_nationkey")) THEN F0."cet_r" ELSE 0 END) AS "cet_r", F0."bst_r" AS "bst_r", F0."bst_r" AS "pos_r"
FROM (
SELECT F0."n_name" AS "n_name", F0."n_nationkey" AS "n_nationkey", F0."ub_n_name" AS "ub_n_name", F0."lb_n_name" AS "lb_n_name", F0."ub_n_nationkey" AS "ub_n_nationkey", F0."lb_n_nationkey" AS "lb_n_nationkey", (CASE  WHEN ((F0."n_name" = 'GERMANY') AND ((F0."ub_n_name" = F0."lb_n_name") AND ('GERMANY' = 'GERMANY'))) THEN 1 ELSE 0 END) AS "cet_r", (CASE  WHEN (F0."n_name" = 'GERMANY') THEN 1 ELSE 0 END) AS "bst_r", F0."pos_r" AS "pos_r"
FROM (
SELECT F0."tid" AS "tid", F0."n_nationkey" AS "n_nationkey", F0."n_name" AS "n_name", F0."n_regionkey" AS "n_regionkey", F0."n_comment" AS "n_comment", F0."ub_tid" AS "ub_tid", F0."lb_tid" AS "lb_tid", F0."ub_n_nationkey" AS "ub_n_nationkey", F0."lb_n_nationkey" AS "lb_n_nationkey", F0."ub_n_name" AS "ub_n_name", F0."lb_n_name" AS "lb_n_name", F0."ub_n_regionkey" AS "ub_n_regionkey", F0."lb_n_regionkey" AS "lb_n_regionkey", F0."ub_n_comment" AS "ub_n_comment", F0."lb_n_comment" AS "lb_n_comment", F0."cet_r" AS "cet_r", F0."bst_r" AS "bst_r", F0."pos_r" AS "pos_r"
FROM "nation_radb" AS F0) F0
WHERE ((F0."lb_n_name" <= 'GERMANY') AND (F0."ub_n_name" >= 'GERMANY'))) F0
WHERE (F0."bst_r" > 0)) F0 JOIN (
SELECT F0."s_suppkey" AS "s_suppkey", F0."s_nationkey" AS "s_nationkey", F0."s_suppkey" AS "ub_s_suppkey", F0."s_suppkey" AS "lb_s_suppkey", F0."s_nationkey" AS "ub_s_nationkey", F0."s_nationkey" AS "lb_s_nationkey", (CASE  WHEN ((F0."ub_s_suppkey" = F0."lb_s_suppkey") AND (F0."ub_s_nationkey" = F0."lb_s_nationkey")) THEN F0."cet_r" ELSE 0 END) AS "cet_r", F0."bst_r" AS "bst_r", F0."bst_r" AS "pos_r"
FROM (
SELECT F0."s_suppkey" AS "s_suppkey", F0."s_nationkey" AS "s_nationkey", F0."ub_s_suppkey" AS "ub_s_suppkey", F0."lb_s_suppkey" AS "lb_s_suppkey", F0."ub_s_nationkey" AS "ub_s_nationkey", F0."lb_s_nationkey" AS "lb_s_nationkey", F0."cet_r" AS "cet_r", F0."bst_r" AS "bst_r", F0."pos_r" AS "pos_r"
FROM "supplier_radb" AS F0) F0
WHERE (F0."bst_r" > 0)) F1 ON ((F0."n_nationkey" = F1."s_nationkey")))) F0 JOIN (
SELECT F0."l_orderkey" AS "l_orderkey", F0."l_suppkey" AS "l_suppkey", F0."l_orderkey" AS "ub_l_orderkey", F0."l_orderkey" AS "lb_l_orderkey", F0."l_suppkey" AS "ub_l_suppkey", F0."l_suppkey" AS "lb_l_suppkey", (CASE  WHEN ((F0."ub_l_orderkey" = F0."lb_l_orderkey") AND (F0."ub_l_suppkey" = F0."lb_l_suppkey")) THEN F0."cet_r" ELSE 0 END) AS "cet_r", F0."bst_r" AS "bst_r", F0."bst_r" AS "pos_r"
FROM (
SELECT F0."l_orderkey" AS "l_orderkey", F0."l_suppkey" AS "l_suppkey", F0."ub_l_orderkey" AS "ub_l_orderkey", F0."lb_l_orderkey" AS "lb_l_orderkey", F0."ub_l_suppkey" AS "ub_l_suppkey", F0."lb_l_suppkey" AS "lb_l_suppkey", F0."cet_r" AS "cet_r", F0."bst_r" AS "bst_r", F0."pos_r" AS "pos_r"
FROM "lineitem_radb" AS F0) F0
WHERE (F0."bst_r" > 0)) F1 ON ((F0."s_suppkey" = F1."l_suppkey")))) F0 JOIN (
SELECT F0."o_orderkey" AS "o_orderkey", F0."o_orderkey" AS "ub_o_orderkey", F0."o_orderkey" AS "lb_o_orderkey", (CASE  WHEN (F0."ub_o_orderkey" = F0."lb_o_orderkey") THEN F0."cet_r" ELSE 0 END) AS "cet_r", F0."bst_r" AS "bst_r", F0."bst_r" AS "pos_r"
FROM (
SELECT F0."o_orderkey" AS "o_orderkey", F0."ub_o_orderkey" AS "ub_o_orderkey", F0."lb_o_orderkey" AS "lb_o_orderkey", F0."cet_r" AS "cet_r", F0."bst_r" AS "bst_r", F0."pos_r" AS "pos_r"
FROM "orders_radb" AS F0) F0
WHERE (F0."bst_r" > 0)) F1 ON ((F0."l_orderkey" = F1."o_orderkey")))) F1 ON ((F0."o1" = F1."o2"))) UNION ALL 
SELECT F0."n1" AS "n1", F1."n2" AS "n2", F0."ub_n1" AS "ub_n1", F0."lb_n1" AS "lb_n1", F1."ub_n2" AS "ub_n2", F1."lb_n2" AS "lb_n2", ((F0."cet_r" + F1."cet_r") + (CASE  WHEN ((F0."o1" = F1."o2") AND ((F0."ub_o1" = F0."lb_o1") AND (F1."ub_o2" = F1."lb_o2"))) THEN 1 ELSE 0 END)) AS "cet_r", ((F0."bst_r" + F1."bst_r") + (CASE  WHEN (F0."o1" = F1."o2") THEN 1 ELSE 0 END)) AS "bst_r", (F0."pos_r" + F1."pos_r") AS "pos_r"
FROM ((
SELECT F0."n_name" AS "n1", F1."o_orderkey" AS "o1", F0."ub_n_name" AS "ub_n1", F0."lb_n_name" AS "lb_n1", F1."ub_o_orderkey" AS "ub_o1", F1."lb_o_orderkey" AS "lb_o1", ((F0."cet_r" + F1."cet_r") + (CASE  WHEN ((F0."c_custkey" = F1."o_custkey") AND ((F0."ub_c_custkey" = F0."lb_c_custkey") AND (F1."ub_o_custkey" = F1."lb_o_custkey"))) THEN 1 ELSE 0 END)) AS "cet_r", ((F0."bst_r" + F1."bst_r") + (CASE  WHEN (F0."c_custkey" = F1."o_custkey") THEN 1 ELSE 0 END)) AS "bst_r", (F0."pos_r" + F1."pos_r") AS "pos_r"
FROM ((
SELECT F0."tid" AS "tid", F0."c_custkey" AS "c_custkey", F0."c_name" AS "c_name", F0."c_address" AS "c_address", F0."c_nationkey" AS "c_nationkey", F0."c_phone" AS "c_phone", F0."c_acctbal" AS "c_acctbal", F0."c_mktsegment" AS "c_mktsegment", F0."c_comment" AS "c_comment", F1."tid" AS "tid1", F1."n_nationkey" AS "n_nationkey", F1."n_name" AS "n_name", F1."n_regionkey" AS "n_regionkey", F1."n_comment" AS "n_comment", F0."ub_tid" AS "ub_tid", F0."lb_tid" AS "lb_tid", F0."ub_c_custkey" AS "ub_c_custkey", F0."lb_c_custkey" AS "lb_c_custkey", F0."ub_c_name" AS "ub_c_name", F0."lb_c_name" AS "lb_c_name", F0."ub_c_address" AS "ub_c_address", F0."lb_c_address" AS "lb_c_address", F0."ub_c_nationkey" AS "ub_c_nationkey", F0."lb_c_nationkey" AS "lb_c_nationkey", F0."ub_c_phone" AS "ub_c_phone", F0."lb_c_phone" AS "lb_c_phone", F0."ub_c_acctbal" AS "ub_c_acctbal", F0."lb_c_acctbal" AS "lb_c_acctbal", F0."ub_c_mktsegment" AS "ub_c_mktsegment", F0."lb_c_mktsegment" AS "lb_c_mktsegment", F0."ub_c_comment" AS "ub_c_comment", F0."lb_c_comment" AS "lb_c_comment", F1."ub_tid" AS "ub_tid1", F1."lb_tid" AS "lb_tid1", F1."ub_n_nationkey" AS "ub_n_nationkey", F1."lb_n_nationkey" AS "lb_n_nationkey", F1."ub_n_name" AS "ub_n_name", F1."lb_n_name" AS "lb_n_name", F1."ub_n_regionkey" AS "ub_n_regionkey", F1."lb_n_regionkey" AS "lb_n_regionkey", F1."ub_n_comment" AS "ub_n_comment", F1."lb_n_comment" AS "lb_n_comment", ((F0."cet_r" + F1."cet_r") + (CASE  WHEN ((F0."c_nationkey" = F1."n_nationkey") AND ((F0."ub_c_nationkey" = F0."lb_c_nationkey") AND (F1."ub_n_nationkey" = F1."lb_n_nationkey"))) THEN 1 ELSE 0 END)) AS "cet_r", ((F0."bst_r" + F1."bst_r") + (CASE  WHEN (F0."c_nationkey" = F1."n_nationkey") THEN 1 ELSE 0 END)) AS "bst_r", (F0."pos_r" + F1."pos_r") AS "pos_r"
FROM ((
SELECT min(F0."tid") AS "tid", min(F0."c_custkey") AS "c_custkey", min(F0."c_name") AS "c_name", min(F0."c_address") AS "c_address", (CASE  WHEN (F0."c_nationkey" >= 12) THEN 12 WHEN ((F0."c_nationkey" < 12) AND (F0."c_nationkey" >= 0)) THEN 0 ELSE 0 END) AS "c_nationkey", min(F0."c_phone") AS "c_phone", min(F0."c_acctbal") AS "c_acctbal", min(F0."c_mktsegment") AS "c_mktsegment", min(F0."c_comment") AS "c_comment", max(F0."ub_tid") AS "ub_tid", min(F0."lb_tid") AS "lb_tid", max(F0."ub_c_custkey") AS "ub_c_custkey", min(F0."lb_c_custkey") AS "lb_c_custkey", max(F0."ub_c_name") AS "ub_c_name", min(F0."lb_c_name") AS "lb_c_name", max(F0."ub_c_address") AS "ub_c_address", min(F0."lb_c_address") AS "lb_c_address", max(F0."ub_c_nationkey") AS "ub_c_nationkey", min(F0."lb_c_nationkey") AS "lb_c_nationkey", max(F0."ub_c_phone") AS "ub_c_phone", min(F0."lb_c_phone") AS "lb_c_phone", max(F0."ub_c_acctbal") AS "ub_c_acctbal", min(F0."lb_c_acctbal") AS "lb_c_acctbal", max(F0."ub_c_mktsegment") AS "ub_c_mktsegment", min(F0."lb_c_mktsegment") AS "lb_c_mktsegment", max(F0."ub_c_comment") AS "ub_c_comment", min(F0."lb_c_comment") AS "lb_c_comment", sum(0) AS "cet_r", sum(0) AS "bst_r", sum(F0."bst_r") AS "pos_r"
FROM "customer_radb" AS F0
GROUP BY (CASE  WHEN (F0."c_nationkey" >= 12) THEN 12 WHEN ((F0."c_nationkey" < 12) AND (F0."c_nationkey" >= 0)) THEN 0 ELSE 0 END)) F0 JOIN (
SELECT min(F0."tid") AS "tid", (CASE  WHEN (F0."n_nationkey" >= 12) THEN 12 WHEN ((F0."n_nationkey" < 12) AND (F0."n_nationkey" >= 0)) THEN 0 ELSE 0 END) AS "n_nationkey", min(F0."n_name") AS "n_name", min(F0."n_regionkey") AS "n_regionkey", min(F0."n_comment") AS "n_comment", max(F0."ub_tid") AS "ub_tid", min(F0."lb_tid") AS "lb_tid", max(F0."ub_n_nationkey") AS "ub_n_nationkey", min(F0."lb_n_nationkey") AS "lb_n_nationkey", max(F0."ub_n_name") AS "ub_n_name", min(F0."lb_n_name") AS "lb_n_name", max(F0."ub_n_regionkey") AS "ub_n_regionkey", min(F0."lb_n_regionkey") AS "lb_n_regionkey", max(F0."ub_n_comment") AS "ub_n_comment", min(F0."lb_n_comment") AS "lb_n_comment", sum(0) AS "cet_r", sum(0) AS "bst_r", sum((CASE  WHEN (F0."n_name" = 'CHINA') THEN 1 ELSE 0 END)) AS "pos_r"
FROM (
SELECT F0."tid" AS "tid", F0."n_nationkey" AS "n_nationkey", F0."n_name" AS "n_name", F0."n_regionkey" AS "n_regionkey", F0."n_comment" AS "n_comment", F0."ub_tid" AS "ub_tid", F0."lb_tid" AS "lb_tid", F0."ub_n_nationkey" AS "ub_n_nationkey", F0."lb_n_nationkey" AS "lb_n_nationkey", F0."ub_n_name" AS "ub_n_name", F0."lb_n_name" AS "lb_n_name", F0."ub_n_regionkey" AS "ub_n_regionkey", F0."lb_n_regionkey" AS "lb_n_regionkey", F0."ub_n_comment" AS "ub_n_comment", F0."lb_n_comment" AS "lb_n_comment", F0."cet_r" AS "cet_r", F0."bst_r" AS "bst_r", F0."pos_r" AS "pos_r"
FROM "nation_radb" AS F0) F0
WHERE ((F0."lb_n_name" <= 'CHINA') AND (F0."ub_n_name" >= 'CHINA'))
GROUP BY (CASE  WHEN (F0."n_nationkey" >= 12) THEN 12 WHEN ((F0."n_nationkey" < 12) AND (F0."n_nationkey" >= 0)) THEN 0 ELSE 0 END)) F1 ON (((F0."lb_c_nationkey" <= F1."ub_n_nationkey") AND (F0."ub_c_nationkey" >= F1."lb_n_nationkey"))))) F0 JOIN (
SELECT min(F0."tid") AS "tid", min(F0."o_orderkey") AS "o_orderkey", (CASE  WHEN (F0."o_custkey" >= 7500) THEN 7500 WHEN ((F0."o_custkey" < 7500) AND (F0."o_custkey" >= 1)) THEN 1 ELSE 1 END) AS "o_custkey", min(F0."o_orderstatus") AS "o_orderstatus", min(F0."o_totalprice") AS "o_totalprice", min(F0."o_orderdate") AS "o_orderdate", min(F0."o_orderpriority") AS "o_orderpriority", min(F0."o_clerk") AS "o_clerk", min(F0."o_shippriority") AS "o_shippriority", min(F0."o_comment") AS "o_comment", max(F0."ub_tid") AS "ub_tid", min(F0."lb_tid") AS "lb_tid", max(F0."ub_o_orderkey") AS "ub_o_orderkey", min(F0."lb_o_orderkey") AS "lb_o_orderkey", max(F0."ub_o_custkey") AS "ub_o_custkey", min(F0."lb_o_custkey") AS "lb_o_custkey", max(F0."ub_o_orderstatus") AS "ub_o_orderstatus", min(F0."lb_o_orderstatus") AS "lb_o_orderstatus", max(F0."ub_o_totalprice") AS "ub_o_totalprice", min(F0."lb_o_totalprice") AS "lb_o_totalprice", max(F0."ub_o_orderdate") AS "ub_o_orderdate", min(F0."lb_o_orderdate") AS "lb_o_orderdate", max(F0."ub_o_orderpriority") AS "ub_o_orderpriority", min(F0."lb_o_orderpriority") AS "lb_o_orderpriority", max(F0."ub_o_clerk") AS "ub_o_clerk", min(F0."lb_o_clerk") AS "lb_o_clerk", max(F0."ub_o_shippriority") AS "ub_o_shippriority", min(F0."lb_o_shippriority") AS "lb_o_shippriority", max(F0."ub_o_comment") AS "ub_o_comment", min(F0."lb_o_comment") AS "lb_o_comment", sum(0) AS "cet_r", sum(0) AS "bst_r", sum(F0."bst_r") AS "pos_r"
FROM "orders_radb" AS F0
GROUP BY (CASE  WHEN (F0."o_custkey" >= 7500) THEN 7500 WHEN ((F0."o_custkey" < 7500) AND (F0."o_custkey" >= 1)) THEN 1 ELSE 1 END)) F1 ON (((F0."lb_c_custkey" <= F1."ub_o_custkey") AND (F0."ub_c_custkey" >= F1."lb_o_custkey"))))) F0 JOIN (
SELECT F0."n_name" AS "n2", F1."o_orderkey" AS "o2", F0."ub_n_name" AS "ub_n2", F0."lb_n_name" AS "lb_n2", F1."ub_o_orderkey" AS "ub_o2", F1."lb_o_orderkey" AS "lb_o2", ((F0."cet_r" + F1."cet_r") + (CASE  WHEN ((F0."l_orderkey" = F1."o_orderkey") AND ((F0."ub_l_orderkey" = F0."lb_l_orderkey") AND (F1."ub_o_orderkey" = F1."lb_o_orderkey"))) THEN 1 ELSE 0 END)) AS "cet_r", ((F0."bst_r" + F1."bst_r") + (CASE  WHEN (F0."l_orderkey" = F1."o_orderkey") THEN 1 ELSE 0 END)) AS "bst_r", (F0."pos_r" + F1."pos_r") AS "pos_r"
FROM ((
SELECT F0."n_name" AS "n_name", F0."n_nationkey" AS "n_nationkey", F0."s_suppkey" AS "s_suppkey", F0."s_nationkey" AS "s_nationkey", F1."l_orderkey" AS "l_orderkey", F1."l_suppkey" AS "l_suppkey", F0."ub_n_name" AS "ub_n_name", F0."lb_n_name" AS "lb_n_name", F0."ub_n_nationkey" AS "ub_n_nationkey", F0."lb_n_nationkey" AS "lb_n_nationkey", F0."ub_s_suppkey" AS "ub_s_suppkey", F0."lb_s_suppkey" AS "lb_s_suppkey", F0."ub_s_nationkey" AS "ub_s_nationkey", F0."lb_s_nationkey" AS "lb_s_nationkey", F1."ub_l_orderkey" AS "ub_l_orderkey", F1."lb_l_orderkey" AS "lb_l_orderkey", F1."ub_l_suppkey" AS "ub_l_suppkey", F1."lb_l_suppkey" AS "lb_l_suppkey", ((F0."cet_r" + F1."cet_r") + (CASE  WHEN ((F0."s_suppkey" = F1."l_suppkey") AND ((F0."ub_s_suppkey" = F0."lb_s_suppkey") AND (F1."ub_l_suppkey" = F1."lb_l_suppkey"))) THEN 1 ELSE 0 END)) AS "cet_r", ((F0."bst_r" + F1."bst_r") + (CASE  WHEN (F0."s_suppkey" = F1."l_suppkey") THEN 1 ELSE 0 END)) AS "bst_r", (F0."pos_r" + F1."pos_r") AS "pos_r"
FROM ((
SELECT F0."n_name" AS "n_name", F0."n_nationkey" AS "n_nationkey", F1."s_suppkey" AS "s_suppkey", F1."s_nationkey" AS "s_nationkey", F0."ub_n_name" AS "ub_n_name", F0."lb_n_name" AS "lb_n_name", F0."ub_n_nationkey" AS "ub_n_nationkey", F0."lb_n_nationkey" AS "lb_n_nationkey", F1."ub_s_suppkey" AS "ub_s_suppkey", F1."lb_s_suppkey" AS "lb_s_suppkey", F1."ub_s_nationkey" AS "ub_s_nationkey", F1."lb_s_nationkey" AS "lb_s_nationkey", ((F0."cet_r" + F1."cet_r") + (CASE  WHEN ((F0."n_nationkey" = F1."s_nationkey") AND ((F0."ub_n_nationkey" = F0."lb_n_nationkey") AND (F1."ub_s_nationkey" = F1."lb_s_nationkey"))) THEN 1 ELSE 0 END)) AS "cet_r", ((F0."bst_r" + F1."bst_r") + (CASE  WHEN (F0."n_nationkey" = F1."s_nationkey") THEN 1 ELSE 0 END)) AS "bst_r", (F0."pos_r" + F1."pos_r") AS "pos_r"
FROM ((
SELECT min(F0."n_name") AS "n_name", (CASE  WHEN (F0."n_nationkey" >= 12) THEN 12 WHEN ((F0."n_nationkey" < 12) AND (F0."n_nationkey" >= 0)) THEN 0 ELSE 0 END) AS "n_nationkey", max(F0."ub_n_name") AS "ub_n_name", min(F0."lb_n_name") AS "lb_n_name", max(F0."ub_n_nationkey") AS "ub_n_nationkey", min(F0."lb_n_nationkey") AS "lb_n_nationkey", sum(0) AS "cet_r", sum(0) AS "bst_r", sum((CASE  WHEN (F0."n_name" = 'GERMANY') THEN 1 ELSE 0 END)) AS "pos_r"
FROM (
SELECT F0."tid" AS "tid", F0."n_nationkey" AS "n_nationkey", F0."n_name" AS "n_name", F0."n_regionkey" AS "n_regionkey", F0."n_comment" AS "n_comment", F0."ub_tid" AS "ub_tid", F0."lb_tid" AS "lb_tid", F0."ub_n_nationkey" AS "ub_n_nationkey", F0."lb_n_nationkey" AS "lb_n_nationkey", F0."ub_n_name" AS "ub_n_name", F0."lb_n_name" AS "lb_n_name", F0."ub_n_regionkey" AS "ub_n_regionkey", F0."lb_n_regionkey" AS "lb_n_regionkey", F0."ub_n_comment" AS "ub_n_comment", F0."lb_n_comment" AS "lb_n_comment", F0."cet_r" AS "cet_r", F0."bst_r" AS "bst_r", F0."pos_r" AS "pos_r"
FROM "nation_radb" AS F0) F0
WHERE ((F0."lb_n_name" <= 'GERMANY') AND (F0."ub_n_name" >= 'GERMANY'))
GROUP BY (CASE  WHEN (F0."n_nationkey" >= 12) THEN 12 WHEN ((F0."n_nationkey" < 12) AND (F0."n_nationkey" >= 0)) THEN 0 ELSE 0 END)) F0 JOIN (
SELECT min(F0."s_suppkey") AS "s_suppkey", (CASE  WHEN (F0."s_nationkey" >= 12) THEN 12 WHEN ((F0."s_nationkey" < 12) AND (F0."s_nationkey" >= 0)) THEN 0 ELSE 0 END) AS "s_nationkey", max(F0."ub_s_suppkey") AS "ub_s_suppkey", min(F0."lb_s_suppkey") AS "lb_s_suppkey", max(F0."ub_s_nationkey") AS "ub_s_nationkey", min(F0."lb_s_nationkey") AS "lb_s_nationkey", sum(0) AS "cet_r", sum(0) AS "bst_r", sum(F0."bst_r") AS "pos_r"
FROM "supplier_radb" AS F0
GROUP BY (CASE  WHEN (F0."s_nationkey" >= 12) THEN 12 WHEN ((F0."s_nationkey" < 12) AND (F0."s_nationkey" >= 0)) THEN 0 ELSE 0 END)) F1 ON (((F0."lb_n_nationkey" <= F1."ub_s_nationkey") AND (F0."ub_n_nationkey" >= F1."lb_s_nationkey"))))) F0 JOIN (
SELECT min(F0."l_orderkey") AS "l_orderkey", (CASE  WHEN (F0."l_suppkey" >= 500) THEN 500 WHEN ((F0."l_suppkey" < 500) AND (F0."l_suppkey" >= 1)) THEN 1 ELSE 1 END) AS "l_suppkey", max(F0."ub_l_orderkey") AS "ub_l_orderkey", min(F0."lb_l_orderkey") AS "lb_l_orderkey", max(F0."ub_l_suppkey") AS "ub_l_suppkey", min(F0."lb_l_suppkey") AS "lb_l_suppkey", sum(0) AS "cet_r", sum(0) AS "bst_r", sum(F0."bst_r") AS "pos_r"
FROM "lineitem_radb" AS F0
GROUP BY (CASE  WHEN (F0."l_suppkey" >= 500) THEN 500 WHEN ((F0."l_suppkey" < 500) AND (F0."l_suppkey" >= 1)) THEN 1 ELSE 1 END)) F1 ON (((F0."lb_s_suppkey" <= F1."ub_l_suppkey") AND (F0."ub_s_suppkey" >= F1."lb_l_suppkey"))))) F0 JOIN (
SELECT (CASE  WHEN (F0."o_orderkey" >= 300000) THEN 300000 WHEN ((F0."o_orderkey" < 300000) AND (F0."o_orderkey" >= 1)) THEN 1 ELSE 1 END) AS "o_orderkey", max(F0."ub_o_orderkey") AS "ub_o_orderkey", min(F0."lb_o_orderkey") AS "lb_o_orderkey", sum(0) AS "cet_r", sum(0) AS "bst_r", sum(F0."bst_r") AS "pos_r"
FROM "orders_radb" AS F0
GROUP BY (CASE  WHEN (F0."o_orderkey" >= 300000) THEN 300000 WHEN ((F0."o_orderkey" < 300000) AND (F0."o_orderkey" >= 1)) THEN 1 ELSE 1 END)) F1 ON (((F0."lb_l_orderkey" <= F1."ub_o_orderkey") AND (F0."ub_l_orderkey" >= F1."lb_o_orderkey"))))) F1 ON (((F0."lb_o1" <= F1."ub_o2") AND (F0."ub_o1" >= F1."lb_o2"))));